"""Generate the *public* wgpu API from ``webgpu.idl`` + the bridge.

``bindgen.generate`` emits the low-level layer (C structs, C method tables,
integer enums) straight from ``webgpu.json``. This module emits what users
actually import: string enums, flag classes, struct dataclasses, and the
``GPU*`` classes with real WebGPU signatures.

The two halves meet in :mod:`bindgen.bridge`, which knows that the IDL's
``mappedAtCreation`` is the C spec's ``mapped_at_creation`` and that
``"rgba8unorm"`` is ``WGPUTextureFormat_RGBA8Unorm``. Because that mapping is
resolved *here*, at generation time, the runtime does no name translation: the
generated code already speaks C-side names and integers.
"""

from __future__ import annotations

import keyword
import re
from pathlib import Path

from . import bridge, paths

GENERATED_DIR = paths.REPO_ROOT / "wgpu" / "_generated"

_BANNER = """\
# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Public API surface, generated from bindgen/resources/webgpu.idl (the W3C
# WebGPU Web IDL) and cross-referenced against the wgpu-native C spec. Re-run
# the generator after updating either spec.
"""


def _ident(name: str) -> str:
    return name + "_" if keyword.iskeyword(name) else name


def _annotate(idl, typename: str, *, optional: bool = False) -> str:
    """Resolve an IDL type to a Python annotation.

    Sequences are annotated as ``Sequence`` rather than ``list`` because the API
    accepts any sequence, and anything that defaults to ``None`` is widened so
    the annotation does not lie about it.
    """
    ann = idl.resolve_type(typename)
    while "list[" in ann:
        ann = ann.replace("list[", "Sequence[", 1)
    if optional and "None" not in ann:
        ann += " | None"
    return ann


# ---- enums -----------------------------------------------------------------


def generate_api_enums(b: bridge.Bridge, lib) -> str:
    """Emit the string-valued enums plus their string -> C-integer maps.

    Enum *values* are the WebGPU strings (``"rgba8unorm"``), because that is
    what the web API and existing wgpu-py code use -- ``TextureFormat.rgba8unorm
    == "rgba8unorm"`` holds. The integers the C API wants are resolved here and
    baked into ``TO_INT`` so no lookup logic ships in the runtime.
    """
    from . import naming

    lines = [
        _BANNER,
        '"""WebGPU enums. Values are strings, so ``wgpu.TextureFormat.rgba8unorm``',
        'and ``"rgba8unorm"`` are interchangeable."""',
        "",
        "from wgpu._api.maps import EnumMap as _EnumMap",
        "",
        "",
        "class Enum:",
        '    """Base class for wgpu enums."""',
        "",
        "    def __init__(self):",
        '        raise RuntimeError("Cannot instantiate an enum.")',
        "",
    ]
    names = sorted(b.idl.enums)
    lines.append("")
    lines.append("__all__ = [")
    lines += [f"    {n!r}," for n in names]
    lines.append("]")
    lines.append("")

    for idl_name in names:
        members = b.idl.enums[idl_name]
        lines.append("")
        lines.append(f"class {idl_name}(Enum):")
        for key, value in members.items():
            lines.append(f"    {_ident(key)} = {value!r}")
        lines.append("")

    # spec-enum-name -> {public string | int -> C int}
    lines.append("")
    lines.append("#: C-spec enum name -> mapping of accepted value to C integer.")
    lines.append("TO_INT: dict[str, _EnumMap] = {}")
    lines.append("")
    for idl_name in names:
        spec_name = b.enum_types.get(idl_name)
        if spec_name is None:
            continue  # web-only enum, never crosses the FFI boundary
        pairs = []
        for value in b.idl.enums[idl_name].values():
            entry = b.enum_values[(idl_name, value)]
            c_int = int(getattr(lib, naming.c_enum_value(spec_name, entry)))
            pairs.append((value, c_int))
        lines.append(f"TO_INT[{spec_name!r}] = _EnumMap({idl_name!r}, {{")
        lines += [f"    {v!r}: {i}," for v, i in pairs]
        lines.append("})")
        lines.append("")
    return "\n".join(lines)


# ---- flags -----------------------------------------------------------------


def generate_api_flags(b: bridge.Bridge) -> str:
    """Emit the integer flag classes plus their name -> integer maps.

    Flag values come from the IDL rather than the C header: they are part of the
    WebGPU spec, and the bridge asserts the two agree.
    """
    lines = [
        _BANNER,
        '"""WebGPU flags: integer bitmasks. ``BufferUsage.MAP_READ | BufferUsage.COPY_DST``',
        'can also be written as ``"MAP_READ|COPY_DST"``."""',
        "",
        "from wgpu._api.maps import FlagMap as _FlagMap",
        "",
        "",
        "class Flags:",
        '    """Base class for wgpu flags."""',
        "",
        "    def __init__(self):",
        '        raise RuntimeError("Cannot instantiate a flags class.")',
        "",
    ]
    names = sorted(b.idl.flags)
    lines.append("")
    lines.append("__all__ = [")
    lines += [f"    {n!r}," for n in names]
    lines.append("]")
    lines.append("")

    for idl_name in names:
        lines.append("")
        lines.append(f"class {idl_name}(Flags):")
        for key, value in b.idl.flags[idl_name].items():
            lines.append(f"    {_ident(key)} = {value}")
        lines.append("")

    lines.append("")
    lines.append("#: C-spec bitflag name -> mapping that accepts ints and 'A|B' strings.")
    lines.append("TO_INT: dict[str, _FlagMap] = {}")
    lines.append("")
    for idl_name in names:
        spec_name = b.flag_types[idl_name]
        lines.append(f"TO_INT[{spec_name!r}] = _FlagMap({idl_name!r}, {{")
        lines += [f"    {k!r}: {v}," for k, v in b.idl.flags[idl_name].items()]
        lines.append("})")
        lines.append("")
    return "\n".join(lines)


# ---- structs ---------------------------------------------------------------


def _params(line: str) -> list:
    """Split an IDL function signature's parameter list into Attributes."""
    from .idl import Attribute

    inner = line[line.index("(") + 1 : line.rindex(")")].strip()
    if not inner:
        return []
    parts, depth, cur = [], 0, ""
    for ch in inner:
        if ch in "<([":
            depth += 1
        elif ch in ">)]":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        parts.append(cur)
    return [Attribute(p, "param") for p in parts]


def _default_repr(default: str | None, typename: str, idl) -> str:
    """Render an IDL default as a Python literal."""
    if default is None:
        return "None"
    d = default.strip()
    if d in ("True", "False", "None"):
        return d
    if d == '""':
        return '""'
    if d == "{}":
        return "None"  # an empty descriptor: the runtime fills in defaults
    if d == "[]":
        return "()"
    if re.fullmatch(r"-?\d+", d):
        return d
    if re.fullmatch(r"-?\d*\.\d+", d):
        return d
    if d.startswith('"'):
        return d
    # An enum constant such as GPUTextureAspect."all" arrives quoted already;
    # anything else is a name we pass through untouched.
    return repr(d.strip('"'))


def generate_api_structs(b: bridge.Bridge) -> str:
    """Emit the public struct dataclasses.

    These are for typing, autocompletion and docs; plain dicts work everywhere a
    struct does, because ``Struct`` is a ``Mapping``.
    """
    lines = [
        _BANNER,
        '"""WebGPU structs, as dataclasses.',
        "",
        "Instantiating these gives readable, type-checkable code, but every API that",
        "accepts a struct also accepts a plain dict with the same fields.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from collections.abc import Mapping, Sequence",
        "from dataclasses import dataclass",
        "",
        "from wgpu._api.types import ArrayLike, CanvasLike",
        "from wgpu._generated import apiclasses as classes",
        "from wgpu._generated import apienums as enums",
        "from wgpu._generated import apiflags as flags",
        "from wgpu._api.struct import Struct",
        "",
        "",
    ]
    names = sorted(b.idl.structs)
    lines.append("__all__ = [")
    lines += [f"    {n!r}," for n in names]
    lines += [f"    {n!r}Struct," for n in names]
    lines.append("]")
    lines.append("")

    for name in names:
        fields = b.idl.structs[name]
        lines.append("")
        lines.append("@dataclass(kw_only=True, repr=False)")
        lines.append(f"class {name}(Struct):")
        if not fields:
            lines.append("    pass")
        for fname, attr in fields.items():
            py = bridge.camel_to_snake(fname)
            ann = b.idl.resolve_type(attr.typename)
            if attr.required:
                lines.append(f"    {_ident(py)}: {ann}")
            else:
                lines.append(
                    f"    {_ident(py)}: {ann} = "
                    f"{_default_repr(attr.default, attr.typename, b.idl)}"
                )
        lines.append("")
        lines.append("")
        lines.append(f"{name}Struct = {name} | dict")
        lines.append("")
    return "\n".join(lines)


# ---- classes ---------------------------------------------------------------

#: Methods whose Python signature genuinely differs from the C one, so the body
#: cannot be generated. The class body is emitted without them and
#: ``wgpu._api.overrides`` supplies the implementation. Each entry says why.
HAND_WRITTEN = {
    # Takes an extra ``data_offset`` and derives ``size`` from the buffer.
    ("GPUQueue", "writeBuffer"),
    # C needs an explicit byte count that the IDL derives from the data.
    ("GPUQueue", "writeTexture"),
}

#: Attributes with no plain C getter behind them: they either aggregate several
#: calls, return a Python-side object, or exist only in the Python API.
HAND_WRITTEN_ATTRS = {
    ("GPUAdapter", "features"),
    ("GPUAdapter", "limits"),
    ("GPUAdapter", "info"),
    ("GPUDevice", "features"),
    ("GPUDevice", "limits"),
    ("GPUDevice", "adapterInfo"),
    ("GPUDevice", "queue"),
    ("GPUDevice", "lost"),
    ("GPUDevice", "onuncapturederror"),
    ("GPUBuffer", "mapState"),
    ("GPUTexture", "textureBindingViewDimension"),
    ("GPUTextureView", "texture"),
    ("GPUCompilationInfo", "messages"),
}

#: Classes with no wgpu-native object behind them at all: they are pure Python
#: (the entrypoint, error types, info bags) or wrap a C object the Web IDL does
#: not model (``GPUCanvasContext`` drives a ``surface``). These are written by
#: hand in ``wgpu._api`` and re-exported, not generated.
PYTHON_SIDE_CLASSES = {
    "GPU",
    "GPUCanvasContext",
    "GPUAdapterInfo",
    "GPUCompilationInfo",
    "GPUCompilationMessage",
    "GPUDeviceLostInfo",
    "GPUError",
    "GPUValidationError",
    "GPUOutOfMemoryError",
    "GPUInternalError",
    "GPUPipelineError",
    "GPUObjectBase",
}

#: Mixins carry methods that several concrete objects share (``draw`` lives on
#: both the render pass and the render bundle encoder). Their signatures come
#: from the IDL; the C method name is looked up via one representative object,
#: and dispatch at runtime uses the *instance*'s spec object.
MIXIN_REPRESENTATIVE = {
    "GPUCommandsMixin": "GPUCommandEncoder",
    "GPUDebugCommandsMixin": "GPUCommandEncoder",
    "GPUBindingCommandsMixin": "GPUComputePassEncoder",
    "GPURenderCommandsMixin": "GPURenderPassEncoder",
    "GPUPipelineBase": "GPUComputePipeline",
}

#: The extra ``label`` keyword that wgpu-py has always accepted on every
#: descriptor-taking method, matching ``GPUObjectDescriptorBase``.
_LABEL_PARAM = 'label: str = ""'


def _method_doc(cls: str, name: str, kind: str) -> str:
    return f"{cls}.{name} ({kind})"


def generate_api_classes(b: bridge.Bridge, spec: dict) -> str:
    """Emit the public ``GPU*`` classes with real WebGPU signatures.

    Descriptor-taking methods are flattened into keyword arguments (the IDL says
    ``createBuffer(GPUBufferDescriptor)``; wgpu-py has always said
    ``create_buffer(*, label, size, usage, mapped_at_creation)``), and every
    ``Promise``-returning method yields the ``_sync``/``_async`` pair.

    Bodies are one call into the runtime, which is why this stays generated:
    the interesting behaviour lives in ``wgpu._api``, not in 150 wrappers.
    """
    objects = {o["name"]: o for o in spec["objects"]}
    lines = [
        _BANNER,
        '"""The public ``GPU*`` classes."""',
        "",
        "from __future__ import annotations",
        "",
        "from collections.abc import Sequence",
        "",
        "from wgpu._api import overrides as _ov",
        "from wgpu._api.base import GPUObjectBase, Mixin",
        "from wgpu._api.types import ArrayLike, CanvasLike",
        "from wgpu._generated import apienums as enums",
        "from wgpu._generated import apiflags as flags",
        "from wgpu._generated import apistructs as structs",
        "",
    ]
    names = sorted(b.idl.classes)
    lines.append("__all__ = [")
    lines += [f"    {n!r}," for n in names]
    lines.append("]")
    lines.append("")

    for cls_name in names:
        if cls_name in PYTHON_SIDE_CLASSES:
            continue
        interface = b.idl.classes[cls_name]
        proxy = MIXIN_REPRESENTATIVE.get(cls_name, cls_name)
        spec_object = b.classes.get(proxy)
        lines.extend(
            _emit_class(b, cls_name, interface, spec_object, objects, proxy)
        )
    return "\n".join(lines)


def _emit_class(b, cls_name, interface, spec_object, objects, proxy) -> list[str]:
    bases = [
        base
        for base in interface.bases
        if base in b.idl.classes and base != "EventTarget"
    ]
    if not bases:
        bases = ["Mixin"] if cls_name in MIXIN_REPRESENTATIVE else ["GPUObjectBase"]
    lines = ["", "", f"class {cls_name}({', '.join(bases)}):"]
    lines.append(f'    """{cls_name} -- see the WebGPU specification."""')
    # A mixin has no object of its own; dispatch uses the instance's.
    if spec_object and cls_name not in MIXIN_REPRESENTATIVE:
        lines.append(f"    _spec_name = {spec_object!r}")
    lines.append("")

    body: list[str] = []
    spec_methods = (
        {m["name"]: m for m in objects[spec_object].get("methods", [])}
        if spec_object
        else {}
    )
    for fn_name, line in interface.functions.items():
        if (cls_name, fn_name) in HAND_WRITTEN:
            body += _emit_override_hook(cls_name, fn_name)
            continue
        spec_method = b.methods.get((proxy, fn_name))
        if spec_method is None:
            continue  # web-only, or lives on a hand-written class
        body += _emit_method(b, cls_name, fn_name, line, spec_methods[spec_method])
    for attr_name in interface.attributes:
        if (cls_name, attr_name) in HAND_WRITTEN_ATTRS:
            body += _emit_attr_hook(cls_name, attr_name)
            continue
        body += _emit_attr(b, cls_name, attr_name, spec_methods)
    if not body:
        body = ["    pass", ""]
    return lines + body


def _emit_override_hook(cls_name, fn_name) -> list[str]:
    """Bind a hand-written implementation into the generated class."""
    py = bridge.camel_to_snake(fn_name)
    return [f"    {py} = _ov.{bridge.camel_to_snake(cls_name[3:])}_{py}", ""]


def _emit_attr_hook(cls_name, attr_name) -> list[str]:
    py = bridge.camel_to_snake(attr_name)
    return [f"    {py} = _ov.{bridge.camel_to_snake(cls_name[3:])}_{py}", ""]


def _emit_attr(b, cls_name, attr_name, spec_methods) -> list[str]:
    """Emit a read-only property backed by the object's C getter."""
    py = bridge.camel_to_snake(attr_name)
    getter = f"get_{py}"
    if getter not in spec_methods:
        raise RuntimeError(f"{cls_name}.{attr_name}: no C getter {getter!r}")
    line = b.idl.classes[cls_name].attributes[attr_name]
    typename = line.partition("attribute")[2].strip().rsplit(" ", 1)[0]
    ann = _annotate(b.idl, typename)
    return [
        "    @property",
        f"    def {_ident(py)}(self) -> {ann}:",
        f'        """{cls_name}.{attr_name}"""',
        f"        return self._get({getter!r})",
        "",
    ]


def _emit_method(b, cls_name, fn_name, line, spec_method) -> list[str]:
    py = bridge.camel_to_snake(fn_name)
    params = _params(line)
    is_async = line.strip().startswith("Promise<")
    if is_async and py.endswith("_async"):
        # ``mapAsync`` is the promise form of ``map``; we re-add the suffix
        # below so it does not become ``map_async_async``.
        py = py[: -len("_async")]
    ret = line.strip().split(" ", 1)[0]
    ann = _annotate(b.idl, ret)

    args = spec_method.get("args", [])
    flattened = (
        len(params) == 1
        and len(args) == 1
        and args[0]["type"].startswith("struct.")
        and params[0].typename.startswith("GPU")
        and params[0].typename.endswith(("Descriptor", "Options"))
    )
    if flattened:
        sig, mapping = _flatten_descriptor(b, params[0].typename)
        call = f"self._call_desc({spec_method['name']!r}, {mapping})"
        decl = f"def {_ident(py)}(self, *, {sig}) -> {ann}:" if sig else (
            f"def {_ident(py)}(self) -> {ann}:"
        )
    else:
        if len(params) != len(args):
            raise RuntimeError(
                f"{cls_name}.{fn_name}: {len(params)} IDL params vs "
                f"{len(args)} C args; add it to HAND_WRITTEN"
            )
        sig_parts, names = [], []
        for p in params:
            name = _ident(bridge.camel_to_snake(p.name))
            names.append(name)
            default = _default_repr(p.default, p.typename, b.idl)
            pann = _annotate(b.idl, p.typename, optional=not p.required and default == "None")
            if p.required:
                sig_parts.append(f"{name}: {pann}")
            else:
                sig_parts.append(f"{name}: {pann} = {default}")
        sig = ", ".join(sig_parts)
        passthrough = "".join(f", {n}" for n in names)
        call = f"self._call({spec_method['name']!r}{passthrough})"
        decl = f"def {_ident(py)}(self{', ' + sig if sig else ''}) -> {ann}:"

    doc = f'        """{cls_name}.{fn_name} -- see the WebGPU specification."""'
    if not is_async:
        return [f"    {decl}", doc, f"        return {call}", ""]

    # Promise-returning: wgpu-py exposes both a blocking and an awaitable form.
    out = []
    for suffix, wrap in (("_async", "self._promise"), ("_sync", "self._await")):
        adecl = decl.replace(f"def {_ident(py)}(", f"def {_ident(py)}{suffix}(", 1)
        out += [f"    {adecl}", doc, f"        return {wrap}({call})", ""]
    out += [
        f"    {_ident(py)} = _ov.deprecated_sync_or_async({py!r})",
        "",
    ]
    return out


def _flatten_descriptor(b, idl_struct_name: str) -> tuple[str, str]:
    """Turn a descriptor struct into keyword parameters + the mapping literal."""
    name = idl_struct_name[3:]  # strip GPU
    if name.endswith("Dict"):
        name = name[:-4]
    fields = b.idl.structs[name]
    ordered, items = [], []
    for fname, attr in fields.items():
        py = _ident(bridge.camel_to_snake(fname))
        default = _default_repr(attr.default, attr.typename, b.idl)
        ann = _annotate(b.idl, attr.typename, optional=not attr.required and default == "None")
        if attr.required:
            ordered.append(f"{py}: {ann}")
        else:
            ordered.append(f"{py}: {ann} = {default}")
        items.append(f"{py!r}: {py}")
    # Keyword-only, so a required parameter may follow a defaulted one; keeping
    # IDL declaration order means ``label`` stays first, as it always has been.
    sig_parts = ordered
    mapping = "{" + ", ".join(items) + "}"
    return ", ".join(sig_parts), mapping


def write_all(out_dir: Path = GENERATED_DIR) -> list[Path]:
    from .generate import _import_module

    b = bridge.build()
    mod = _import_module()
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for fname, text in [
        ("apienums.py", generate_api_enums(b, mod.lib)),
        ("apiflags.py", generate_api_flags(b)),
    ]:
        path = out_dir / fname
        path.write_text(text)
        written.append(path)
    return written


if __name__ == "__main__":
    for p in write_all():
        print("wrote", p.relative_to(paths.REPO_ROOT))
