"""Generate the *public* wgpu API from ``webgpu.idl`` + the bridge.

``bindgen.generate`` emits the low-level layer (C structs, C method tables,
integer enums) straight from ``webgpu.json``. This module emits what users
actually import: string enums, flag classes, struct dataclasses, and the
``GPU*`` classes with real WebGPU signatures.

The two halves meet in :mod:`bindgen.bridge`, which knows that the IDL's
``mappedAtCreation`` is the C spec's ``mapped_at_creation`` and that
``"rgba8unorm"`` is ``WGPUTextureFormat_RGBA8Unorm``. Because that mapping is
resolved *here*, at generation time, the runtime does no name translation: the
generated code already speaks C-side names and integers.
"""

from __future__ import annotations

import keyword
import re
from pathlib import Path

from . import bridge, paths

GENERATED_DIR = paths.REPO_ROOT / "wgpu" / "_generated"

_BANNER = """\
# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Public API surface, generated from bindgen/resources/webgpu.idl (the W3C
# WebGPU Web IDL) and cross-referenced against the wgpu-native C spec. Re-run
# the generator after updating either spec.
"""


def _ident(name: str) -> str:
    return name + "_" if keyword.iskeyword(name) else name


def _annotate(idl, typename: str, *, optional: bool = False) -> str:
    """Resolve an IDL type to a Python annotation.

    Sequences are annotated as ``Sequence`` rather than ``list`` because the API
    accepts any sequence, and anything that defaults to ``None`` is widened so
    the annotation does not lie about it.
    """
    ann = idl.resolve_type(typename)
    while "list[" in ann:
        ann = ann.replace("list[", "Sequence[", 1)
    if optional and "None" not in ann:
        ann += " | None"
    return ann


# ---- enums -----------------------------------------------------------------


def _web_name(spec_entry: str) -> str:
    """``2D_array`` -> ``2d-array``, ``discrete_GPU`` -> ``discrete-gpu``.

    The spelling the Web API uses, derived for enums the IDL does not define.
    """
    return spec_entry.lower().replace("_", "-")


def _native_features(lib) -> list[tuple[str, int]]:
    """wgpu-native's extra feature names, read from its own header."""
    header = paths.FFI_DIR / "wgpu.h"
    if not header.exists():
        return []
    out = []
    seen = set()
    for c_name in sorted(
        set(re.findall(r"WGPUNativeFeature_(\w+)", header.read_text()))
    ):
        if c_name == "Force32":
            continue  # a sizing sentinel, not a feature
        name = bridge.camel_to_snake(c_name).replace("_", "-")
        if name in seen:
            continue
        value = getattr(lib, f"WGPUNativeFeature_{c_name}", None)
        if value is None:
            # Named in the header but not compiled in (behind an #if, or only
            # mentioned in docs). Skipping keeps this self-correcting.
            continue
        seen.add(name)
        out.append((name, int(value)))
    return out


def generate_api_enums(b: bridge.Bridge, lib) -> str:
    """Emit the string-valued enums plus their string -> C-integer maps.

    Enum *values* are the WebGPU strings (``"rgba8unorm"``), because that is
    what the web API and existing wgpu-py code use -- ``TextureFormat.rgba8unorm
    == "rgba8unorm"`` holds. The integers the C API wants are resolved here and
    baked into ``TO_INT`` so no lookup logic ships in the runtime.
    """
    from . import naming

    lines = [
        _BANNER,
        '"""WebGPU enums. Values are strings, so ``wgpu.TextureFormat.rgba8unorm``',
        'and ``"rgba8unorm"`` are interchangeable."""',
        "",
        "from typing import Literal",
        "",
        "from wgpu._runtime.enumbase import EnumType as _EnumType",
        "from wgpu._runtime.maps import EnumMap as _EnumMap",
        "",
        "",
        "class Enum(metaclass=_EnumType):",
        '    """Base class for wgpu enums."""',
        "",
        "    def __init__(self):",
        '        raise RuntimeError("Cannot instantiate an enum.")',
        "",
    ]
    mapped = set(b.enum_types.values())
    c_only_enums = [e for e in b.spec["enums"] if e["name"] not in mapped]
    names = sorted(b.idl.enums)
    lines.append("")
    lines.append("__all__ = [")
    lines += [f"    {n!r}," for n in names]
    lines += [f"    '{n}Enum'," for n in names]
    lines.append("]")
    lines.append("")

    for idl_name in names:
        members = b.idl.enums[idl_name]
        lines.append("")
        lines.append(f"class {idl_name}(Enum):")
        for key, value in members.items():
            lines.append(f"    {_ident(key)} = {value!r}")
        lines.append("")

    # Type aliases used in annotations: a Literal of the valid strings, widened
    # with ``str`` so passing an unlisted value is a runtime error, not a type
    # error (new spec values appear before the vendored IDL catches up).
    lines.append("")
    for idl_name in names:
        values = list(b.idl.enums[idl_name].values())
        literal = ", ".join(repr(v) for v in values)
        lines.append(f"{idl_name}Enum = Literal[{literal}] | str")
    lines.append("")

    # spec-enum-name -> {public string | int -> C int}
    lines.append("")
    lines.append("#: C-spec enum name -> mapping of accepted value to C integer.")
    lines.append("TO_INT: dict[str, _EnumMap] = {}")
    lines.append("")
    for idl_name in names:
        spec_name = b.enum_types.get(idl_name)
        if spec_name is None:
            continue  # web-only enum, never crosses the FFI boundary
        pairs = []
        for value in b.idl.enums[idl_name].values():
            entry = b.enum_values[(idl_name, value)]
            c_int = int(getattr(lib, naming.c_enum_value(spec_name, entry)))
            pairs.append((value, c_int))
        lines.append(f"TO_INT[{spec_name!r}] = _EnumMap({idl_name!r}, {{")
        lines += [f"    {v!r}: {i}," for v, i in pairs]
        lines.append("})")
        lines.append("")

    # wgpu-native extends WGPUFeatureName with its own features. They are not
    # in either spec file -- only in wgpu.h -- but they share the enum's value
    # space and users do request them by name, so they are folded in here.
    native = _native_features(lib)
    if native:
        lines.append("")
        lines.append("# wgpu-native's own features, from wgpu.h. Not WebGPU, but")
        lines.append("# they extend the same enum and are requested the same way.")
        lines.append("TO_INT['feature_name'].update({")
        lines += [f"    {name!r}: {value}," for name, value in native]
        lines.append("})")
        lines.append("")

    # Enums the C API has but the Web IDL does not (backend type, adapter type,
    # native-only features). They never come *in* from user code, but they do
    # come back out of getters, and an integer there would be useless.
    lines.append("")
    lines.append("# C-only enums: no Web IDL counterpart, but their values are")
    lines.append("# reported by getters such as adapter.info.")
    for item in c_only_enums:
        spec_name = item["name"]
        pairs = []
        for entry in item["entries"]:
            if entry is None:
                continue
            c_int = int(getattr(lib, naming.c_enum_value(spec_name, entry["name"])))
            pairs.append((_web_name(entry["name"]), c_int))
        seen = set()
        lines.append(f"TO_INT[{spec_name!r}] = _EnumMap({spec_name!r}, {{")
        for v, i in pairs:
            if v not in seen:
                seen.add(v)
                lines.append(f"    {v!r}: {i},")
        lines.append("})")
        lines.append("")

    # The other direction, for values coming *back* out of C. Built from the
    # same pairs, so the two can never disagree.
    lines.append("")
    lines.append("#: C-spec enum name -> mapping of C integer back to its string.")
    lines.append("FROM_INT: dict[str, dict[int, str]] = {")
    lines.append("    name: {i: v for v, i in table.items() if isinstance(v, str)}")
    lines.append("    for name, table in TO_INT.items()")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ---- flags -----------------------------------------------------------------


def generate_api_flags(b: bridge.Bridge) -> str:
    """Emit the integer flag classes plus their name -> integer maps.

    Flag values come from the IDL rather than the C header: they are part of the
    WebGPU spec, and the bridge asserts the two agree.
    """
    lines = [
        _BANNER,
        '"""WebGPU flags: integer bitmasks. ``BufferUsage.MAP_READ | BufferUsage.COPY_DST``',
        'can also be written as ``"MAP_READ|COPY_DST"``."""',
        "",
        "from wgpu._runtime.enumbase import EnumType as _EnumType",
        "from wgpu._runtime.maps import FlagMap as _FlagMap",
        "",
        "",
        "class Flags(metaclass=_EnumType):",
        '    """Base class for wgpu flags."""',
        "",
        "    def __init__(self):",
        '        raise RuntimeError("Cannot instantiate a flags class.")',
        "",
    ]
    names = sorted(b.idl.flags)
    lines.append("")
    lines.append("__all__ = [")
    lines += [f"    {n!r}," for n in names]
    lines += [f"    '{n}Flags'," for n in names]
    lines.append("]")
    lines.append("")

    for idl_name in names:
        lines.append("")
        lines.append(f"class {idl_name}(Flags):")
        for key, value in b.idl.flags[idl_name].items():
            lines.append(f"    {_ident(key)} = {value}")
        lines.append("")

    # Flags accept an int or an ``"A|B"`` string, in annotations as at runtime.
    lines.append("")
    for idl_name in names:
        lines.append(f"{idl_name}Flags = int | str")
    lines.append("")
    lines.append(
        "#: C-spec bitflag name -> mapping that accepts ints and 'A|B' strings."
    )
    lines.append("TO_INT: dict[str, _FlagMap] = {}")
    lines.append("")
    for idl_name in names:
        spec_name = b.flag_types[idl_name]
        lines.append(f"TO_INT[{spec_name!r}] = _FlagMap({idl_name!r}, {{")
        lines += [f"    {k!r}: {v}," for k, v in b.idl.flags[idl_name].items()]
        lines.append("})")
        lines.append("")
    return "\n".join(lines)


# ---- structs ---------------------------------------------------------------


def _params(line: str) -> list:
    """Split an IDL function signature's parameter list into Attributes."""
    from .idl import Attribute

    inner = line[line.index("(") + 1 : line.rindex(")")].strip()
    if not inner:
        return []
    parts, depth, cur = [], 0, ""
    for ch in inner:
        if ch in "<([":
            depth += 1
        elif ch in ">)]":
            depth -= 1
        if ch == "," and depth == 0:
            parts.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        parts.append(cur)
    return [Attribute(p, "param") for p in parts]


def _default_repr(default: str | None, typename: str, idl) -> str:
    """Render an IDL default as a Python literal."""
    if default is None:
        return "None"
    d = default.strip()
    if d in ("True", "False", "None"):
        return d
    if d == '""':
        return '""'
    if d == "{}":
        return "None"  # an empty descriptor: the runtime fills in defaults
    if d == "[]":
        return "()"
    if re.fullmatch(r"-?\d+", d):
        return d
    if re.fullmatch(r"-?\d*\.\d+", d):
        return d
    if d.startswith('"'):
        return d
    # An enum constant such as GPUTextureAspect."all" arrives quoted already;
    # anything else is a name we pass through untouched.
    return repr(d.strip('"'))


def generate_api_structs(b: bridge.Bridge) -> str:
    """Emit the public struct dataclasses.

    These are for typing, autocompletion and docs; plain dicts work everywhere a
    struct does, because ``Struct`` is a ``Mapping``.
    """
    lines = [
        _BANNER,
        '"""WebGPU structs, as dataclasses.',
        "",
        "Instantiating these gives readable, type-checkable code, but every API that",
        "accepts a struct also accepts a plain dict with the same fields.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from collections.abc import Mapping, Sequence",
        "from dataclasses import dataclass",
        "",
        "from wgpu._api.types import ArrayLike, CanvasLike",
        "from wgpu._generated import apiclasses as classes",
        "from wgpu._generated import apienums as enums",
        "from wgpu._generated import apiflags as flags",
        "from wgpu._api.struct import Struct",
        "",
        "",
    ]
    names = sorted(b.idl.structs)
    lines.append("__all__ = [")
    lines += [f"    {n!r}," for n in names]
    lines += [f"    '{n}Struct'," for n in names]
    lines.append("]")
    lines.append("")

    for name in names:
        fields = b.idl.structs[name]
        lines.append("")
        lines.append("@dataclass(kw_only=True, repr=False)")
        lines.append(f"class {name}(Struct):")
        if not fields:
            lines.append("    pass")
        for fname, attr in fields.items():
            py = bridge.camel_to_snake(fname)
            ann = b.idl.resolve_type(attr.typename)
            if attr.required:
                lines.append(f"    {_ident(py)}: {ann}")
            else:
                lines.append(
                    f"    {_ident(py)}: {ann} = "
                    f"{_default_repr(attr.default, attr.typename, b.idl)}"
                )
        lines.append("")
        lines.append("")
        lines.append(f"{name}Struct = {name} | dict")
        lines.append("")
    return "\n".join(lines)


# ---- classes ---------------------------------------------------------------

#: Methods whose Python signature genuinely differs from the C one, so the body
#: cannot be generated. The class body is emitted without them and
#: ``wgpu._api.overrides`` supplies the implementation. Each entry says why.
HAND_WRITTEN = {
    # The IDL overloads this with a dynamic-offsets slice; C takes the array.
    ("GPUBindingCommandsMixin", "setBindGroup"),
    # The spec defines an omitted size as "the rest of the buffer", which is a
    # value only the Python side knows -- wgpu-native rejects the C sentinel.
    ("GPUBuffer", "mapAsync"),
    ("GPUBuffer", "getMappedRange"),
    ("GPUBuffer", "unmap"),
    # wgpu-native does not implement the C function, but wgpu-py has always
    # answered this rather than failing; see the override.
    ("GPUShaderModule", "getCompilationInfo"),
}

#: Attributes with no plain C getter behind them: they either aggregate several
#: calls, return a Python-side object, or exist only in the Python API.
HAND_WRITTEN_ATTRS = {
    ("GPUAdapter", "features"),
    ("GPUAdapter", "limits"),
    ("GPUAdapter", "info"),
    ("GPUDevice", "features"),
    ("GPUDevice", "limits"),
    ("GPUDevice", "adapterInfo"),
    ("GPUDevice", "queue"),
    ("GPUDevice", "lost"),
    ("GPUDevice", "onuncapturederror"),
    ("GPUBuffer", "mapState"),
    ("GPUTexture", "textureBindingViewDimension"),
    ("GPUTextureView", "texture"),
    ("GPUCompilationInfo", "messages"),
}

#: Classes with no wgpu-native object behind them at all: they are pure Python
#: (the entrypoint, error types, info bags) or wrap a C object the Web IDL does
#: not model (``GPUCanvasContext`` drives a ``surface``). These are written by
#: hand in ``wgpu._api`` and re-exported, not generated.
PYTHON_SIDE_CLASSES = {
    "GPU",
    "GPUCanvasContext",
    "GPUAdapterInfo",
    "GPUCompilationInfo",
    "GPUCompilationMessage",
    "GPUDeviceLostInfo",
    "GPUError",
    "GPUValidationError",
    "GPUOutOfMemoryError",
    "GPUInternalError",
    "GPUPipelineError",
    "GPUObjectBase",
}

#: Mixins carry methods that several concrete objects share (``draw`` lives on
#: both the render pass and the render bundle encoder). Their signatures come
#: from the IDL; the C method name is looked up via one representative object,
#: and dispatch at runtime uses the *instance*'s spec object.
MIXIN_REPRESENTATIVE = {
    "GPUCommandsMixin": "GPUCommandEncoder",
    "GPUDebugCommandsMixin": "GPUCommandEncoder",
    "GPUBindingCommandsMixin": "GPUComputePassEncoder",
    "GPURenderCommandsMixin": "GPURenderPassEncoder",
    "GPUPipelineBase": "GPUComputePipeline",
}

#: Attributes fixed for an object's lifetime, because they come from the
#: descriptor it was created with. These are read constantly in render loops, so
#: they are fetched once and cached rather than crossing the FFI boundary each
#: time. Everything not listed here is read live -- notably a buffer's map
#: state, which changes.
IMMUTABLE_ATTRS = {
    ("GPUBuffer", "size"),
    ("GPUBuffer", "usage"),
    ("GPUTexture", "width"),
    ("GPUTexture", "height"),
    ("GPUTexture", "depthOrArrayLayers"),
    ("GPUTexture", "mipLevelCount"),
    ("GPUTexture", "sampleCount"),
    ("GPUTexture", "dimension"),
    ("GPUTexture", "format"),
    ("GPUTexture", "usage"),
    ("GPUQuerySet", "type"),
    ("GPUQuerySet", "count"),
}

#: The extra ``label`` keyword that wgpu-py has always accepted on every
#: descriptor-taking method, matching ``GPUObjectDescriptorBase``.
_LABEL_PARAM = 'label: str = ""'

# ---- direct calls ----------------------------------------------------------
#
# Command recording is the hot path: a frame issues thousands of draws and
# state changes, and profiling showed almost all of that time going into
# marshalling layers rather than the C call. For the methods whose arguments
# need no allocation, the generator emits a body that calls the bound C
# function straight away -- no descriptor lookup, no argument loop, no
# per-call conversion that cffi would do anyway.
#
# The cost of that directness is that these calls do not check for a pending
# wgpu-native error. Errors still surface, at the next call that does check --
# in practice ``finish()`` or ``submit()``, since both take a descriptor or an
# array and so use the general path. That is the same place the classic
# implementation reported them.

#: Argument kinds a direct call can pass through without allocating.
DIRECT_ARG_KINDS = frozenset({"prim", "enum", "bitflag", "object"})

#: Return kinds a direct call can produce with at most one inline conversion.
DIRECT_RET_KINDS = frozenset({None, "prim", "object", "enum", "bitflag"})


def _method_doc(cls: str, name: str, kind: str) -> str:
    return f"{cls}.{name} ({kind})"


def generate_api_classes(b: bridge.Bridge, spec: dict, native=None) -> str:
    """Emit the public ``GPU*`` classes with real WebGPU signatures.

    Descriptor-taking methods are flattened into keyword arguments (the IDL says
    ``createBuffer(GPUBufferDescriptor)``; wgpu-py has always said
    ``create_buffer(*, label, size, usage, mapped_at_creation)``), and every
    ``Promise``-returning method yields the ``_sync``/``_async`` pair.

    Bodies are one call into the runtime, which is why this stays generated:
    the interesting behaviour lives in ``wgpu._api``, not in 150 wrappers.
    """
    objects = {o["name"]: o for o in spec["objects"]}
    binds: set = set()
    names = [n for n in sorted(b.idl.classes) if n not in PYTHON_SIDE_CLASSES]

    body: list[str] = []
    for cls_name in _in_dependency_order(b, names):
        if cls_name in PYTHON_SIDE_CLASSES:
            continue
        interface = b.idl.classes[cls_name]
        proxy = MIXIN_REPRESENTATIVE.get(cls_name, cls_name)
        spec_object = b.classes.get(proxy)
        body.extend(
            _emit_class(
                b, cls_name, interface, spec_object, objects, proxy, binds, native
            )
        )

    lines = [
        _BANNER,
        '"""The public ``GPU*`` classes."""',
        "",
        "from __future__ import annotations",
        "",
        "from collections.abc import Sequence",
        "",
        "from wgpu._api import overrides as _ov",
        "from wgpu._api.base import unimplemented as _unimplemented",
        "from wgpu._api.base import GPUObjectBase, Mixin, new_object as _new_object",
        "from wgpu._api.base import slice_data as _slice_data",
        "from wgpu._api.types import ArrayLike, CanvasLike",
        "from wgpu._generated import apienums as enums",
        "from wgpu._generated import apiflags as flags",
        "from wgpu._generated import apistructs as structs",
        "",
    ]
    lines += _emit_bindings(binds)
    lines.append("__all__ = [")
    lines += [f"    {n!r}," for n in names]
    lines.append("]")
    lines.append("")
    lines.extend(body)
    return "\n".join(lines)


def _emit_bindings(binds: set) -> list[str]:
    """Bind, once at import, everything the direct call bodies reference.

    Resolving these here is the whole point: a hot method body becomes a single
    call to an already-bound C function, with no lookups left to do.
    """
    if not binds:
        return []
    lines = [
        "# Bound once at import so the hot methods below are a single C call.",
        "from wgpu._native import ffi as _ffi, lib as _lib",
        "",
    ]
    kinds = {kind for kind, _ in binds}
    if "null" in kinds or "handle" in kinds:
        lines.append("_NULL = _ffi.NULL")
    if "errors" in kinds:
        lines.append("from wgpu._api.base import raise_if_error as _raise_if_error")
    if "handle" in kinds:
        lines.append("")
        lines.append("def _handle(obj):")
        lines.append(
            '    """A public object as its C handle; "auto" and None are NULL."""'
        )
        lines.append(
            '    return _NULL if obj is None or obj == "auto" else obj._handle'
        )
        lines.append("")
    for width in sorted(w for k, w in binds if k == "whole"):
        # WGPU_WHOLE_SIZE / WGPU_WHOLE_MAP_SIZE, per parameter width.
        lines.append(f"_WHOLE{width} = {(1 << width) - 1}")
    if "enum_out" in kinds:
        lines.append("")
        lines.append("def _enum_out(table, value):")
        lines.append('    """A C enum value as its public string."""')
        lines.append("    return table.get(value, value)")
        lines.append("")
    for ref in sorted(r for k, r in binds if k == "enum"):
        lines.append(f"_E_{ref} = enums.TO_INT[{ref!r}]")
    for ref in sorted(r for k, r in binds if k == "bitflag"):
        lines.append(f"_F_{ref} = flags.TO_INT[{ref!r}]")
    for ref in sorted(r for k, r in binds if k == "enum_out"):
        lines.append(f"_R_{ref} = enums.FROM_INT[{ref!r}]")
    for func in sorted(f for k, f in binds if k == "func"):
        lines.append(f"_c_{func} = _lib.{func}")
    lines.append("")
    lines.append("")
    return lines


def _in_dependency_order(b, names):
    """Order classes so every base is defined before the classes that use it."""
    ordered, seen = [], set()

    def visit(name):
        if name in seen:
            return
        seen.add(name)
        for base in b.idl.classes[name].bases:
            if base in b.idl.classes:
                visit(base)
        ordered.append(name)

    for name in names:
        visit(name)
    return ordered


def _emit_class(
    b, cls_name, interface, spec_object, objects, proxy, binds=None, native=None
) -> list[str]:
    bases = [
        base
        for base in interface.bases
        if base in b.idl.classes and base != "EventTarget"
    ]
    # Mixins come first so their methods win resolution, with the object base
    # last -- the order wgpu-py has always used.
    bases.sort(key=lambda n: n == "GPUObjectBase")
    if not bases:
        bases = ["Mixin"] if cls_name in MIXIN_REPRESENTATIVE else ["GPUObjectBase"]
    lines = ["", "", f"class {cls_name}({', '.join(bases)}):"]
    lines.append(f'    """{cls_name} -- see the WebGPU specification."""')
    # A mixin has no object of its own; dispatch uses the instance's.
    if spec_object and cls_name not in MIXIN_REPRESENTATIVE:
        lines.append(f"    _spec_name = {spec_object!r}")
    lines.append("")

    body: list[str] = []
    spec_methods = (
        {m["name"]: m for m in objects[spec_object].get("methods", [])}
        if spec_object
        else {}
    )
    for fn_name, line in interface.functions.items():
        if (cls_name, fn_name) in HAND_WRITTEN:
            body += _emit_override_hook(cls_name, fn_name, line)
            continue
        spec_method = b.methods.get((proxy, fn_name)) or bridge.camel_to_snake(fn_name)
        if spec_method not in spec_methods:
            continue  # web-only, or lives on a hand-written class
        body += _emit_method(
            b,
            cls_name,
            fn_name,
            line,
            spec_methods[spec_method],
            interface,
            spec_object=(None if cls_name in MIXIN_REPRESENTATIVE else spec_object),
            binds=binds,
            native=native,
        )
    # Methods a mixin contributes are declared once but implemented by a
    # *different* C function per concrete object (draw is
    # wgpuRenderPassEncoderDraw here, wgpuRenderBundleEncoderDraw there). The
    # mixin therefore keeps the general-path body, and each concrete class gets
    # a direct override bound to its own C function -- which matters, because
    # these are the methods a frame calls thousands of times.
    if spec_object and cls_name not in MIXIN_REPRESENTATIVE and native is not None:
        body += _emit_mixin_overrides(
            b, cls_name, interface, spec_object, spec_methods, binds, native
        )

    for attr_name in interface.attributes:
        if (cls_name, attr_name) in HAND_WRITTEN_ATTRS:
            body += _emit_attr_hook(cls_name, attr_name)
            continue
        body += _emit_attr(b, cls_name, attr_name, spec_methods)
    if not body:
        body = ["    pass", ""]
    return lines + body


def _emit_c_binding(
    b, cls_name, fn_name, spec_methods, spec_object, binds
) -> list[str]:
    """Expose a hand-written method's C function as a class attribute.

    ``set_bind_group`` cannot be generated -- the web API slices a dynamic
    offsets buffer that C takes as an array -- but its overwhelmingly common
    case passes no offsets at all, and that case is one C call. Binding the
    function per class lets the hand-written implementation take it.
    """
    from . import naming

    spec_method = bridge.camel_to_snake(fn_name)
    if spec_method not in spec_methods:
        return []
    c_func = naming.c_method_func(spec_object, spec_method)
    binds.add(("func", c_func))
    return [f"    _c_{spec_method} = staticmethod(_c_{c_func})", ""]


def _emit_mixin_overrides(
    b, cls_name, interface, spec_object, spec_methods, binds, native
) -> list[str]:
    """Emit direct-call overrides for the methods this class gets from mixins."""
    out: list[str] = []
    seen = set(interface.functions)
    for base in interface.bases:
        if base not in MIXIN_REPRESENTATIVE:
            continue
        for fn_name, line in b.idl.classes[base].functions.items():
            if fn_name in seen:
                continue
            if (base, fn_name) in HAND_WRITTEN:
                # The implementation is hand-written, but it still needs *this*
                # class's C function to take a fast path of its own.
                out += _emit_c_binding(
                    b, cls_name, fn_name, spec_methods, spec_object, binds
                )
                seen.add(fn_name)
                continue
            seen.add(fn_name)
            spec_method = bridge.camel_to_snake(fn_name)
            if spec_method not in spec_methods:
                continue
            emitted = _emit_method(
                b,
                cls_name,
                fn_name,
                line,
                spec_methods[spec_method],
                interface,
                spec_object=spec_object,
                binds=binds,
                native=native,
            )
            # Only worth overriding if it actually compiled to a direct call;
            # otherwise the inherited implementation is identical.
            if any("_c_wgpu" in ln for ln in emitted):
                out += emitted
    return out


def _override_prefix(cls_name: str) -> str:
    """``GPUBindingCommandsMixin`` -> ``binding_commands``, ``GPUQueue`` -> ``queue``."""
    name = cls_name[3:]
    if name.endswith("Mixin"):
        name = name[: -len("Mixin")]
    return bridge.camel_to_snake(name)


def _emit_override_hook(cls_name, fn_name, line="") -> list[str]:
    """Bind a hand-written implementation into the generated class.

    A promise-returning method needs its whole family bound, not just one name.
    """
    py = bridge.camel_to_snake(fn_name)
    prefix = _override_prefix(cls_name)
    if line.strip().startswith("Promise<"):
        # A promise-returning method needs its whole family bound, whether or
        # not the IDL name already carries the Async suffix.
        base = py[: -len("_async")] if py.endswith("_async") else py
        return [
            f"    {base}_async = _ov.{prefix}_{base}_async",
            f"    {base}_sync = _ov.{prefix}_{base}_sync",
            f"    {base} = _ov.{prefix}_{base}",
            "",
        ]
    return [f"    {py} = _ov.{prefix}_{py}", ""]


def _emit_attr_hook(cls_name, attr_name) -> list[str]:
    py = bridge.camel_to_snake(attr_name)
    return [f"    {py} = _ov.{_override_prefix(cls_name)}_{py}", ""]


def _emit_attr(b, cls_name, attr_name, spec_methods) -> list[str]:
    """Emit a read-only property backed by the object's C getter."""
    py = bridge.camel_to_snake(attr_name)
    getter = f"get_{py}"
    if getter not in spec_methods:
        raise RuntimeError(f"{cls_name}.{attr_name}: no C getter {getter!r}")
    line = b.idl.classes[cls_name].attributes[attr_name]
    typename = line.partition("attribute")[2].strip().rsplit(" ", 1)[0]
    ann = _annotate(b.idl, typename)
    fetch = "_get_cached" if (cls_name, attr_name) in IMMUTABLE_ATTRS else "_get"
    return [
        "    @property",
        f"    def {_ident(py)}(self) -> {ann}:",
        f'        """{cls_name}.{attr_name}"""',
        f"        return self.{fetch}({getter!r})",
        "",
    ]


#: IDL parameters that describe a *window* into the data rather than a value
#: C receives. They never map to a C argument; they slice the buffer first.
_WINDOW_OFFSET_PARAMS = frozenset({"dataOffset"})


def _data_slice_body(b, spec_method, params, py) -> tuple[str, str] | None:
    """Emit a body for methods that hand raw bytes to C, or None.

    The web API passes a buffer plus an optional ``(dataOffset, size)`` window;
    C wants a pointer and an explicit byte count. Three methods share that
    shape -- ``writeBuffer``, ``writeTexture``, ``setImmediates`` -- so it is
    derived rather than written three times.

    C arguments are matched to IDL parameters positionally, skipping the two
    the C API synthesises (the pointer and its byte count). Whatever IDL
    parameter is left over is the window's size.
    """
    from . import generate

    args = spec_method.get("args", [])
    kinds = [generate._parse_member_type(a["type"])[0] for a in args]
    if "c_void" not in kinds:
        return None
    data_at = kinds.index("c_void")
    count_at = data_at + 1
    if count_at >= len(kinds) or kinds[count_at] != "prim":
        return None  # raw data with no byte count: not this shape

    offset_param = next((p for p in params if p.name in _WINDOW_OFFSET_PARAMS), None)
    rest = [p for p in params if p is not offset_param]

    exprs, index = [], 0
    for position in range(len(args)):
        if position == data_at:
            exprs.append("_chunk")
            index += 1  # the IDL's ``data`` parameter
        elif position == count_at:
            exprs.append("_chunk.nbytes")  # synthesised, consumes no parameter
        else:
            if index >= len(rest):
                return None
            exprs.append(_ident(bridge.camel_to_snake(rest[index].name)))
            index += 1
    size_param = rest[index] if index < len(rest) else None

    data_name = "data"
    offset = _ident(bridge.camel_to_snake(offset_param.name)) if offset_param else "0"
    size = _ident(bridge.camel_to_snake(size_param.name)) if size_param else "None"
    prologue = f"_chunk = _slice_data({data_name}, {offset}, {size})"
    call = f"self._call({spec_method['name']!r}, {', '.join(exprs)})"
    return prologue, call


def _direct_body(b, spec_object, spec_method, params, binds, native) -> str | None:
    """Return a direct C-call expression for this method, or None.

    ``binds`` collects the module-level names the emitted body needs, so the
    preamble can bind them once at import.
    """
    from . import generate, naming

    if spec_object is None or native is None:
        return None
    ffi = native.ffi
    args = spec_method.get("args", [])
    if len(params) != len(args):
        return None
    parsed = [generate._parse_member_type(a["type"]) for a in args]
    if any(is_array or kind not in DIRECT_ARG_KINDS for kind, _ref, is_array in parsed):
        return None

    ret = spec_method.get("returns")
    ret_kind, ret_ref = (None, None)
    if ret:
        ret_kind, ret_ref, ret_array = generate._parse_member_type(ret["type"])
        if ret_array or ret_kind not in DIRECT_RET_KINDS:
            return None
        if ret_kind == "object" and ret_ref not in b.classes.values():
            return None  # returns an object with no public class

    c_func = naming.c_method_func(spec_object, spec_method["name"])
    c_sig = ffi.typeof(getattr(native.lib, c_func)).args
    binds.add(("func", c_func))

    exprs = []
    for i, ((kind, ref, _), param, arg) in enumerate(zip(parsed, params, args)):
        name = _ident(bridge.camel_to_snake(param.name))
        omittable = not param.required and (param.default or "").strip() in (
            None,
            "",
            "None",
        )
        if kind == "prim":
            if omittable:
                # An omitted size means "the rest of the resource"; C spells
                # that as an all-ones sentinel of the parameter's own width.
                width = ffi.sizeof(c_sig[i + 1]) * 8
                binds.add(("whole", width))
                # A falsy size means "the rest of the resource" -- wgpu-py has
                # always accepted 0 as well as None for this.
                exprs.append(f"(_WHOLE{width} if not {name} else {name})")
            else:
                exprs.append(name)  # cffi coerces ints and floats itself
        elif kind in ("enum", "bitflag"):
            prefix = "_E_" if kind == "enum" else "_F_"
            binds.add((kind, ref))
            exprs.append(f"{prefix}{ref}[{name}]")
        elif kind == "object":
            if arg.get("optional") or omittable:
                binds.add(("null", None))
                exprs.append(f"({name}._handle if {name} is not None else _NULL)")
            else:
                exprs.append(f"{name}._handle")
        else:  # pragma: no cover - guarded above
            return None

    call = f"_c_{c_func}(self._handle{''.join(', ' + e for e in exprs)})"
    return _return_expr(b, call, ret_kind, ret_ref, binds)


def _return_expr(b, call: str, ret_kind, ret_ref, binds, label: str = "") -> str:
    """Wrap a raw C call so it yields the public form of its return value."""
    if ret_kind is None or (ret_kind == "prim" and ret_ref != "bool"):
        return call
    if ret_kind == "prim":  # bool
        return f"bool({call})"
    if ret_kind == "bitflag":
        return call
    if ret_kind == "enum":
        binds.add(("enum_out", ret_ref))
        return f"_enum_out(_R_{ret_ref}, {call})"
    # object return: it inherits this object's event pump and keeps it alive
    cls = next(k for k, v in b.classes.items() if v == ret_ref)
    binds.add(("new_object", None))
    suffix = f", {label}" if label else ""
    return f"_new_object({cls}, {call}, self{suffix})"


#: Member kinds a compiled descriptor body can fill with one statement each.
#: Arrays, nested structs, callbacks and chained extensions need the
#: interpreted builder, which those methods keep using.
COMPILABLE_MEMBER_KINDS = frozenset({"prim", "enum", "bitflag", "string", "object"})


def _compiled_descriptor_body(b, spec_object, spec_method, idl_struct, binds, native):
    """Build this method's descriptor inline, or return None.

    The interpreted builder walks a struct descriptor on every call: look up
    the member, dispatch on its kind, normalise the key, apply the default.
    None of that depends on the *values*, so for a struct whose members are all
    settable in one statement, the generator does that walk once, here, and
    emits straight-line code.

    Returns ``(lines, call)``, where the lines build ``_d`` and the call is the
    C call to make with it. The keep-alive problem solves itself: the encoded
    strings are locals, so they outlive the call that reads them.
    """
    from wgpu._generated.structs import STRUCTS

    from . import generate, naming

    if spec_object is None or native is None:
        return None
    args = spec_method.get("args", [])
    if len(args) != 1 or not args[0]["type"].startswith("struct."):
        return None
    desc = STRUCTS.get(args[0]["type"].split(".", 1)[1])
    if desc is None or desc.adapters or desc.s_type:
        return None  # a shape adapter or a chained struct: keep interpreting
    if any(
        m.array
        or m.kind not in COMPILABLE_MEMBER_KINDS
        or (m.kind == "prim" and m.pointer)
        for m in desc.members
    ):
        return None

    ret = spec_method.get("returns")
    ret_kind, ret_ref = (None, None)
    if ret:
        ret_kind, ret_ref, ret_array = generate._parse_member_type(ret["type"])
        if ret_array or ret_kind not in DIRECT_RET_KINDS:
            return None
        if ret_kind == "object" and ret_ref not in b.classes.values():
            return None

    # The public keyword names, as the flattened signature spells them.
    idl_name = idl_struct[3:]
    if idl_name.endswith("Dict"):
        idl_name = idl_name[:-4]
    params = {_ident(bridge.camel_to_snake(f)) for f in b.idl.structs.get(idl_name, {})}

    lines = [f'_d = _ffi.new("{desc.c_name} *")']
    for mem in desc.members:
        given = mem.py in params
        if not given:
            # No public keyword sets this member; only a constant default can.
            literal = _default_literal(mem.default)
            if literal is not None:
                lines.append(f"_d.{mem.c} = {literal}")
            continue
        name = mem.py
        # An explicit None means "unspecified", exactly as omitting the field
        # does for the interpreted builder -- so it falls back the same way.
        fallback = _default_literal(mem.default)
        if mem.kind == "string":
            # Falsy label -> leave the zeroed StringView, which is the empty
            # string. cffi's char[] is NUL-terminated, hence the -1.
            lines += [
                f"if {name}:",
                f'    _s_{name} = _ffi.new("char[]", {name}.encode())',
                f"    _d.{mem.c}.data = _s_{name}",
                f"    _d.{mem.c}.length = len(_s_{name}) - 1",
            ]
            continue
        if mem.kind == "enum":
            binds.add(("enum", mem.ref))
            value = f"_E_{mem.ref}[{name}]"
        elif mem.kind == "bitflag":
            binds.add(("bitflag", mem.ref))
            value = f"_F_{mem.ref}[{name}]"
        elif mem.kind == "object":
            binds.add(("handle", None))
            value = f"_handle({name})"
        else:  # prim
            value = name
        lines.append(f"if {name} is not None:")
        lines.append(f"    _d.{mem.c} = {value}")
        if fallback is not None:
            lines.append("else:")
            lines.append(f"    _d.{mem.c} = {fallback}")

    c_func = naming.c_method_func(spec_object, spec_method["name"])
    binds.add(("func", c_func))
    binds.add(("errors", None))
    # The label never comes back from C, so a created object carries the one it
    # was asked for -- exactly what the interpreted path records.
    label = (
        "label"
        if any(m.py == "label" for m in desc.members) and "label" in params
        else ""
    )
    call = _return_expr(
        b, f"_c_{c_func}(self._handle, _d)", ret_kind, ret_ref, binds, label
    )
    # Unlike the per-draw setters, these still report errors where they always
    # have: finish() is a checkpoint the rest of the API relies on.
    lines.append(f"_r = {call}")
    lines.append("_raise_if_error()")
    return lines, "_r"


def _default_literal(default):
    """A struct default as a Python literal, or None if there is nothing to emit.

    Zero is nothing to emit: ``ffi.new`` hands back zeroed memory, so assigning
    a falsy default would only restate what is already there.
    """
    if isinstance(default, bool):
        return "1" if default else None
    if isinstance(default, (int, float)):
        return repr(default) if default else None
    return None


def _unimplemented_body(spec_object, spec_method) -> str | None:
    """A guard for C functions wgpu-native declares but does not implement.

    Calling one aborts the process outright -- a Rust ``unimplemented!()``
    cannot unwind across FFI -- so these must never reach C. The list comes
    from wgpu-native's own source, so a submodule bump that implements one
    silently turns the guard back into a real call.
    """
    from . import naming

    if spec_object is None:
        return None
    c_func = naming.c_method_func(spec_object, spec_method["name"])
    if c_func not in paths.unimplemented_functions():
        return None
    return f"_unimplemented({c_func!r})"


def _emit_method(
    b,
    cls_name,
    fn_name,
    line,
    spec_method,
    interface,
    spec_object=None,
    binds=None,
    native=None,
) -> list[str]:
    py = bridge.camel_to_snake(fn_name)
    params = _params(line)
    is_async = line.strip().startswith("Promise<")
    if is_async and py.endswith("_async"):
        # ``mapAsync`` is the promise form of ``map``; we re-add the suffix
        # below so it does not become ``map_async_async``.
        py = py[: -len("_async")]
    # Strip any IDL extended attribute (``[NewObject] GPURenderBundle finish()``)
    # before reading the return type.
    decl = re.sub(r"^\s*\[[^\]]*\]\s*", "", line.strip())
    ret = decl.split(" ", 1)[0]
    ann = _annotate(b.idl, ret)

    prologue = None
    args = spec_method.get("args", [])
    flattened = (
        len(params) == 1
        and len(args) == 1
        and args[0]["type"].startswith("struct.")
        and params[0].typename.startswith("GPU")
        and params[0].typename.endswith(("Descriptor", "Options"))
    )
    if flattened:
        sig, mapping = _flatten_descriptor(b, params[0].typename)
        call = _unimplemented_body(spec_object, spec_method)
        if call is None and not is_async and binds is not None:
            compiled = _compiled_descriptor_body(
                b, spec_object, spec_method, params[0].typename, binds, native
            )
            if compiled is not None:
                prologue, call = compiled
        if call is None:
            call = f"self._call_desc({spec_method['name']!r}, {mapping})"
        decl = (
            f"def {_ident(py)}(self, *, {sig}) -> {ann}:"
            if sig
            else (f"def {_ident(py)}(self) -> {ann}:")
        )
    else:
        call = _unimplemented_body(spec_object, spec_method)
        if call is None:
            # Methods that hand raw bytes to C carry extra IDL parameters (the
            # slice window), so this is tried before the arity check.
            sliced = _data_slice_body(b, spec_method, params, py)
            if sliced is not None:
                prologue, call = sliced
        if call is None and len(params) != len(args):
            raise RuntimeError(
                f"{cls_name}.{fn_name}: {len(params)} IDL params vs "
                f"{len(args)} C args; add it to HAND_WRITTEN"
            )
        sig_parts, names = [], []
        for p in params:
            name = _ident(bridge.camel_to_snake(p.name))
            names.append(name)
            default = _default_repr(p.default, p.typename, b.idl)
            pann = _annotate(
                b.idl, p.typename, optional=not p.required and default == "None"
            )
            if p.required:
                sig_parts.append(f"{name}: {pann}")
            else:
                sig_parts.append(f"{name}: {pann} = {default}")
        sig = ", ".join(sig_parts)
        passthrough = "".join(f", {n}" for n in names)
        if call is None and not is_async and binds is not None:
            call = _direct_body(b, spec_object, spec_method, params, binds, native)
        if call is None:
            call = f"self._call({spec_method['name']!r}{passthrough})"
        decl = f"def {_ident(py)}(self{', ' + sig if sig else ''}) -> {ann}:"

    doc = f'        """{cls_name}.{fn_name} -- see the WebGPU specification."""'
    if isinstance(prologue, str):
        prologue = [prologue]
    if not is_async:
        body = [f"    {decl}", doc]
        body += [f"        {ln}" for ln in prologue or ()]
        return [*body, f"        return {call}", ""]

    # Promise-returning: wgpu-py exposes both a blocking and an awaitable form.
    # Unless the IDL already has a separate synchronous sibling, in which case
    # only the awaitable form is ours to add.
    has_sync_sibling = any(
        bridge.camel_to_snake(other) == py
        for other in interface.functions
        if other != fn_name
    )
    out = []
    variants = (("_async", "self._promise"),)
    if not has_sync_sibling:
        variants += (("_sync", "self._await"),)
    for suffix, wrap in variants:
        adecl = decl.replace(f"def {_ident(py)}(", f"def {_ident(py)}{suffix}(", 1)
        out += [f"    {adecl}", doc, f"        return {wrap}({call})", ""]
    if not has_sync_sibling:
        out += [f"    {_ident(py)} = _ov.deprecated_sync_or_async({py!r})", ""]
    return out


def _flatten_descriptor(b, idl_struct_name: str) -> tuple[str, str]:
    """Turn a descriptor struct into keyword parameters + the mapping literal."""
    name = idl_struct_name[3:]  # strip GPU
    if name.endswith("Dict"):
        name = name[:-4]
    fields = b.idl.structs[name]
    ordered, items = [], []
    for fname, attr in fields.items():
        py = _ident(bridge.camel_to_snake(fname))
        default = _default_repr(attr.default, attr.typename, b.idl)
        ann = _annotate(
            b.idl, attr.typename, optional=not attr.required and default == "None"
        )
        if attr.required:
            ordered.append(f"{py}: {ann}")
        else:
            ordered.append(f"{py}: {ann} = {default}")
        items.append(f"{py!r}: {py}")
    # Keyword-only, so a required parameter may follow a defaulted one; keeping
    # IDL declaration order means ``label`` stays first, as it always has been.
    sig_parts = ordered
    mapping = "{" + ", ".join(items) + "}"
    return ", ".join(sig_parts), mapping


def write_all(out_dir: Path = GENERATED_DIR) -> list[Path]:
    from .generate import _import_module

    b = bridge.build()
    mod = _import_module()
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for fname, text in [
        ("apienums.py", generate_api_enums(b, mod.lib)),
        ("apiflags.py", generate_api_flags(b)),
    ]:
        path = out_dir / fname
        path.write_text(text)
        written.append(path)
    return written


if __name__ == "__main__":
    for p in write_all():
        print("wrote", p.relative_to(paths.REPO_ROOT))
