"""Generate the high-level Pythonic layer from ``webgpu.json`` + the compiled lib.

The spec (``webgpu.json``) provides *structure* (which enums/flags/structs/
objects exist, their members, types, defaults and docstrings); the compiled
extension provides *values* (enum integers) and *validation* (every C name we
derive must actually resolve). Anything that does not resolve raises, so a
submodule bump can never silently emit wrong bindings.

Currently generates:
* ``enums.py``  -- one ``IntEnum`` per spec enum
* ``flags.py``  -- one ``IntFlag`` per spec bitflag

(structs and object classes follow.)
"""

from __future__ import annotations

import json
import keyword
from pathlib import Path

from . import naming, paths

GENERATED_DIR = paths.REPO_ROOT / "wgpu" / "_generated"

_BANNER = '''\
# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Source of truth: wgpu-native/ffi/webgpu-headers/webgpu.json (the machine-
# readable WebGPU spec) plus the compiled extension for enum values. Re-run the
# generator after bumping the wgpu-native submodule.
'''


def load_spec() -> dict:
    return json.loads(paths.WEBGPU_JSON.read_text())


def _import_module():
    """Load the compiled low-level extension (exposes ``.lib`` and ``.ffi``)."""
    from .ffi_build import NATIVE_DIR, load_compiled

    return load_compiled(NATIVE_DIR)


def _docstring(text: str | None, indent: str) -> str:
    text = (text or "").strip()
    if not text or text == "TODO":
        return ""
    lines = text.splitlines()
    if len(lines) == 1:
        return f'{indent}"""{lines[0]}"""\n'
    body = "\n".join(indent + ln if ln else "" for ln in lines)
    return f'{indent}"""\n{body}\n{indent}"""\n'


def _member_ident(spec_name: str) -> str:
    ident = naming.py_enum_member(spec_name)
    if keyword.iskeyword(ident):
        ident += "_"
    return ident


def _emit_enum_like(spec_group, lib, base_class, c_value_fn) -> str:
    """Shared emitter for enums and bitflags."""
    out: list[str] = []
    for item in spec_group:
        py_name = naming.py_enum_name(item["name"])
        out.append(f"class {py_name}({base_class}):")
        doc = _docstring(item.get("doc"), "    ")
        if doc:
            out.append(doc.rstrip("\n"))
        seen: set[str] = set()
        emitted = 0
        for entry in item["entries"]:
            if entry is None:
                continue
            c_name = c_value_fn(item["name"], entry["name"])
            value = int(getattr(lib, c_name))  # validates + reads real value
            ident = _member_ident(entry["name"])
            if ident in seen:
                continue
            seen.add(ident)
            out.append(f"    {ident} = {value}")
            emitted += 1
        if emitted == 0:
            out.append("    pass")
        out.append("")
        out.append("")
    return "\n".join(out)


def generate_enums(spec, lib) -> str:
    body = _emit_enum_like(spec["enums"], lib, "enum.IntEnum", naming.c_enum_value)
    return f"{_BANNER}\nimport enum\n\n\n{body}"


def generate_flags(spec, lib) -> str:
    body = _emit_enum_like(spec["bitflags"], lib, "enum.IntFlag", naming.c_enum_value)
    return f"{_BANNER}\nimport enum\n\n\n{body}"


# ---- structs ---------------------------------------------------------------

def _parse_member_type(spec_type: str) -> tuple[str, str | None, bool]:
    """Return ``(kind, ref, is_array)`` for a spec member ``type`` string.

    ``kind`` is one of: prim, string, out_string, enum, bitflag, struct,
    object, callback, c_void. ``ref`` is the referenced spec name for
    enum/bitflag/struct/object/callback, else ``None``.
    """
    is_array = spec_type.startswith("array<")
    if is_array:
        spec_type = spec_type[len("array<") : -1]
    if "." in spec_type:
        cat, ref = spec_type.split(".", 1)
        kind = {
            "enum": "enum",
            "bitflag": "bitflag",
            "struct": "struct",
            "object": "object",
            "callback": "callback",
        }.get(cat, cat)
        return kind, ref, is_array
    if spec_type in ("string_with_default_empty", "nullable_string"):
        return "string", None, is_array
    if spec_type == "out_string":
        return "out_string", None, is_array
    if spec_type == "c_void":
        return "c_void", None, is_array
    return "prim", spec_type, is_array


def generate_structs(spec, ffi) -> str:
    """Emit declarative descriptors for every struct, validated against the ffi.

    Each descriptor records the C type/field names, member kinds, pointer-ness,
    optionality and defaults -- everything a runtime builder needs to turn a
    Python mapping into a filled cffi struct. Every C field name is checked to
    exist on the real compiled type, so a naming drift fails generation.
    """
    lines = [
        _BANNER,
        '"""Declarative descriptors for every wgpu-native struct.',
        "",
        "``STRUCTS[spec_name]`` maps to a ``StructDescriptor``. The runtime struct",
        "builder consumes these; they are generated, not hand-written.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass, field",
        "",
        "",
        "@dataclass(frozen=True)",
        "class Member:",
        "    py: str          # pythonic keyword name",
        "    c: str           # C struct field name",
        "    kind: str        # prim|string|out_string|enum|bitflag|struct|object|callback|c_void",
        "    ref: str | None  # referenced spec name (enum/bitflag/struct/object)",
        "    pointer: str | None",
        "    optional: bool",
        "    default: object",
        "    array: bool",
        "    count_c: str | None  # C count field, for arrays",
        "",
        "",
        "@dataclass(frozen=True)",
        "class StructDescriptor:",
        "    c_name: str",
        "    category: str    # extensible|standalone|extension|extensible_callback_arg",
        "    members: tuple = field(default_factory=tuple)",
        "",
        "",
        "STRUCTS: dict[str, StructDescriptor] = {}",
        "",
    ]

    for st in spec["structs"]:
        c_name = naming.c_type_name(st["name"])
        c_type = ffi.typeof(c_name)  # validates the struct type exists
        c_fields = {f[0] for f in (c_type.fields or [])}

        members_src = []
        for mem in st.get("members", []):
            kind, ref, is_array = _parse_member_type(mem["type"])
            c_field = naming.c_struct_field(mem["name"])
            assert c_field in c_fields, f"{c_name} has no field {c_field}"
            count_c = None
            if is_array:
                count_c = naming.c_array_count_field(mem["name"])
                assert count_c in c_fields, f"{c_name} has no count field {count_c}"
            members_src.append(
                "        Member(py={!r}, c={!r}, kind={!r}, ref={!r}, pointer={!r}, "
                "optional={!r}, default={!r}, array={!r}, count_c={!r}),".format(
                    naming.py_member_name(mem["name"]),
                    c_field,
                    kind,
                    ref,
                    mem.get("pointer"),
                    bool(mem.get("optional", False)),
                    mem.get("default"),
                    is_array,
                    count_c,
                )
            )
        lines.append(f"STRUCTS[{st['name']!r}] = StructDescriptor(")
        lines.append(f"    c_name={c_name!r},")
        lines.append(f"    category={st.get('type')!r},")
        if members_src:
            lines.append("    members=(")
            lines.extend(members_src)
            lines.append("    ),")
        lines.append(")")
        lines.append("")
    return "\n".join(lines)


def write_all(out_dir: Path = GENERATED_DIR) -> list[Path]:
    spec = load_spec()
    mod = _import_module()
    lib, ffi = mod.lib, mod.ffi
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "__init__.py").write_text(
        _BANNER + '\n"""Auto-generated Pythonic layer for wgpu-native."""\n'
    )
    written = []
    for fname, text in [
        ("enums.py", generate_enums(spec, lib)),
        ("flags.py", generate_flags(spec, lib)),
        ("structs.py", generate_structs(spec, ffi)),
    ]:
        path = out_dir / fname
        path.write_text(text)
        written.append(path)
    return written


if __name__ == "__main__":
    for p in write_all():
        print("wrote", p.relative_to(paths.REPO_ROOT))
