"""Generate the high-level Pythonic layer from ``webgpu.json`` + the compiled lib.

The spec (``webgpu.json``) provides *structure* (which enums/flags/structs/
objects exist, their members, types, defaults and docstrings); the compiled
extension provides *values* (enum integers) and *validation* (every C name we
derive must actually resolve). Anything that does not resolve raises, so a
submodule bump can never silently emit wrong bindings.

Currently generates:
* ``enums.py``  -- one ``IntEnum`` per spec enum
* ``flags.py``  -- one ``IntFlag`` per spec bitflag

(structs and object classes follow.)
"""

from __future__ import annotations

import json
import keyword
from pathlib import Path

from . import naming, paths

GENERATED_DIR = paths.REPO_ROOT / "wgpu" / "_generated"

_BANNER = '''\
# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Source of truth: wgpu-native/ffi/webgpu-headers/webgpu.json (the machine-
# readable WebGPU spec) plus the compiled extension for enum values. Re-run the
# generator after bumping the wgpu-native submodule.
'''


def load_spec() -> dict:
    return json.loads(paths.WEBGPU_JSON.read_text())


def _import_lib():
    """Load the compiled low-level extension, returning its ``lib`` object."""
    from .ffi_build import NATIVE_DIR, load_compiled

    return load_compiled(NATIVE_DIR).lib


def _docstring(text: str | None, indent: str) -> str:
    text = (text or "").strip()
    if not text or text == "TODO":
        return ""
    lines = text.splitlines()
    if len(lines) == 1:
        return f'{indent}"""{lines[0]}"""\n'
    body = "\n".join(indent + ln if ln else "" for ln in lines)
    return f'{indent}"""\n{body}\n{indent}"""\n'


def _member_ident(spec_name: str) -> str:
    ident = naming.py_enum_member(spec_name)
    if keyword.iskeyword(ident):
        ident += "_"
    return ident


def _emit_enum_like(spec_group, lib, base_class, c_value_fn) -> str:
    """Shared emitter for enums and bitflags."""
    out: list[str] = []
    for item in spec_group:
        py_name = naming.py_enum_name(item["name"])
        out.append(f"class {py_name}({base_class}):")
        doc = _docstring(item.get("doc"), "    ")
        if doc:
            out.append(doc.rstrip("\n"))
        seen: set[str] = set()
        emitted = 0
        for entry in item["entries"]:
            if entry is None:
                continue
            c_name = c_value_fn(item["name"], entry["name"])
            value = int(getattr(lib, c_name))  # validates + reads real value
            ident = _member_ident(entry["name"])
            if ident in seen:
                continue
            seen.add(ident)
            out.append(f"    {ident} = {value}")
            emitted += 1
        if emitted == 0:
            out.append("    pass")
        out.append("")
        out.append("")
    return "\n".join(out)


def generate_enums(spec, lib) -> str:
    body = _emit_enum_like(spec["enums"], lib, "enum.IntEnum", naming.c_enum_value)
    return f"{_BANNER}\nimport enum\n\n\n{body}"


def generate_flags(spec, lib) -> str:
    body = _emit_enum_like(spec["bitflags"], lib, "enum.IntFlag", naming.c_enum_value)
    return f"{_BANNER}\nimport enum\n\n\n{body}"


def write_all(out_dir: Path = GENERATED_DIR) -> list[Path]:
    spec = load_spec()
    lib = _import_lib()
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "__init__.py").write_text(
        _BANNER + '\n"""Auto-generated Pythonic layer for wgpu-native."""\n'
    )
    written = []
    for fname, text in [
        ("enums.py", generate_enums(spec, lib)),
        ("flags.py", generate_flags(spec, lib)),
    ]:
        path = out_dir / fname
        path.write_text(text)
        written.append(path)
    return written


if __name__ == "__main__":
    for p in write_all():
        print("wrote", p.relative_to(paths.REPO_ROOT))
