"""Generate the high-level Pythonic layer from ``webgpu.json`` + the compiled lib.

The spec (``webgpu.json``) provides *structure* (which enums/flags/structs/
objects exist, their members, types, defaults and docstrings); the compiled
extension provides *values* (enum integers) and *validation* (every C name we
derive must actually resolve). Anything that does not resolve raises, so a
submodule bump can never silently emit wrong bindings.

Generates, into ``wgpu/_generated/``:

* ``enums.py``     -- one ``IntEnum`` per spec enum, plus ``BY_SPEC_NAME``
* ``flags.py``     -- one ``IntFlag`` per spec bitflag, plus ``BY_SPEC_NAME``
* ``structs.py``   -- declarative descriptors driving the runtime struct builder
* ``constants.py`` -- the WebGPU sentinel constants
* ``objects.py``   -- the object/method table (C functions, args, lifecycles)
* ``classes.py``   -- the ``GPU*`` wrapper classes

The output is committed, so bumping the submodule yields a reviewable diff, and
it never imports this package: the runtime must work in a wheel that ships no
generator.
"""

from __future__ import annotations

import json
import keyword
from pathlib import Path

from . import naming, paths

GENERATED_DIR = paths.REPO_ROOT / "wgpu" / "_generated"

_BANNER = """\
# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Source of truth: wgpu-native/ffi/webgpu-headers/webgpu.json (the machine-
# readable WebGPU spec) plus the compiled extension for enum values. Re-run the
# generator after bumping the wgpu-native submodule.
"""


def load_spec() -> dict:
    return json.loads(paths.WEBGPU_JSON.read_text())


def _import_module():
    """Load the compiled low-level extension (exposes ``.lib`` and ``.ffi``)."""
    from .ffi_build import NATIVE_DIR, load_compiled

    return load_compiled(NATIVE_DIR)


def _docstring(text: str | None, indent: str) -> str:
    text = (text or "").strip()
    if not text or text == "TODO":
        return ""
    # Escape so arbitrary upstream doc text can never produce invalid Python
    # (a stray triple quote or a trailing backslash would otherwise break it).
    text = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    lines = text.splitlines()
    if len(lines) == 1 and not lines[0].endswith('"'):
        return f'{indent}"""{lines[0]}"""\n'
    body = "\n".join(indent + ln if ln else "" for ln in lines)
    return f'{indent}"""\n{body}\n{indent}"""\n'


def _member_ident(spec_name: str) -> str:
    ident = naming.py_enum_member(spec_name)
    if keyword.iskeyword(ident):
        ident += "_"
    return ident


def _emit_enum_like(spec_group, lib, base_class, c_value_fn) -> str:
    """Shared emitter for enums and bitflags."""
    out: list[str] = []
    for item in spec_group:
        py_name = naming.py_enum_name(item["name"])
        out.append(f"class {py_name}({base_class}):")
        doc = _docstring(item.get("doc"), "    ")
        if doc:
            out.append(doc.rstrip("\n"))
        seen: set[str] = set()
        emitted = 0
        for entry in item["entries"]:
            if entry is None:
                continue
            c_name = c_value_fn(item["name"], entry["name"])
            value = int(getattr(lib, c_name))  # validates + reads real value
            ident = _member_ident(entry["name"])
            if ident in seen:
                continue
            seen.add(ident)
            out.append(f"    {ident} = {value}")
            emitted += 1
        if emitted == 0:
            out.append("    pass")
        out.append("")
        out.append("")
    return "\n".join(out)


def _by_spec_name(spec_group) -> str:
    """Emit a spec-name -> class map, so the runtime never needs the generator."""
    lines = ["BY_SPEC_NAME = {"]
    for item in spec_group:
        lines.append(f"    {item['name']!r}: {naming.py_enum_name(item['name'])},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_enums(spec, lib) -> str:
    body = _emit_enum_like(spec["enums"], lib, "enum.IntEnum", naming.c_enum_value)
    return f"{_BANNER}\nimport enum\n\n\n{body}{_by_spec_name(spec['enums'])}"


def generate_flags(spec, lib) -> str:
    body = _emit_enum_like(spec["bitflags"], lib, "enum.IntFlag", naming.c_enum_value)
    return f"{_BANNER}\nimport enum\n\n\n{body}{_by_spec_name(spec['bitflags'])}"


# ---- structs ---------------------------------------------------------------


def _parse_member_type(spec_type: str) -> tuple[str, str | None, bool]:
    """Return ``(kind, ref, is_array)`` for a spec member ``type`` string.

    ``kind`` is one of: prim, string, out_string, enum, bitflag, struct,
    object, callback, c_void. ``ref`` is the referenced spec name for
    enum/bitflag/struct/object/callback, else ``None``.
    """
    is_array = spec_type.startswith("array<")
    if is_array:
        spec_type = spec_type[len("array<") : -1]
    if "." in spec_type:
        cat, ref = spec_type.split(".", 1)
        kind = {
            "enum": "enum",
            "bitflag": "bitflag",
            "struct": "struct",
            "object": "object",
            "callback": "callback",
        }.get(cat, cat)
        return kind, ref, is_array
    if spec_type in ("string_with_default_empty", "nullable_string"):
        return "string", None, is_array
    if spec_type == "out_string":
        return "out_string", None, is_array
    if spec_type == "c_void":
        return "c_void", None, is_array
    return "prim", spec_type, is_array


def _resolve_default(mem, kind, ref, lib):
    """Resolve a spec default to something the runtime can use directly.

    Enum/bitflag member names become plain integers here, so the runtime never
    has to map spec names back to Python identifiers. ``constant.*`` defaults
    stay symbolic because some are size_t-width and must be resolved per target.
    """
    default = mem.get("default")
    if not isinstance(default, str):
        return default
    if default.startswith("constant.") or default.startswith("0x"):
        return default
    if kind in ("enum", "bitflag"):
        return int(getattr(lib, naming.c_enum_value(ref, default)))
    return default


def generate_structs(spec, ffi, lib) -> str:
    """Emit declarative descriptors for every struct, validated against the ffi.

    Each descriptor records the C type/field names, member kinds, pointer-ness,
    optionality and defaults -- everything a runtime builder needs to turn a
    Python mapping into a filled cffi struct. Every C field name is checked to
    exist on the real compiled type, so a naming drift fails generation.
    """
    lines = [
        _BANNER,
        '"""Declarative descriptors for every wgpu-native struct.',
        "",
        "``STRUCTS[spec_name]`` maps to a ``StructDescriptor``. The runtime struct",
        "builder consumes these; they are generated, not hand-written.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass, field",
        "",
        "",
        "@dataclass(frozen=True)",
        "class Member:",
        "    py: str          # pythonic keyword name",
        "    c: str           # C struct field name",
        "    kind: str        # prim|string|out_string|enum|bitflag|struct|object|callback|c_void",
        "    ref: str | None  # referenced spec name (enum/bitflag/struct/object)",
        "    pointer: str | None",
        "    optional: bool",
        "    default: object",
        "    array: bool",
        "    count_c: str | None  # C count field, for arrays",
        "",
        "",
        "@dataclass(frozen=True)",
        "class StructDescriptor:",
        "    c_name: str",
        "    category: str    # extensible|standalone|extension|extensible_callback_arg",
        "    members: tuple = field(default_factory=tuple)",
        "",
        "",
        "STRUCTS: dict[str, StructDescriptor] = {}",
        "",
    ]

    for st in spec["structs"]:
        c_name = naming.c_type_name(st["name"])
        c_type = ffi.typeof(c_name)  # validates the struct type exists
        c_fields = {f[0] for f in (c_type.fields or [])}

        members_src = []
        for mem in st.get("members", []):
            kind, ref, is_array = _parse_member_type(mem["type"])
            c_field = naming.c_struct_field(mem["name"])
            assert c_field in c_fields, f"{c_name} has no field {c_field}"
            count_c = None
            if is_array:
                count_c = naming.c_array_count_field(mem["name"])
                assert count_c in c_fields, f"{c_name} has no count field {count_c}"
            members_src.append(
                "        Member(py={!r}, c={!r}, kind={!r}, ref={!r}, pointer={!r}, "
                "optional={!r}, default={!r}, array={!r}, count_c={!r}),".format(
                    naming.py_member_name(mem["name"]),
                    c_field,
                    kind,
                    ref,
                    mem.get("pointer"),
                    bool(mem.get("optional", False)),
                    _resolve_default(mem, kind, ref, lib),
                    is_array,
                    count_c,
                )
            )
        lines.append(f"STRUCTS[{st['name']!r}] = StructDescriptor(")
        lines.append(f"    c_name={c_name!r},")
        lines.append(f"    category={st.get('type')!r},")
        if members_src:
            lines.append("    members=(")
            lines.extend(members_src)
            lines.append("    ),")
        lines.append(")")
        lines.append("")
    return "\n".join(lines)


# ---- constants -------------------------------------------------------------

# Symbolic constant values in the spec, mapped to a cross-platform-correct
# Python expression. size_t-width values are resolved at runtime from the ffi so
# the committed file stays correct on 32- and 64-bit targets alike.
_CONST_EXPR = {
    "uint32_max": "0xFFFFFFFF",
    "uint64_max": "0xFFFFFFFFFFFFFFFF",
    "usize_max": "_SIZE_T_MAX",
    "nan": 'float("nan")',
}


def generate_constants(spec) -> str:
    lines = [
        _BANNER,
        '"""WebGPU sentinel constants (e.g. WHOLE_SIZE), from webgpu.json."""',
        "",
        "from wgpu._native import ffi as _ffi",
        "",
        "_SIZE_T_MAX = (1 << (8 * _ffi.sizeof('size_t'))) - 1",
        "",
    ]
    for const in spec["constants"]:
        expr = _CONST_EXPR[const["value"]]
        lines.append(f"{const['name']} = {expr}")
    lines.append("")
    return "\n".join(lines)


# ---- objects & methods -----------------------------------------------------


def _arg_descriptor(arg: dict) -> str:
    """Emit an ``Arg(...)`` literal for a method argument."""
    kind, ref, is_array = _parse_member_type(arg["type"])
    count_c = naming.c_array_count_field(arg["name"]) if is_array else None
    return (
        "Arg(py={!r}, kind={!r}, ref={!r}, pointer={!r}, optional={!r}, "
        "array={!r}, count_c={!r})".format(
            naming.py_member_name(arg["name"]),
            kind,
            ref,
            arg.get("pointer"),
            bool(arg.get("optional", False)),
            is_array,
            count_c,
        )
    )


def _c_arg_count(lib, ffi, c_func: str) -> int:
    return len(ffi.typeof(getattr(lib, c_func)).args)


def generate_objects(spec, lib, ffi) -> str:
    """Emit the declarative method table for every object, validated against
    the compiled lib (each C function exists and its arg count matches)."""
    lines = [
        _BANNER,
        '"""Declarative object/method descriptors, generated from webgpu.json.',
        "",
        "The runtime invoker turns these into live Python method calls. Names and",
        "arg counts are validated against the compiled extension at generation.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass, field",
        "",
        "",
        "@dataclass(frozen=True)",
        "class Arg:",
        "    py: str",
        "    kind: str        # prim|string|enum|bitflag|struct|object|c_void",
        "    ref: str | None",
        "    pointer: str | None",
        "    optional: bool",
        "    array: bool",
        "    count_c: str | None",
        "",
        "",
        "@dataclass(frozen=True)",
        "class Method:",
        "    py: str",
        "    c_func: str",
        "    args: tuple = ()",
        "    ret_kind: str | None = None   # None == void",
        "    ret_ref: str | None = None",
        "    ret_optional: bool = False",
        "    is_async: bool = False",
        "    callback_ref: str | None = None",
        "    callback_info_c: str | None = None  # e.g. WGPURequestAdapterCallbackInfo",
        "    callback_result_ref: str | None = None  # object the callback returns",
        "    doc: str = ''",
        "",
        "",
        "@dataclass(frozen=True)",
        "class ObjectType:",
        "    c_name: str",
        "    release_func: str = ''   # e.g. wgpuDeviceRelease",
        "    add_ref_func: str = ''   # e.g. wgpuDeviceAddRef",
        "    methods: tuple = field(default_factory=tuple)",
        "",
        "",
        "OBJECTS: dict[str, ObjectType] = {}",
        "",
    ]

    callbacks = {cb["name"]: cb for cb in spec["callbacks"]}

    def _callback_result(callback_ref):
        cb = callbacks[callback_ref.split(".", 1)[1]]
        for a in cb.get("args", []):
            if a["type"].startswith("object."):
                return a["type"].split(".", 1)[1]
        return None

    for obj in spec["objects"]:
        c_name = naming.c_type_name(obj["name"])
        methods_src = []
        for meth in obj.get("methods", []):
            c_func = naming.c_method_func(obj["name"], meth["name"])
            n_c_args = _c_arg_count(lib, ffi, c_func)  # validates func exists
            is_async = "callback" in meth
            args = meth.get("args", [])
            # expected C args: self + (2 per array arg else 1) + (1 if async)
            expected = 1 + sum(2 if a["type"].startswith("array<") else 1 for a in args)
            expected += 1 if is_async else 0
            assert expected == n_c_args, (
                f"{c_func}: arg-count mismatch spec={expected} c={n_c_args}"
            )
            ret = meth.get("returns")
            ret_kind = ret_ref = None
            ret_optional = False
            if ret and not is_async:
                ret_kind, ret_ref, _ = _parse_member_type(ret["type"])
                ret_optional = bool(ret.get("optional", False))
            callback_info_c = None
            callback_result_ref = None
            if is_async:
                cb = meth["callback"].split(".", 1)[1]
                callback_info_c = naming.c_type_name(cb) + "CallbackInfo"
                callback_result_ref = _callback_result(meth["callback"])
            args_src = ",\n            ".join(_arg_descriptor(a) for a in args)
            methods_src.append(
                "        Method(\n"
                f"            py={meth['name']!r}, c_func={c_func!r},\n"
                f"            args=({args_src}{',' if args else ''}),\n"
                f"            ret_kind={ret_kind!r}, ret_ref={ret_ref!r}, ret_optional={ret_optional!r},\n"
                f"            is_async={is_async!r}, callback_ref={meth.get('callback')!r},\n"
                f"            callback_info_c={callback_info_c!r},\n"
                f"            callback_result_ref={callback_result_ref!r},\n"
                f"            doc={_clean_doc(meth.get('doc'))!r},\n"
                "        ),"
            )
        release_func = naming.c_object_lifecycle(obj["name"], "Release")
        add_ref_func = naming.c_object_lifecycle(obj["name"], "AddRef")
        for fn in (release_func, add_ref_func):
            getattr(lib, fn)  # validate the lifecycle functions exist
        lines.append(f"OBJECTS[{obj['name']!r}] = ObjectType(")
        lines.append(f"    c_name={c_name!r},")
        lines.append(f"    release_func={release_func!r},")
        lines.append(f"    add_ref_func={add_ref_func!r},")
        if methods_src:
            lines.append("    methods=(")
            lines.extend(methods_src)
            lines.append("    ),")
        lines.append(")")
        lines.append("")
    return "\n".join(lines)


def _clean_doc(text: str | None) -> str:
    text = (text or "").strip()
    return "" if text in ("", "TODO") else text


# ---- classes ---------------------------------------------------------------


def generate_classes(spec) -> str:
    """Emit one ``GPU<Object>`` class per object with real method signatures.

    Every method body funnels through ``GPUObjectBase._invoke``, so the classes
    are ergonomic (introspectable signatures + docstrings) with zero per-method
    hand code.
    """
    import keyword as _kw

    lines = [
        _BANNER,
        '"""Generated ``GPU*`` wrapper classes for wgpu-native objects."""',
        "",
        "from wgpu._runtime.base import GPUObjectBase",
        "",
    ]
    for obj in spec["objects"]:
        cls = "GPU" + naming.py_class_name(obj["name"])
        lines.append(f"class {cls}(GPUObjectBase):")
        lines.append(f"    _spec_name = {obj['name']!r}")
        lines.append("")
        methods = obj.get("methods", [])
        if not methods:
            lines.append("    pass")
            lines.append("")
        for meth in methods:
            args = meth.get("args", [])
            # A default (=None) is only valid for a trailing run of optional args,
            # since Python forbids a defaulted param before a required one. The
            # invoker still accepts None for any optional arg.
            can_default = [False] * len(args)
            for i in range(len(args) - 1, -1, -1):
                if args[i].get("optional") and (
                    i == len(args) - 1 or can_default[i + 1]
                ):
                    can_default[i] = True
                else:
                    break
            params = ["self"]
            names = []
            for i, arg in enumerate(args):
                name = naming.py_member_name(arg["name"])
                if _kw.iskeyword(name):
                    name += "_"
                names.append(name)
                params.append(f"{name}=None" if can_default[i] else name)
            call_args = ", ".join(names)
            sig = ", ".join(params)
            lines.append(f"    def {_py_method(meth['name'])}({sig}):")
            doc = _docstring(meth.get("doc"), "        ")
            if doc:
                lines.append(doc.rstrip("\n"))
            passthrough = f", {call_args}" if call_args else ""
            lines.append(f"        return self._invoke({meth['name']!r}{passthrough})")
            lines.append("")
        lines.append("")
    return "\n".join(lines)


def _py_method(name: str) -> str:
    import keyword as _kw

    return name + "_" if _kw.iskeyword(name) else name


def write_all(out_dir: Path = GENERATED_DIR) -> list[Path]:
    spec = load_spec()
    mod = _import_module()
    lib, ffi = mod.lib, mod.ffi
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "__init__.py").write_text(
        _BANNER + '\n"""Auto-generated Pythonic layer for wgpu-native."""\n'
    )
    written = []
    for fname, text in [
        ("enums.py", generate_enums(spec, lib)),
        ("flags.py", generate_flags(spec, lib)),
        ("structs.py", generate_structs(spec, ffi, lib)),
        ("constants.py", generate_constants(spec)),
        ("objects.py", generate_objects(spec, lib, ffi)),
        ("classes.py", generate_classes(spec)),
    ]:
        path = out_dir / fname
        path.write_text(text)
        written.append(path)
    return written


if __name__ == "__main__":
    for p in write_all():
        print("wrote", p.relative_to(paths.REPO_ROOT))
