# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Public API surface, generated from bindgen/resources/webgpu.idl (the W3C
# WebGPU Web IDL) and cross-referenced against the wgpu-native C spec. Re-run
# the generator after updating either spec.

"""The public ``GPU*`` classes."""

from __future__ import annotations

from collections.abc import Sequence

from wgpu._api import overrides as _ov
from wgpu._api.base import unimplemented as _unimplemented
from wgpu._api.base import GPUHandle, GPUObjectBase, Mixin
from wgpu._api.base import new_object as _new_object
from wgpu._api.base import slice_data as _slice_data
from wgpu._api.types import ArrayLike, CanvasLike
from wgpu._generated import apienums as enums
from wgpu._generated import apiflags as flags
from wgpu._generated import apistructs as structs

# Bound once at import so the hot methods below are a single C call.
from wgpu._native import ffi as _ffi, lib as _lib
from wgpu._api.base import raise_if_error as _raise_if_error
from wgpu._generated.constants import strlen as _STRLEN
from wgpu._runtime.errors import InvalidValueError

_NULL = _ffi.NULL
_WHOLE64 = 18446744073709551615
_E_address_mode = enums.TO_INT['address_mode']
_E_compare_function = enums.TO_INT['compare_function']
_E_error_filter = enums.TO_INT['error_filter']
_E_filter_mode = enums.TO_INT['filter_mode']
_E_index_format = enums.TO_INT['index_format']
_E_mipmap_filter_mode = enums.TO_INT['mipmap_filter_mode']
_E_query_type = enums.TO_INT['query_type']
_F_buffer_usage = flags.TO_INT['buffer_usage']
_c_wgpuBufferDestroy = _lib.wgpuBufferDestroy
_c_wgpuCommandEncoderClearBuffer = _lib.wgpuCommandEncoderClearBuffer
_c_wgpuCommandEncoderCopyBufferToBuffer = _lib.wgpuCommandEncoderCopyBufferToBuffer
_c_wgpuCommandEncoderFinish = _lib.wgpuCommandEncoderFinish
_c_wgpuCommandEncoderPopDebugGroup = _lib.wgpuCommandEncoderPopDebugGroup
_c_wgpuCommandEncoderResolveQuerySet = _lib.wgpuCommandEncoderResolveQuerySet
_c_wgpuComputePassEncoderDispatchWorkgroups = _lib.wgpuComputePassEncoderDispatchWorkgroups
_c_wgpuComputePassEncoderDispatchWorkgroupsIndirect = _lib.wgpuComputePassEncoderDispatchWorkgroupsIndirect
_c_wgpuComputePassEncoderEnd = _lib.wgpuComputePassEncoderEnd
_c_wgpuComputePassEncoderPopDebugGroup = _lib.wgpuComputePassEncoderPopDebugGroup
_c_wgpuComputePassEncoderSetBindGroup = _lib.wgpuComputePassEncoderSetBindGroup
_c_wgpuComputePassEncoderSetPipeline = _lib.wgpuComputePassEncoderSetPipeline
_c_wgpuComputePipelineGetBindGroupLayout = _lib.wgpuComputePipelineGetBindGroupLayout
_c_wgpuDeviceCreateBuffer = _lib.wgpuDeviceCreateBuffer
_c_wgpuDeviceCreateCommandEncoder = _lib.wgpuDeviceCreateCommandEncoder
_c_wgpuDeviceCreateQuerySet = _lib.wgpuDeviceCreateQuerySet
_c_wgpuDeviceCreateSampler = _lib.wgpuDeviceCreateSampler
_c_wgpuDeviceDestroy = _lib.wgpuDeviceDestroy
_c_wgpuDevicePushErrorScope = _lib.wgpuDevicePushErrorScope
_c_wgpuQuerySetDestroy = _lib.wgpuQuerySetDestroy
_c_wgpuQueueSubmit = _lib.wgpuQueueSubmit
_c_wgpuRenderBundleEncoderDraw = _lib.wgpuRenderBundleEncoderDraw
_c_wgpuRenderBundleEncoderDrawIndexed = _lib.wgpuRenderBundleEncoderDrawIndexed
_c_wgpuRenderBundleEncoderDrawIndexedIndirect = _lib.wgpuRenderBundleEncoderDrawIndexedIndirect
_c_wgpuRenderBundleEncoderDrawIndirect = _lib.wgpuRenderBundleEncoderDrawIndirect
_c_wgpuRenderBundleEncoderFinish = _lib.wgpuRenderBundleEncoderFinish
_c_wgpuRenderBundleEncoderPopDebugGroup = _lib.wgpuRenderBundleEncoderPopDebugGroup
_c_wgpuRenderBundleEncoderSetBindGroup = _lib.wgpuRenderBundleEncoderSetBindGroup
_c_wgpuRenderBundleEncoderSetIndexBuffer = _lib.wgpuRenderBundleEncoderSetIndexBuffer
_c_wgpuRenderBundleEncoderSetPipeline = _lib.wgpuRenderBundleEncoderSetPipeline
_c_wgpuRenderBundleEncoderSetVertexBuffer = _lib.wgpuRenderBundleEncoderSetVertexBuffer
_c_wgpuRenderPassEncoderBeginOcclusionQuery = _lib.wgpuRenderPassEncoderBeginOcclusionQuery
_c_wgpuRenderPassEncoderDraw = _lib.wgpuRenderPassEncoderDraw
_c_wgpuRenderPassEncoderDrawIndexed = _lib.wgpuRenderPassEncoderDrawIndexed
_c_wgpuRenderPassEncoderDrawIndexedIndirect = _lib.wgpuRenderPassEncoderDrawIndexedIndirect
_c_wgpuRenderPassEncoderDrawIndirect = _lib.wgpuRenderPassEncoderDrawIndirect
_c_wgpuRenderPassEncoderEnd = _lib.wgpuRenderPassEncoderEnd
_c_wgpuRenderPassEncoderEndOcclusionQuery = _lib.wgpuRenderPassEncoderEndOcclusionQuery
_c_wgpuRenderPassEncoderExecuteBundles = _lib.wgpuRenderPassEncoderExecuteBundles
_c_wgpuRenderPassEncoderPopDebugGroup = _lib.wgpuRenderPassEncoderPopDebugGroup
_c_wgpuRenderPassEncoderSetBindGroup = _lib.wgpuRenderPassEncoderSetBindGroup
_c_wgpuRenderPassEncoderSetIndexBuffer = _lib.wgpuRenderPassEncoderSetIndexBuffer
_c_wgpuRenderPassEncoderSetPipeline = _lib.wgpuRenderPassEncoderSetPipeline
_c_wgpuRenderPassEncoderSetScissorRect = _lib.wgpuRenderPassEncoderSetScissorRect
_c_wgpuRenderPassEncoderSetStencilReference = _lib.wgpuRenderPassEncoderSetStencilReference
_c_wgpuRenderPassEncoderSetVertexBuffer = _lib.wgpuRenderPassEncoderSetVertexBuffer
_c_wgpuRenderPassEncoderSetViewport = _lib.wgpuRenderPassEncoderSetViewport
_c_wgpuRenderPipelineGetBindGroupLayout = _lib.wgpuRenderPipelineGetBindGroupLayout
_c_wgpuTextureDestroy = _lib.wgpuTextureDestroy


__all__ = [
    'GPUAdapter',
    'GPUBindGroup',
    'GPUBindGroupLayout',
    'GPUBindingCommandsMixin',
    'GPUBuffer',
    'GPUCommandBuffer',
    'GPUCommandEncoder',
    'GPUCommandsMixin',
    'GPUComputePassEncoder',
    'GPUComputePipeline',
    'GPUDebugCommandsMixin',
    'GPUDevice',
    'GPUPipelineBase',
    'GPUPipelineLayout',
    'GPUQuerySet',
    'GPUQueue',
    'GPURenderBundle',
    'GPURenderBundleEncoder',
    'GPURenderCommandsMixin',
    'GPURenderPassEncoder',
    'GPURenderPipeline',
    'GPUSampler',
    'GPUShaderModule',
    'GPUTexture',
    'GPUTextureView',
]



class GPUAdapter(GPUHandle):
    """GPUAdapter -- see the WebGPU specification."""
    _spec_name = 'adapter'

    def request_device_async(self, *, label: str = "", required_features: Sequence[enums.FeatureNameEnum] = (), required_limits: dict[str, int | None] = None, default_queue: structs.QueueDescriptorStruct | None = None) -> GPUDevice:
        """GPUAdapter.requestDevice -- see the WebGPU specification."""
        return self._promise(self._call_desc('request_device', {'label': label, 'required_features': required_features, 'required_limits': required_limits, 'default_queue': default_queue}))

    def request_device_sync(self, *, label: str = "", required_features: Sequence[enums.FeatureNameEnum] = (), required_limits: dict[str, int | None] = None, default_queue: structs.QueueDescriptorStruct | None = None) -> GPUDevice:
        """GPUAdapter.requestDevice -- see the WebGPU specification."""
        return self._await(self._call_desc('request_device', {'label': label, 'required_features': required_features, 'required_limits': required_limits, 'default_queue': default_queue}))

    request_device = _ov.deprecated_sync_or_async('request_device')

    features = _ov.adapter_features

    limits = _ov.adapter_limits

    info = _ov.adapter_info



class GPUBindGroup(GPUObjectBase):
    """GPUBindGroup -- see the WebGPU specification."""
    _spec_name = 'bind_group'

    pass



class GPUBindGroupLayout(GPUObjectBase):
    """GPUBindGroupLayout -- see the WebGPU specification."""
    _spec_name = 'bind_group_layout'

    pass



class GPUBindingCommandsMixin(Mixin):
    """GPUBindingCommandsMixin -- see the WebGPU specification."""

    set_bind_group = _ov.binding_commands_set_bind_group

    def set_immediates(self, range_offset: int, data: ArrayLike, data_offset: int = 0, data_size: int | None = None) -> None:
        """GPUBindingCommandsMixin.setImmediates -- see the WebGPU specification."""
        _chunk = _slice_data(data, data_offset, data_size)
        return self._call('set_immediates', range_offset, _chunk, _chunk.nbytes)



class GPUBuffer(GPUObjectBase):
    """GPUBuffer -- see the WebGPU specification."""
    _spec_name = 'buffer'

    map_async = _ov.buffer_map_async
    map_sync = _ov.buffer_map_sync
    map = _ov.buffer_map

    get_mapped_range = _ov.buffer_get_mapped_range

    unmap = _ov.buffer_unmap

    def destroy(self) -> None:
        """GPUBuffer.destroy -- see the WebGPU specification."""
        return _c_wgpuBufferDestroy(self._handle)

    @property
    def size(self) -> int:
        """GPUBuffer.size"""
        return self._get_cached('get_size')

    @property
    def usage(self) -> int:
        """GPUBuffer.usage"""
        return self._get_cached('get_usage')

    map_state = _ov.buffer_map_state



class GPUCommandBuffer(GPUObjectBase):
    """GPUCommandBuffer -- see the WebGPU specification."""
    _spec_name = 'command_buffer'

    pass



class GPUCommandsMixin(Mixin):
    """GPUCommandsMixin -- see the WebGPU specification."""

    pass



class GPUDebugCommandsMixin(Mixin):
    """GPUDebugCommandsMixin -- see the WebGPU specification."""

    def push_debug_group(self, group_label: str) -> None:
        """GPUDebugCommandsMixin.pushDebugGroup -- see the WebGPU specification."""
        return self._call('push_debug_group', group_label)

    def pop_debug_group(self) -> None:
        """GPUDebugCommandsMixin.popDebugGroup -- see the WebGPU specification."""
        return self._call('pop_debug_group')

    def insert_debug_marker(self, marker_label: str) -> None:
        """GPUDebugCommandsMixin.insertDebugMarker -- see the WebGPU specification."""
        return self._call('insert_debug_marker', marker_label)



class GPUCommandEncoder(GPUCommandsMixin, GPUDebugCommandsMixin, GPUObjectBase):
    """GPUCommandEncoder -- see the WebGPU specification."""
    _spec_name = 'command_encoder'

    def begin_render_pass(self, *, label: str = "", color_attachments: Sequence[structs.RenderPassColorAttachmentStruct], depth_stencil_attachment: structs.RenderPassDepthStencilAttachmentStruct | None = None, occlusion_query_set: GPUQuerySet | None = None, timestamp_writes: structs.RenderPassTimestampWritesStruct | None = None, max_draw_count: int = 50000000) -> GPURenderPassEncoder:
        """GPUCommandEncoder.beginRenderPass -- see the WebGPU specification."""
        return self._call_desc('begin_render_pass', {'label': label, 'color_attachments': color_attachments, 'depth_stencil_attachment': depth_stencil_attachment, 'occlusion_query_set': occlusion_query_set, 'timestamp_writes': timestamp_writes, 'max_draw_count': max_draw_count})

    def begin_compute_pass(self, *, label: str = "", timestamp_writes: structs.ComputePassTimestampWritesStruct | None = None) -> GPUComputePassEncoder:
        """GPUCommandEncoder.beginComputePass -- see the WebGPU specification."""
        return self._call_desc('begin_compute_pass', {'label': label, 'timestamp_writes': timestamp_writes})

    def copy_buffer_to_buffer(self, source: GPUBuffer, source_offset: int, destination: GPUBuffer, destination_offset: int, size: int | None = None) -> None:
        """GPUCommandEncoder.copyBufferToBuffer -- see the WebGPU specification."""
        return _c_wgpuCommandEncoderCopyBufferToBuffer(self._handle, source._handle, source_offset, destination._handle, destination_offset, (_WHOLE64 if not size else size))

    def copy_buffer_to_texture(self, source: structs.TexelCopyBufferInfoStruct, destination: structs.TexelCopyTextureInfoStruct, copy_size: tuple[int, int, int] | structs.Extent3DStruct) -> None:
        """GPUCommandEncoder.copyBufferToTexture -- see the WebGPU specification."""
        return self._call('copy_buffer_to_texture', source, destination, copy_size)

    def copy_texture_to_buffer(self, source: structs.TexelCopyTextureInfoStruct, destination: structs.TexelCopyBufferInfoStruct, copy_size: tuple[int, int, int] | structs.Extent3DStruct) -> None:
        """GPUCommandEncoder.copyTextureToBuffer -- see the WebGPU specification."""
        return self._call('copy_texture_to_buffer', source, destination, copy_size)

    def copy_texture_to_texture(self, source: structs.TexelCopyTextureInfoStruct, destination: structs.TexelCopyTextureInfoStruct, copy_size: tuple[int, int, int] | structs.Extent3DStruct) -> None:
        """GPUCommandEncoder.copyTextureToTexture -- see the WebGPU specification."""
        return self._call('copy_texture_to_texture', source, destination, copy_size)

    def clear_buffer(self, buffer: GPUBuffer, offset: int = 0, size: int | None = None) -> None:
        """GPUCommandEncoder.clearBuffer -- see the WebGPU specification."""
        return _c_wgpuCommandEncoderClearBuffer(self._handle, buffer._handle, offset, (_WHOLE64 if not size else size))

    def resolve_query_set(self, query_set: GPUQuerySet, first_query: int, query_count: int, destination: GPUBuffer, destination_offset: int) -> None:
        """GPUCommandEncoder.resolveQuerySet -- see the WebGPU specification."""
        return _c_wgpuCommandEncoderResolveQuerySet(self._handle, query_set._handle, first_query, query_count, destination._handle, destination_offset)

    def finish(self, *, label: str = "") -> GPUCommandBuffer:
        """GPUCommandEncoder.finish -- see the WebGPU specification."""
        _d = _ffi.new("WGPUCommandBufferDescriptor *")
        if label is not None:
            _s_label = _ffi.new("char[]", label.encode())
            _d.label.data = _s_label
            _d.label.length = len(_s_label) - 1
        else:
            _d.label.length = _STRLEN
        _r = _new_object(GPUCommandBuffer, _c_wgpuCommandEncoderFinish(self._handle, _d), self._parent, label)
        _raise_if_error()
        return _r

    def pop_debug_group(self) -> None:
        """GPUCommandEncoder.popDebugGroup -- see the WebGPU specification."""
        return _c_wgpuCommandEncoderPopDebugGroup(self._handle)



class GPUComputePassEncoder(GPUCommandsMixin, GPUDebugCommandsMixin, GPUBindingCommandsMixin, GPUObjectBase):
    """GPUComputePassEncoder -- see the WebGPU specification."""
    _spec_name = 'compute_pass_encoder'

    def set_pipeline(self, pipeline: GPUComputePipeline) -> None:
        """GPUComputePassEncoder.setPipeline -- see the WebGPU specification."""
        return _c_wgpuComputePassEncoderSetPipeline(self._handle, pipeline._handle)

    def dispatch_workgroups(self, workgroup_count_x: int, workgroup_count_y: int = 1, workgroup_count_z: int = 1) -> None:
        """GPUComputePassEncoder.dispatchWorkgroups -- see the WebGPU specification."""
        return _c_wgpuComputePassEncoderDispatchWorkgroups(self._handle, workgroup_count_x, workgroup_count_y, workgroup_count_z)

    def dispatch_workgroups_indirect(self, indirect_buffer: GPUBuffer, indirect_offset: int) -> None:
        """GPUComputePassEncoder.dispatchWorkgroupsIndirect -- see the WebGPU specification."""
        return _c_wgpuComputePassEncoderDispatchWorkgroupsIndirect(self._handle, indirect_buffer._handle, indirect_offset)

    def end(self) -> None:
        """GPUComputePassEncoder.end -- see the WebGPU specification."""
        return _c_wgpuComputePassEncoderEnd(self._handle)

    def pop_debug_group(self) -> None:
        """GPUComputePassEncoder.popDebugGroup -- see the WebGPU specification."""
        return _c_wgpuComputePassEncoderPopDebugGroup(self._handle)

    _c_set_bind_group = staticmethod(_c_wgpuComputePassEncoderSetBindGroup)



class GPUPipelineBase(Mixin):
    """GPUPipelineBase -- see the WebGPU specification."""

    def get_bind_group_layout(self, index: int) -> GPUBindGroupLayout:
        """GPUPipelineBase.getBindGroupLayout -- see the WebGPU specification."""
        return self._call('get_bind_group_layout', index)



class GPUComputePipeline(GPUPipelineBase, GPUObjectBase):
    """GPUComputePipeline -- see the WebGPU specification."""
    _spec_name = 'compute_pipeline'

    def get_bind_group_layout(self, index: int) -> GPUBindGroupLayout:
        """GPUComputePipeline.getBindGroupLayout -- see the WebGPU specification."""
        return _new_object(GPUBindGroupLayout, _c_wgpuComputePipelineGetBindGroupLayout(self._handle, index), self)



class GPUDevice(GPUObjectBase):
    """GPUDevice -- see the WebGPU specification."""
    _spec_name = 'device'

    def destroy(self) -> None:
        """GPUDevice.destroy -- see the WebGPU specification."""
        return _c_wgpuDeviceDestroy(self._handle)

    def create_buffer(self, *, label: str = "", size: int, usage: flags.BufferUsageFlags, mapped_at_creation: bool = False) -> GPUBuffer:
        """GPUDevice.createBuffer -- see the WebGPU specification."""
        _d = _ffi.new("WGPUBufferDescriptor *")
        if label is not None:
            _s_label = _ffi.new("char[]", label.encode())
            _d.label.data = _s_label
            _d.label.length = len(_s_label) - 1
        else:
            _d.label.length = _STRLEN
        if usage is not None:
            _d.usage = _F_buffer_usage[usage]
        else:
            raise InvalidValueError("WGPUBufferDescriptor: 'usage' is required")
        if size is not None:
            _d.size = size
        else:
            raise InvalidValueError("WGPUBufferDescriptor: 'size' is required")
        if mapped_at_creation is not None:
            _d.mappedAtCreation = mapped_at_creation
        _r = _new_object(GPUBuffer, _c_wgpuDeviceCreateBuffer(self._handle, _d), self, label)
        _raise_if_error()
        return _r

    def create_texture(self, *, label: str = "", size: tuple[int, int, int] | structs.Extent3DStruct, mip_level_count: int = 1, sample_count: int = 1, dimension: enums.TextureDimensionEnum = "2d", format: enums.TextureFormatEnum, usage: flags.TextureUsageFlags, view_formats: Sequence[enums.TextureFormatEnum] = (), texture_binding_view_dimension: enums.TextureViewDimensionEnum | None = None) -> GPUTexture:
        """GPUDevice.createTexture -- see the WebGPU specification."""
        return self._call_desc('create_texture', {'label': label, 'size': size, 'mip_level_count': mip_level_count, 'sample_count': sample_count, 'dimension': dimension, 'format': format, 'usage': usage, 'view_formats': view_formats, 'texture_binding_view_dimension': texture_binding_view_dimension})

    def create_sampler(self, *, label: str = "", address_mode_u: enums.AddressModeEnum = "clamp-to-edge", address_mode_v: enums.AddressModeEnum = "clamp-to-edge", address_mode_w: enums.AddressModeEnum = "clamp-to-edge", mag_filter: enums.FilterModeEnum = "nearest", min_filter: enums.FilterModeEnum = "nearest", mipmap_filter: enums.MipmapFilterModeEnum = "nearest", lod_min_clamp: float = 0, lod_max_clamp: float = 32, compare: enums.CompareFunctionEnum | None = None, max_anisotropy: int = 1) -> GPUSampler:
        """GPUDevice.createSampler -- see the WebGPU specification."""
        _d = _ffi.new("WGPUSamplerDescriptor *")
        if label is not None:
            _s_label = _ffi.new("char[]", label.encode())
            _d.label.data = _s_label
            _d.label.length = len(_s_label) - 1
        else:
            _d.label.length = _STRLEN
        if address_mode_u is not None:
            _d.addressModeU = _E_address_mode[address_mode_u]
        if address_mode_v is not None:
            _d.addressModeV = _E_address_mode[address_mode_v]
        if address_mode_w is not None:
            _d.addressModeW = _E_address_mode[address_mode_w]
        if mag_filter is not None:
            _d.magFilter = _E_filter_mode[mag_filter]
        if min_filter is not None:
            _d.minFilter = _E_filter_mode[min_filter]
        if mipmap_filter is not None:
            _d.mipmapFilter = _E_mipmap_filter_mode[mipmap_filter]
        if lod_min_clamp is not None:
            _d.lodMinClamp = lod_min_clamp
        if lod_max_clamp is not None:
            _d.lodMaxClamp = lod_max_clamp
        else:
            _d.lodMaxClamp = 32
        if compare is not None:
            _d.compare = _E_compare_function[compare]
        if max_anisotropy is not None:
            _d.maxAnisotropy = max_anisotropy
        else:
            _d.maxAnisotropy = 1
        _r = _new_object(GPUSampler, _c_wgpuDeviceCreateSampler(self._handle, _d), self, label)
        _raise_if_error()
        return _r

    def create_bind_group_layout(self, *, label: str = "", entries: Sequence[structs.BindGroupLayoutEntryStruct]) -> GPUBindGroupLayout:
        """GPUDevice.createBindGroupLayout -- see the WebGPU specification."""
        return self._call_desc('create_bind_group_layout', {'label': label, 'entries': entries})

    def create_pipeline_layout(self, *, label: str = "", bind_group_layouts: Sequence[GPUBindGroupLayout], immediate_size: int = 0) -> GPUPipelineLayout:
        """GPUDevice.createPipelineLayout -- see the WebGPU specification."""
        return self._call_desc('create_pipeline_layout', {'label': label, 'bind_group_layouts': bind_group_layouts, 'immediate_size': immediate_size})

    def create_bind_group(self, *, label: str = "", layout: GPUBindGroupLayout, entries: Sequence[structs.BindGroupEntryStruct]) -> GPUBindGroup:
        """GPUDevice.createBindGroup -- see the WebGPU specification."""
        return self._call_desc('create_bind_group', {'label': label, 'layout': layout, 'entries': entries})

    def create_shader_module(self, *, label: str = "", code: str, compilation_hints: Sequence[structs.ShaderModuleCompilationHintStruct] = ()) -> GPUShaderModule:
        """GPUDevice.createShaderModule -- see the WebGPU specification."""
        return self._call_desc('create_shader_module', {'label': label, 'code': code, 'compilation_hints': compilation_hints})

    def create_compute_pipeline(self, *, label: str = "", layout: GPUPipelineLayout | enums.AutoLayoutModeEnum, compute: structs.ProgrammableStageStruct) -> GPUComputePipeline:
        """GPUDevice.createComputePipeline -- see the WebGPU specification."""
        return self._call_desc('create_compute_pipeline', {'label': label, 'layout': layout, 'compute': compute})

    def create_render_pipeline(self, *, label: str = "", layout: GPUPipelineLayout | enums.AutoLayoutModeEnum, vertex: structs.VertexStateStruct, primitive: structs.PrimitiveStateStruct | None = None, depth_stencil: structs.DepthStencilStateStruct | None = None, multisample: structs.MultisampleStateStruct | None = None, fragment: structs.FragmentStateStruct | None = None) -> GPURenderPipeline:
        """GPUDevice.createRenderPipeline -- see the WebGPU specification."""
        return self._call_desc('create_render_pipeline', {'label': label, 'layout': layout, 'vertex': vertex, 'primitive': primitive, 'depth_stencil': depth_stencil, 'multisample': multisample, 'fragment': fragment})

    def create_compute_pipeline_async(self, *, label: str = "", layout: GPUPipelineLayout | enums.AutoLayoutModeEnum, compute: structs.ProgrammableStageStruct) -> GPUComputePipeline:
        """GPUDevice.createComputePipelineAsync -- see the WebGPU specification."""
        return self._promise(_unimplemented('wgpuDeviceCreateComputePipelineAsync'))

    def create_render_pipeline_async(self, *, label: str = "", layout: GPUPipelineLayout | enums.AutoLayoutModeEnum, vertex: structs.VertexStateStruct, primitive: structs.PrimitiveStateStruct | None = None, depth_stencil: structs.DepthStencilStateStruct | None = None, multisample: structs.MultisampleStateStruct | None = None, fragment: structs.FragmentStateStruct | None = None) -> GPURenderPipeline:
        """GPUDevice.createRenderPipelineAsync -- see the WebGPU specification."""
        return self._promise(_unimplemented('wgpuDeviceCreateRenderPipelineAsync'))

    def create_command_encoder(self, *, label: str = "") -> GPUCommandEncoder:
        """GPUDevice.createCommandEncoder -- see the WebGPU specification."""
        _d = _ffi.new("WGPUCommandEncoderDescriptor *")
        if label is not None:
            _s_label = _ffi.new("char[]", label.encode())
            _d.label.data = _s_label
            _d.label.length = len(_s_label) - 1
        else:
            _d.label.length = _STRLEN
        _r = _new_object(GPUCommandEncoder, _c_wgpuDeviceCreateCommandEncoder(self._handle, _d), self, label)
        _raise_if_error()
        return _r

    def create_render_bundle_encoder(self, *, label: str = "", color_formats: Sequence[enums.TextureFormatEnum], depth_stencil_format: enums.TextureFormatEnum | None = None, sample_count: int = 1, depth_read_only: bool = False, stencil_read_only: bool = False) -> GPURenderBundleEncoder:
        """GPUDevice.createRenderBundleEncoder -- see the WebGPU specification."""
        return self._call_desc('create_render_bundle_encoder', {'label': label, 'color_formats': color_formats, 'depth_stencil_format': depth_stencil_format, 'sample_count': sample_count, 'depth_read_only': depth_read_only, 'stencil_read_only': stencil_read_only})

    def create_query_set(self, *, label: str = "", type: enums.QueryTypeEnum, count: int) -> GPUQuerySet:
        """GPUDevice.createQuerySet -- see the WebGPU specification."""
        _d = _ffi.new("WGPUQuerySetDescriptor *")
        if label is not None:
            _s_label = _ffi.new("char[]", label.encode())
            _d.label.data = _s_label
            _d.label.length = len(_s_label) - 1
        else:
            _d.label.length = _STRLEN
        if type is not None:
            _d.type = _E_query_type[type]
        else:
            raise InvalidValueError("WGPUQuerySetDescriptor: 'type' is required")
        if count is not None:
            _d.count = count
        else:
            raise InvalidValueError("WGPUQuerySetDescriptor: 'count' is required")
        _r = _new_object(GPUQuerySet, _c_wgpuDeviceCreateQuerySet(self._handle, _d), self, label)
        _raise_if_error()
        return _r

    def push_error_scope(self, filter: enums.ErrorFilterEnum) -> None:
        """GPUDevice.pushErrorScope -- see the WebGPU specification."""
        return _c_wgpuDevicePushErrorScope(self._handle, _E_error_filter[filter])

    def pop_error_scope_async(self) -> GPUError:
        """GPUDevice.popErrorScope -- see the WebGPU specification."""
        return self._promise(self._call('pop_error_scope'))

    def pop_error_scope_sync(self) -> GPUError:
        """GPUDevice.popErrorScope -- see the WebGPU specification."""
        return self._await(self._call('pop_error_scope'))

    pop_error_scope = _ov.deprecated_sync_or_async('pop_error_scope')

    features = _ov.device_features

    limits = _ov.device_limits

    adapter_info = _ov.device_adapter_info

    queue = _ov.device_queue

    lost = _ov.device_lost

    onuncapturederror = _ov.device_onuncapturederror



class GPUPipelineLayout(GPUObjectBase):
    """GPUPipelineLayout -- see the WebGPU specification."""
    _spec_name = 'pipeline_layout'

    pass



class GPUQuerySet(GPUObjectBase):
    """GPUQuerySet -- see the WebGPU specification."""
    _spec_name = 'query_set'

    def destroy(self) -> None:
        """GPUQuerySet.destroy -- see the WebGPU specification."""
        return _ov.destroy_consuming(self, _c_wgpuQuerySetDestroy)

    @property
    def type(self) -> enums.QueryTypeEnum:
        """GPUQuerySet.type"""
        return self._get_cached('get_type')

    @property
    def count(self) -> int:
        """GPUQuerySet.count"""
        return self._get_cached('get_count')



class GPUQueue(GPUObjectBase):
    """GPUQueue -- see the WebGPU specification."""
    _spec_name = 'queue'

    def submit(self, command_buffers: Sequence[GPUCommandBuffer]) -> None:
        """GPUQueue.submit -- see the WebGPU specification."""
        _a_command_buffers = [_o._handle for _o in command_buffers]
        _r = _c_wgpuQueueSubmit(self._handle, len(_a_command_buffers), (_ffi.new("struct WGPUCommandBufferImpl *[]", _a_command_buffers) if _a_command_buffers else _NULL))
        _raise_if_error()
        return _r

    def on_submitted_work_done_async(self) -> None:
        """GPUQueue.onSubmittedWorkDone -- see the WebGPU specification."""
        return self._promise(self._call('on_submitted_work_done'))

    def on_submitted_work_done_sync(self) -> None:
        """GPUQueue.onSubmittedWorkDone -- see the WebGPU specification."""
        return self._await(self._call('on_submitted_work_done'))

    on_submitted_work_done = _ov.deprecated_sync_or_async('on_submitted_work_done')

    def write_buffer(self, buffer: GPUBuffer, buffer_offset: int, data: ArrayLike, data_offset: int = 0, size: int | None = None) -> None:
        """GPUQueue.writeBuffer -- see the WebGPU specification."""
        _chunk = _slice_data(data, data_offset, size)
        return self._call('write_buffer', buffer, buffer_offset, _chunk, _chunk.nbytes)

    def write_texture(self, destination: structs.TexelCopyTextureInfoStruct, data: ArrayLike, data_layout: structs.TexelCopyBufferLayoutStruct, size: tuple[int, int, int] | structs.Extent3DStruct) -> None:
        """GPUQueue.writeTexture -- see the WebGPU specification."""
        _chunk = _slice_data(data, 0, None)
        return self._call('write_texture', destination, _chunk, _chunk.nbytes, data_layout, size)



class GPURenderBundle(GPUObjectBase):
    """GPURenderBundle -- see the WebGPU specification."""
    _spec_name = 'render_bundle'

    pass



class GPURenderCommandsMixin(Mixin):
    """GPURenderCommandsMixin -- see the WebGPU specification."""

    def set_pipeline(self, pipeline: GPURenderPipeline) -> None:
        """GPURenderCommandsMixin.setPipeline -- see the WebGPU specification."""
        return self._call('set_pipeline', pipeline)

    def set_index_buffer(self, buffer: GPUBuffer, index_format: enums.IndexFormatEnum, offset: int = 0, size: int | None = None) -> None:
        """GPURenderCommandsMixin.setIndexBuffer -- see the WebGPU specification."""
        return self._call('set_index_buffer', buffer, index_format, offset, size)

    def set_vertex_buffer(self, slot: int, buffer: GPUBuffer, offset: int = 0, size: int | None = None) -> None:
        """GPURenderCommandsMixin.setVertexBuffer -- see the WebGPU specification."""
        return self._call('set_vertex_buffer', slot, buffer, offset, size)

    def draw(self, vertex_count: int, instance_count: int = 1, first_vertex: int = 0, first_instance: int = 0) -> None:
        """GPURenderCommandsMixin.draw -- see the WebGPU specification."""
        return self._call('draw', vertex_count, instance_count, first_vertex, first_instance)

    def draw_indexed(self, index_count: int, instance_count: int = 1, first_index: int = 0, base_vertex: int = 0, first_instance: int = 0) -> None:
        """GPURenderCommandsMixin.drawIndexed -- see the WebGPU specification."""
        return self._call('draw_indexed', index_count, instance_count, first_index, base_vertex, first_instance)

    def draw_indirect(self, indirect_buffer: GPUBuffer, indirect_offset: int) -> None:
        """GPURenderCommandsMixin.drawIndirect -- see the WebGPU specification."""
        return self._call('draw_indirect', indirect_buffer, indirect_offset)

    def draw_indexed_indirect(self, indirect_buffer: GPUBuffer, indirect_offset: int) -> None:
        """GPURenderCommandsMixin.drawIndexedIndirect -- see the WebGPU specification."""
        return self._call('draw_indexed_indirect', indirect_buffer, indirect_offset)



class GPURenderBundleEncoder(GPUCommandsMixin, GPUDebugCommandsMixin, GPUBindingCommandsMixin, GPURenderCommandsMixin, GPUObjectBase):
    """GPURenderBundleEncoder -- see the WebGPU specification."""
    _spec_name = 'render_bundle_encoder'

    def finish(self, *, label: str = "") -> GPURenderBundle:
        """GPURenderBundleEncoder.finish -- see the WebGPU specification."""
        _d = _ffi.new("WGPURenderBundleDescriptor *")
        if label is not None:
            _s_label = _ffi.new("char[]", label.encode())
            _d.label.data = _s_label
            _d.label.length = len(_s_label) - 1
        else:
            _d.label.length = _STRLEN
        _r = _new_object(GPURenderBundle, _c_wgpuRenderBundleEncoderFinish(self._handle, _d), self._parent, label)
        _raise_if_error()
        return _r

    def pop_debug_group(self) -> None:
        """GPURenderBundleEncoder.popDebugGroup -- see the WebGPU specification."""
        return _c_wgpuRenderBundleEncoderPopDebugGroup(self._handle)

    _c_set_bind_group = staticmethod(_c_wgpuRenderBundleEncoderSetBindGroup)

    def set_pipeline(self, pipeline: GPURenderPipeline) -> None:
        """GPURenderBundleEncoder.setPipeline -- see the WebGPU specification."""
        return _c_wgpuRenderBundleEncoderSetPipeline(self._handle, pipeline._handle)

    def set_index_buffer(self, buffer: GPUBuffer, index_format: enums.IndexFormatEnum, offset: int = 0, size: int | None = None) -> None:
        """GPURenderBundleEncoder.setIndexBuffer -- see the WebGPU specification."""
        return _c_wgpuRenderBundleEncoderSetIndexBuffer(self._handle, buffer._handle, _E_index_format[index_format], offset, (_WHOLE64 if not size else size))

    def set_vertex_buffer(self, slot: int, buffer: GPUBuffer, offset: int = 0, size: int | None = None) -> None:
        """GPURenderBundleEncoder.setVertexBuffer -- see the WebGPU specification."""
        return _c_wgpuRenderBundleEncoderSetVertexBuffer(self._handle, slot, (buffer._handle if buffer is not None else _NULL), offset, (_WHOLE64 if not size else size))

    def draw(self, vertex_count: int, instance_count: int = 1, first_vertex: int = 0, first_instance: int = 0) -> None:
        """GPURenderBundleEncoder.draw -- see the WebGPU specification."""
        return _c_wgpuRenderBundleEncoderDraw(self._handle, vertex_count, instance_count, first_vertex, first_instance)

    def draw_indexed(self, index_count: int, instance_count: int = 1, first_index: int = 0, base_vertex: int = 0, first_instance: int = 0) -> None:
        """GPURenderBundleEncoder.drawIndexed -- see the WebGPU specification."""
        return _c_wgpuRenderBundleEncoderDrawIndexed(self._handle, index_count, instance_count, first_index, base_vertex, first_instance)

    def draw_indirect(self, indirect_buffer: GPUBuffer, indirect_offset: int) -> None:
        """GPURenderBundleEncoder.drawIndirect -- see the WebGPU specification."""
        return _c_wgpuRenderBundleEncoderDrawIndirect(self._handle, indirect_buffer._handle, indirect_offset)

    def draw_indexed_indirect(self, indirect_buffer: GPUBuffer, indirect_offset: int) -> None:
        """GPURenderBundleEncoder.drawIndexedIndirect -- see the WebGPU specification."""
        return _c_wgpuRenderBundleEncoderDrawIndexedIndirect(self._handle, indirect_buffer._handle, indirect_offset)



class GPURenderPassEncoder(GPUCommandsMixin, GPUDebugCommandsMixin, GPUBindingCommandsMixin, GPURenderCommandsMixin, GPUObjectBase):
    """GPURenderPassEncoder -- see the WebGPU specification."""
    _spec_name = 'render_pass_encoder'

    def set_viewport(self, x: float, y: float, width: float, height: float, min_depth: float, max_depth: float) -> None:
        """GPURenderPassEncoder.setViewport -- see the WebGPU specification."""
        return _c_wgpuRenderPassEncoderSetViewport(self._handle, x, y, width, height, min_depth, max_depth)

    def set_scissor_rect(self, x: int, y: int, width: int, height: int) -> None:
        """GPURenderPassEncoder.setScissorRect -- see the WebGPU specification."""
        return _c_wgpuRenderPassEncoderSetScissorRect(self._handle, x, y, width, height)

    def set_blend_constant(self, color: tuple[float, float, float, float] | structs.ColorStruct) -> None:
        """GPURenderPassEncoder.setBlendConstant -- see the WebGPU specification."""
        return self._call('set_blend_constant', color)

    def set_stencil_reference(self, reference: int) -> None:
        """GPURenderPassEncoder.setStencilReference -- see the WebGPU specification."""
        return _c_wgpuRenderPassEncoderSetStencilReference(self._handle, reference)

    def begin_occlusion_query(self, query_index: int) -> None:
        """GPURenderPassEncoder.beginOcclusionQuery -- see the WebGPU specification."""
        return _c_wgpuRenderPassEncoderBeginOcclusionQuery(self._handle, query_index)

    def end_occlusion_query(self) -> None:
        """GPURenderPassEncoder.endOcclusionQuery -- see the WebGPU specification."""
        return _c_wgpuRenderPassEncoderEndOcclusionQuery(self._handle)

    def execute_bundles(self, bundles: Sequence[GPURenderBundle]) -> None:
        """GPURenderPassEncoder.executeBundles -- see the WebGPU specification."""
        _a_bundles = [_o._handle for _o in bundles]
        _r = _c_wgpuRenderPassEncoderExecuteBundles(self._handle, len(_a_bundles), (_ffi.new("struct WGPURenderBundleImpl *[]", _a_bundles) if _a_bundles else _NULL))
        _raise_if_error()
        return _r

    def end(self) -> None:
        """GPURenderPassEncoder.end -- see the WebGPU specification."""
        return _c_wgpuRenderPassEncoderEnd(self._handle)

    def pop_debug_group(self) -> None:
        """GPURenderPassEncoder.popDebugGroup -- see the WebGPU specification."""
        return _c_wgpuRenderPassEncoderPopDebugGroup(self._handle)

    _c_set_bind_group = staticmethod(_c_wgpuRenderPassEncoderSetBindGroup)

    def set_pipeline(self, pipeline: GPURenderPipeline) -> None:
        """GPURenderPassEncoder.setPipeline -- see the WebGPU specification."""
        return _c_wgpuRenderPassEncoderSetPipeline(self._handle, pipeline._handle)

    def set_index_buffer(self, buffer: GPUBuffer, index_format: enums.IndexFormatEnum, offset: int = 0, size: int | None = None) -> None:
        """GPURenderPassEncoder.setIndexBuffer -- see the WebGPU specification."""
        return _c_wgpuRenderPassEncoderSetIndexBuffer(self._handle, buffer._handle, _E_index_format[index_format], offset, (_WHOLE64 if not size else size))

    def set_vertex_buffer(self, slot: int, buffer: GPUBuffer, offset: int = 0, size: int | None = None) -> None:
        """GPURenderPassEncoder.setVertexBuffer -- see the WebGPU specification."""
        return _c_wgpuRenderPassEncoderSetVertexBuffer(self._handle, slot, (buffer._handle if buffer is not None else _NULL), offset, (_WHOLE64 if not size else size))

    def draw(self, vertex_count: int, instance_count: int = 1, first_vertex: int = 0, first_instance: int = 0) -> None:
        """GPURenderPassEncoder.draw -- see the WebGPU specification."""
        return _c_wgpuRenderPassEncoderDraw(self._handle, vertex_count, instance_count, first_vertex, first_instance)

    def draw_indexed(self, index_count: int, instance_count: int = 1, first_index: int = 0, base_vertex: int = 0, first_instance: int = 0) -> None:
        """GPURenderPassEncoder.drawIndexed -- see the WebGPU specification."""
        return _c_wgpuRenderPassEncoderDrawIndexed(self._handle, index_count, instance_count, first_index, base_vertex, first_instance)

    def draw_indirect(self, indirect_buffer: GPUBuffer, indirect_offset: int) -> None:
        """GPURenderPassEncoder.drawIndirect -- see the WebGPU specification."""
        return _c_wgpuRenderPassEncoderDrawIndirect(self._handle, indirect_buffer._handle, indirect_offset)

    def draw_indexed_indirect(self, indirect_buffer: GPUBuffer, indirect_offset: int) -> None:
        """GPURenderPassEncoder.drawIndexedIndirect -- see the WebGPU specification."""
        return _c_wgpuRenderPassEncoderDrawIndexedIndirect(self._handle, indirect_buffer._handle, indirect_offset)



class GPURenderPipeline(GPUPipelineBase, GPUObjectBase):
    """GPURenderPipeline -- see the WebGPU specification."""
    _spec_name = 'render_pipeline'

    def get_bind_group_layout(self, index: int) -> GPUBindGroupLayout:
        """GPURenderPipeline.getBindGroupLayout -- see the WebGPU specification."""
        return _new_object(GPUBindGroupLayout, _c_wgpuRenderPipelineGetBindGroupLayout(self._handle, index), self)



class GPUSampler(GPUObjectBase):
    """GPUSampler -- see the WebGPU specification."""
    _spec_name = 'sampler'

    pass



class GPUShaderModule(GPUObjectBase):
    """GPUShaderModule -- see the WebGPU specification."""
    _spec_name = 'shader_module'

    get_compilation_info_async = _ov.shader_module_get_compilation_info_async
    get_compilation_info_sync = _ov.shader_module_get_compilation_info_sync
    get_compilation_info = _ov.shader_module_get_compilation_info



class GPUTexture(GPUObjectBase):
    """GPUTexture -- see the WebGPU specification."""
    _spec_name = 'texture'

    def create_view(self, *, label: str = "", format: enums.TextureFormatEnum | None = None, dimension: enums.TextureViewDimensionEnum | None = None, usage: flags.TextureUsageFlags = 0, aspect: enums.TextureAspectEnum = "all", base_mip_level: int = 0, mip_level_count: int | None = None, base_array_layer: int = 0, array_layer_count: int | None = None, swizzle: str = "rgba") -> GPUTextureView:
        """GPUTexture.createView -- see the WebGPU specification."""
        return self._call_desc('create_view', {'label': label, 'format': format, 'dimension': dimension, 'usage': usage, 'aspect': aspect, 'base_mip_level': base_mip_level, 'mip_level_count': mip_level_count, 'base_array_layer': base_array_layer, 'array_layer_count': array_layer_count, 'swizzle': swizzle})

    def destroy(self) -> None:
        """GPUTexture.destroy -- see the WebGPU specification."""
        return _c_wgpuTextureDestroy(self._handle)

    @property
    def width(self) -> int:
        """GPUTexture.width"""
        return self._get_cached('get_width')

    @property
    def height(self) -> int:
        """GPUTexture.height"""
        return self._get_cached('get_height')

    @property
    def depth_or_array_layers(self) -> int:
        """GPUTexture.depthOrArrayLayers"""
        return self._get_cached('get_depth_or_array_layers')

    @property
    def mip_level_count(self) -> int:
        """GPUTexture.mipLevelCount"""
        return self._get_cached('get_mip_level_count')

    @property
    def sample_count(self) -> int:
        """GPUTexture.sampleCount"""
        return self._get_cached('get_sample_count')

    @property
    def dimension(self) -> enums.TextureDimensionEnum:
        """GPUTexture.dimension"""
        return self._get_cached('get_dimension')

    @property
    def format(self) -> enums.TextureFormatEnum:
        """GPUTexture.format"""
        return self._get_cached('get_format')

    @property
    def usage(self) -> int:
        """GPUTexture.usage"""
        return self._get_cached('get_usage')

    texture_binding_view_dimension = _ov.texture_texture_binding_view_dimension



class GPUTextureView(GPUObjectBase):
    """GPUTextureView -- see the WebGPU specification."""
    _spec_name = 'texture_view'

    pass
