# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Public API surface, generated from bindgen/resources/webgpu.idl (the W3C
# WebGPU Web IDL) and cross-referenced against the wgpu-native C spec. Re-run
# the generator after updating either spec.

"""The public ``GPU*`` classes."""

from __future__ import annotations

from collections.abc import Sequence

from wgpu._api import overrides as _ov
from wgpu._api.base import GPUObjectBase, Mixin
from wgpu._api.types import ArrayLike, CanvasLike
from wgpu._generated import apienums as enums
from wgpu._generated import apiflags as flags
from wgpu._generated import apistructs as structs

__all__ = [
    'GPU',
    'GPUAdapter',
    'GPUAdapterInfo',
    'GPUBindGroup',
    'GPUBindGroupLayout',
    'GPUBindingCommandsMixin',
    'GPUBuffer',
    'GPUCanvasContext',
    'GPUCommandBuffer',
    'GPUCommandEncoder',
    'GPUCommandsMixin',
    'GPUCompilationInfo',
    'GPUCompilationMessage',
    'GPUComputePassEncoder',
    'GPUComputePipeline',
    'GPUDebugCommandsMixin',
    'GPUDevice',
    'GPUDeviceLostInfo',
    'GPUError',
    'GPUInternalError',
    'GPUObjectBase',
    'GPUOutOfMemoryError',
    'GPUPipelineBase',
    'GPUPipelineError',
    'GPUPipelineLayout',
    'GPUQuerySet',
    'GPUQueue',
    'GPURenderBundle',
    'GPURenderBundleEncoder',
    'GPURenderCommandsMixin',
    'GPURenderPassEncoder',
    'GPURenderPipeline',
    'GPUSampler',
    'GPUShaderModule',
    'GPUTexture',
    'GPUTextureView',
    'GPUValidationError',
]



class GPUAdapter(GPUObjectBase):
    """GPUAdapter -- see the WebGPU specification."""
    _spec_name = 'adapter'

    def request_device_async(self, *, label: str = "", required_features: Sequence[enums.FeatureNameEnum] = (), required_limits: dict[str, int | None] = None, default_queue: structs.QueueDescriptorStruct | None = None) -> GPUDevice:
        """GPUAdapter.requestDevice -- see the WebGPU specification."""
        return self._promise(self._call_desc('request_device', {'label': label, 'required_features': required_features, 'required_limits': required_limits, 'default_queue': default_queue}))

    def request_device_sync(self, *, label: str = "", required_features: Sequence[enums.FeatureNameEnum] = (), required_limits: dict[str, int | None] = None, default_queue: structs.QueueDescriptorStruct | None = None) -> GPUDevice:
        """GPUAdapter.requestDevice -- see the WebGPU specification."""
        return self._await(self._call_desc('request_device', {'label': label, 'required_features': required_features, 'required_limits': required_limits, 'default_queue': default_queue}))

    request_device = _ov.deprecated_sync_or_async('request_device')

    features = _ov.adapter_features

    limits = _ov.adapter_limits

    info = _ov.adapter_info



class GPUBindGroup(GPUObjectBase):
    """GPUBindGroup -- see the WebGPU specification."""
    _spec_name = 'bind_group'

    pass



class GPUBindGroupLayout(GPUObjectBase):
    """GPUBindGroupLayout -- see the WebGPU specification."""
    _spec_name = 'bind_group_layout'

    pass



class GPUBindingCommandsMixin(Mixin):
    """GPUBindingCommandsMixin -- see the WebGPU specification."""

    pass



class GPUBuffer(GPUObjectBase):
    """GPUBuffer -- see the WebGPU specification."""
    _spec_name = 'buffer'

    def map_async(self, mode: flags.MapModeFlags, offset: int = 0, size: int | None = None) -> None:
        """GPUBuffer.mapAsync -- see the WebGPU specification."""
        return self._promise(self._call('map_async', mode, offset, size))

    def map_sync(self, mode: flags.MapModeFlags, offset: int = 0, size: int | None = None) -> None:
        """GPUBuffer.mapAsync -- see the WebGPU specification."""
        return self._await(self._call('map_async', mode, offset, size))

    map = _ov.deprecated_sync_or_async('map')

    def get_mapped_range(self, offset: int = 0, size: int | None = None) -> ArrayLike:
        """GPUBuffer.getMappedRange -- see the WebGPU specification."""
        return self._call('get_mapped_range', offset, size)

    def unmap(self) -> None:
        """GPUBuffer.unmap -- see the WebGPU specification."""
        return self._call('unmap')

    def destroy(self) -> None:
        """GPUBuffer.destroy -- see the WebGPU specification."""
        return self._call('destroy')

    @property
    def size(self) -> int:
        """GPUBuffer.size"""
        return self._get('get_size')

    @property
    def usage(self) -> int:
        """GPUBuffer.usage"""
        return self._get('get_usage')

    map_state = _ov.buffer_map_state



class GPUCommandBuffer(GPUObjectBase):
    """GPUCommandBuffer -- see the WebGPU specification."""
    _spec_name = 'command_buffer'

    pass



class GPUCommandsMixin(Mixin):
    """GPUCommandsMixin -- see the WebGPU specification."""

    pass



class GPUDebugCommandsMixin(Mixin):
    """GPUDebugCommandsMixin -- see the WebGPU specification."""

    pass



class GPUCommandEncoder(GPUCommandsMixin, GPUDebugCommandsMixin, GPUObjectBase):
    """GPUCommandEncoder -- see the WebGPU specification."""
    _spec_name = 'command_encoder'

    def begin_render_pass(self, *, label: str = "", color_attachments: Sequence[structs.RenderPassColorAttachmentStruct], depth_stencil_attachment: structs.RenderPassDepthStencilAttachmentStruct | None = None, occlusion_query_set: GPUQuerySet | None = None, timestamp_writes: structs.RenderPassTimestampWritesStruct | None = None, max_draw_count: int = 50000000) -> GPURenderPassEncoder:
        """GPUCommandEncoder.beginRenderPass -- see the WebGPU specification."""
        return self._call_desc('begin_render_pass', {'label': label, 'color_attachments': color_attachments, 'depth_stencil_attachment': depth_stencil_attachment, 'occlusion_query_set': occlusion_query_set, 'timestamp_writes': timestamp_writes, 'max_draw_count': max_draw_count})

    def begin_compute_pass(self, *, label: str = "", timestamp_writes: structs.ComputePassTimestampWritesStruct | None = None) -> GPUComputePassEncoder:
        """GPUCommandEncoder.beginComputePass -- see the WebGPU specification."""
        return self._call_desc('begin_compute_pass', {'label': label, 'timestamp_writes': timestamp_writes})

    def copy_buffer_to_buffer(self, source: GPUBuffer, source_offset: int, destination: GPUBuffer, destination_offset: int, size: int | None = None) -> None:
        """GPUCommandEncoder.copyBufferToBuffer -- see the WebGPU specification."""
        return self._call('copy_buffer_to_buffer', source, source_offset, destination, destination_offset, size)

    def copy_buffer_to_texture(self, source: structs.TexelCopyBufferInfoStruct, destination: structs.TexelCopyTextureInfoStruct, copy_size: tuple[int, int, int] | structs.Extent3DStruct) -> None:
        """GPUCommandEncoder.copyBufferToTexture -- see the WebGPU specification."""
        return self._call('copy_buffer_to_texture', source, destination, copy_size)

    def copy_texture_to_buffer(self, source: structs.TexelCopyTextureInfoStruct, destination: structs.TexelCopyBufferInfoStruct, copy_size: tuple[int, int, int] | structs.Extent3DStruct) -> None:
        """GPUCommandEncoder.copyTextureToBuffer -- see the WebGPU specification."""
        return self._call('copy_texture_to_buffer', source, destination, copy_size)

    def copy_texture_to_texture(self, source: structs.TexelCopyTextureInfoStruct, destination: structs.TexelCopyTextureInfoStruct, copy_size: tuple[int, int, int] | structs.Extent3DStruct) -> None:
        """GPUCommandEncoder.copyTextureToTexture -- see the WebGPU specification."""
        return self._call('copy_texture_to_texture', source, destination, copy_size)

    def clear_buffer(self, buffer: GPUBuffer, offset: int = 0, size: int | None = None) -> None:
        """GPUCommandEncoder.clearBuffer -- see the WebGPU specification."""
        return self._call('clear_buffer', buffer, offset, size)

    def resolve_query_set(self, query_set: GPUQuerySet, first_query: int, query_count: int, destination: GPUBuffer, destination_offset: int) -> None:
        """GPUCommandEncoder.resolveQuerySet -- see the WebGPU specification."""
        return self._call('resolve_query_set', query_set, first_query, query_count, destination, destination_offset)

    def finish(self, *, label: str = "") -> GPUCommandBuffer:
        """GPUCommandEncoder.finish -- see the WebGPU specification."""
        return self._call_desc('finish', {'label': label})



class GPUComputePassEncoder(GPUCommandsMixin, GPUDebugCommandsMixin, GPUBindingCommandsMixin, GPUObjectBase):
    """GPUComputePassEncoder -- see the WebGPU specification."""
    _spec_name = 'compute_pass_encoder'

    def set_pipeline(self, pipeline: GPUComputePipeline) -> None:
        """GPUComputePassEncoder.setPipeline -- see the WebGPU specification."""
        return self._call('set_pipeline', pipeline)

    def dispatch_workgroups(self, workgroup_count_x: int, workgroup_count_y: int = 1, workgroup_count_z: int = 1) -> None:
        """GPUComputePassEncoder.dispatchWorkgroups -- see the WebGPU specification."""
        return self._call('dispatch_workgroups', workgroup_count_x, workgroup_count_y, workgroup_count_z)

    def dispatch_workgroups_indirect(self, indirect_buffer: GPUBuffer, indirect_offset: int) -> None:
        """GPUComputePassEncoder.dispatchWorkgroupsIndirect -- see the WebGPU specification."""
        return self._call('dispatch_workgroups_indirect', indirect_buffer, indirect_offset)

    def end(self) -> None:
        """GPUComputePassEncoder.end -- see the WebGPU specification."""
        return self._call('end')



class GPUPipelineBase(Mixin):
    """GPUPipelineBase -- see the WebGPU specification."""

    pass



class GPUComputePipeline(GPUPipelineBase, GPUObjectBase):
    """GPUComputePipeline -- see the WebGPU specification."""
    _spec_name = 'compute_pipeline'

    pass



class GPUDevice(GPUObjectBase):
    """GPUDevice -- see the WebGPU specification."""
    _spec_name = 'device'

    def destroy(self) -> None:
        """GPUDevice.destroy -- see the WebGPU specification."""
        return self._call('destroy')

    def create_buffer(self, *, label: str = "", size: int, usage: flags.BufferUsageFlags, mapped_at_creation: bool = False) -> GPUBuffer:
        """GPUDevice.createBuffer -- see the WebGPU specification."""
        return self._call_desc('create_buffer', {'label': label, 'size': size, 'usage': usage, 'mapped_at_creation': mapped_at_creation})

    def create_texture(self, *, label: str = "", size: tuple[int, int, int] | structs.Extent3DStruct, mip_level_count: int = 1, sample_count: int = 1, dimension: enums.TextureDimensionEnum = "2d", format: enums.TextureFormatEnum, usage: flags.TextureUsageFlags, view_formats: Sequence[enums.TextureFormatEnum] = (), texture_binding_view_dimension: enums.TextureViewDimensionEnum | None = None) -> GPUTexture:
        """GPUDevice.createTexture -- see the WebGPU specification."""
        return self._call_desc('create_texture', {'label': label, 'size': size, 'mip_level_count': mip_level_count, 'sample_count': sample_count, 'dimension': dimension, 'format': format, 'usage': usage, 'view_formats': view_formats, 'texture_binding_view_dimension': texture_binding_view_dimension})

    def create_sampler(self, *, label: str = "", address_mode_u: enums.AddressModeEnum = "clamp-to-edge", address_mode_v: enums.AddressModeEnum = "clamp-to-edge", address_mode_w: enums.AddressModeEnum = "clamp-to-edge", mag_filter: enums.FilterModeEnum = "nearest", min_filter: enums.FilterModeEnum = "nearest", mipmap_filter: enums.MipmapFilterModeEnum = "nearest", lod_min_clamp: float = 0, lod_max_clamp: float = 32, compare: enums.CompareFunctionEnum | None = None, max_anisotropy: int = 1) -> GPUSampler:
        """GPUDevice.createSampler -- see the WebGPU specification."""
        return self._call_desc('create_sampler', {'label': label, 'address_mode_u': address_mode_u, 'address_mode_v': address_mode_v, 'address_mode_w': address_mode_w, 'mag_filter': mag_filter, 'min_filter': min_filter, 'mipmap_filter': mipmap_filter, 'lod_min_clamp': lod_min_clamp, 'lod_max_clamp': lod_max_clamp, 'compare': compare, 'max_anisotropy': max_anisotropy})

    def create_bind_group_layout(self, *, label: str = "", entries: Sequence[structs.BindGroupLayoutEntryStruct]) -> GPUBindGroupLayout:
        """GPUDevice.createBindGroupLayout -- see the WebGPU specification."""
        return self._call_desc('create_bind_group_layout', {'label': label, 'entries': entries})

    def create_pipeline_layout(self, *, label: str = "", bind_group_layouts: Sequence[GPUBindGroupLayout], immediate_size: int = 0) -> GPUPipelineLayout:
        """GPUDevice.createPipelineLayout -- see the WebGPU specification."""
        return self._call_desc('create_pipeline_layout', {'label': label, 'bind_group_layouts': bind_group_layouts, 'immediate_size': immediate_size})

    def create_bind_group(self, *, label: str = "", layout: GPUBindGroupLayout, entries: Sequence[structs.BindGroupEntryStruct]) -> GPUBindGroup:
        """GPUDevice.createBindGroup -- see the WebGPU specification."""
        return self._call_desc('create_bind_group', {'label': label, 'layout': layout, 'entries': entries})

    def create_shader_module(self, *, label: str = "", code: str, compilation_hints: Sequence[structs.ShaderModuleCompilationHintStruct] = ()) -> GPUShaderModule:
        """GPUDevice.createShaderModule -- see the WebGPU specification."""
        return self._call_desc('create_shader_module', {'label': label, 'code': code, 'compilation_hints': compilation_hints})

    def create_compute_pipeline(self, *, label: str = "", layout: GPUPipelineLayout | enums.AutoLayoutModeEnum, compute: structs.ProgrammableStageStruct) -> GPUComputePipeline:
        """GPUDevice.createComputePipeline -- see the WebGPU specification."""
        return self._call_desc('create_compute_pipeline', {'label': label, 'layout': layout, 'compute': compute})

    def create_render_pipeline(self, *, label: str = "", layout: GPUPipelineLayout | enums.AutoLayoutModeEnum, vertex: structs.VertexStateStruct, primitive: structs.PrimitiveStateStruct | None = None, depth_stencil: structs.DepthStencilStateStruct | None = None, multisample: structs.MultisampleStateStruct | None = None, fragment: structs.FragmentStateStruct | None = None) -> GPURenderPipeline:
        """GPUDevice.createRenderPipeline -- see the WebGPU specification."""
        return self._call_desc('create_render_pipeline', {'label': label, 'layout': layout, 'vertex': vertex, 'primitive': primitive, 'depth_stencil': depth_stencil, 'multisample': multisample, 'fragment': fragment})

    def create_compute_pipeline_async(self, *, label: str = "", layout: GPUPipelineLayout | enums.AutoLayoutModeEnum, compute: structs.ProgrammableStageStruct) -> GPUComputePipeline:
        """GPUDevice.createComputePipelineAsync -- see the WebGPU specification."""
        return self._promise(self._call_desc('create_compute_pipeline_async', {'label': label, 'layout': layout, 'compute': compute}))

    def create_compute_pipeline_sync(self, *, label: str = "", layout: GPUPipelineLayout | enums.AutoLayoutModeEnum, compute: structs.ProgrammableStageStruct) -> GPUComputePipeline:
        """GPUDevice.createComputePipelineAsync -- see the WebGPU specification."""
        return self._await(self._call_desc('create_compute_pipeline_async', {'label': label, 'layout': layout, 'compute': compute}))

    create_compute_pipeline = _ov.deprecated_sync_or_async('create_compute_pipeline')

    def create_render_pipeline_async(self, *, label: str = "", layout: GPUPipelineLayout | enums.AutoLayoutModeEnum, vertex: structs.VertexStateStruct, primitive: structs.PrimitiveStateStruct | None = None, depth_stencil: structs.DepthStencilStateStruct | None = None, multisample: structs.MultisampleStateStruct | None = None, fragment: structs.FragmentStateStruct | None = None) -> GPURenderPipeline:
        """GPUDevice.createRenderPipelineAsync -- see the WebGPU specification."""
        return self._promise(self._call_desc('create_render_pipeline_async', {'label': label, 'layout': layout, 'vertex': vertex, 'primitive': primitive, 'depth_stencil': depth_stencil, 'multisample': multisample, 'fragment': fragment}))

    def create_render_pipeline_sync(self, *, label: str = "", layout: GPUPipelineLayout | enums.AutoLayoutModeEnum, vertex: structs.VertexStateStruct, primitive: structs.PrimitiveStateStruct | None = None, depth_stencil: structs.DepthStencilStateStruct | None = None, multisample: structs.MultisampleStateStruct | None = None, fragment: structs.FragmentStateStruct | None = None) -> GPURenderPipeline:
        """GPUDevice.createRenderPipelineAsync -- see the WebGPU specification."""
        return self._await(self._call_desc('create_render_pipeline_async', {'label': label, 'layout': layout, 'vertex': vertex, 'primitive': primitive, 'depth_stencil': depth_stencil, 'multisample': multisample, 'fragment': fragment}))

    create_render_pipeline = _ov.deprecated_sync_or_async('create_render_pipeline')

    def create_command_encoder(self, *, label: str = "") -> GPUCommandEncoder:
        """GPUDevice.createCommandEncoder -- see the WebGPU specification."""
        return self._call_desc('create_command_encoder', {'label': label})

    def create_render_bundle_encoder(self, *, label: str = "", color_formats: Sequence[enums.TextureFormatEnum], depth_stencil_format: enums.TextureFormatEnum | None = None, sample_count: int = 1, depth_read_only: bool = False, stencil_read_only: bool = False) -> GPURenderBundleEncoder:
        """GPUDevice.createRenderBundleEncoder -- see the WebGPU specification."""
        return self._call_desc('create_render_bundle_encoder', {'label': label, 'color_formats': color_formats, 'depth_stencil_format': depth_stencil_format, 'sample_count': sample_count, 'depth_read_only': depth_read_only, 'stencil_read_only': stencil_read_only})

    def create_query_set(self, *, label: str = "", type: enums.QueryTypeEnum, count: int) -> GPUQuerySet:
        """GPUDevice.createQuerySet -- see the WebGPU specification."""
        return self._call_desc('create_query_set', {'label': label, 'type': type, 'count': count})

    def push_error_scope(self, filter: enums.ErrorFilterEnum) -> None:
        """GPUDevice.pushErrorScope -- see the WebGPU specification."""
        return self._call('push_error_scope', filter)

    def pop_error_scope_async(self) -> GPUError:
        """GPUDevice.popErrorScope -- see the WebGPU specification."""
        return self._promise(self._call('pop_error_scope'))

    def pop_error_scope_sync(self) -> GPUError:
        """GPUDevice.popErrorScope -- see the WebGPU specification."""
        return self._await(self._call('pop_error_scope'))

    pop_error_scope = _ov.deprecated_sync_or_async('pop_error_scope')

    features = _ov.device_features

    limits = _ov.device_limits

    adapter_info = _ov.device_adapter_info

    queue = _ov.device_queue

    lost = _ov.device_lost

    onuncapturederror = _ov.device_onuncapturederror



class GPUPipelineLayout(GPUObjectBase):
    """GPUPipelineLayout -- see the WebGPU specification."""
    _spec_name = 'pipeline_layout'

    pass



class GPUQuerySet(GPUObjectBase):
    """GPUQuerySet -- see the WebGPU specification."""
    _spec_name = 'query_set'

    def destroy(self) -> None:
        """GPUQuerySet.destroy -- see the WebGPU specification."""
        return self._call('destroy')

    @property
    def type(self) -> enums.QueryTypeEnum:
        """GPUQuerySet.type"""
        return self._get('get_type')

    @property
    def count(self) -> int:
        """GPUQuerySet.count"""
        return self._get('get_count')



class GPUQueue(GPUObjectBase):
    """GPUQueue -- see the WebGPU specification."""
    _spec_name = 'queue'

    def submit(self, command_buffers: Sequence[GPUCommandBuffer]) -> None:
        """GPUQueue.submit -- see the WebGPU specification."""
        return self._call('submit', command_buffers)

    def on_submitted_work_done_async(self) -> None:
        """GPUQueue.onSubmittedWorkDone -- see the WebGPU specification."""
        return self._promise(self._call('on_submitted_work_done'))

    def on_submitted_work_done_sync(self) -> None:
        """GPUQueue.onSubmittedWorkDone -- see the WebGPU specification."""
        return self._await(self._call('on_submitted_work_done'))

    on_submitted_work_done = _ov.deprecated_sync_or_async('on_submitted_work_done')

    write_buffer = _ov.queue_write_buffer

    write_texture = _ov.queue_write_texture



class GPURenderBundle(GPUObjectBase):
    """GPURenderBundle -- see the WebGPU specification."""
    _spec_name = 'render_bundle'

    pass



class GPURenderCommandsMixin(Mixin):
    """GPURenderCommandsMixin -- see the WebGPU specification."""

    pass



class GPURenderBundleEncoder(GPUCommandsMixin, GPUDebugCommandsMixin, GPUBindingCommandsMixin, GPURenderCommandsMixin, GPUObjectBase):
    """GPURenderBundleEncoder -- see the WebGPU specification."""
    _spec_name = 'render_bundle_encoder'

    def finish(self, *, label: str = "") -> GPURenderBundle:
        """GPURenderBundleEncoder.finish -- see the WebGPU specification."""
        return self._call_desc('finish', {'label': label})



class GPURenderPassEncoder(GPUCommandsMixin, GPUDebugCommandsMixin, GPUBindingCommandsMixin, GPURenderCommandsMixin, GPUObjectBase):
    """GPURenderPassEncoder -- see the WebGPU specification."""
    _spec_name = 'render_pass_encoder'

    def set_viewport(self, x: float, y: float, width: float, height: float, min_depth: float, max_depth: float) -> None:
        """GPURenderPassEncoder.setViewport -- see the WebGPU specification."""
        return self._call('set_viewport', x, y, width, height, min_depth, max_depth)

    def set_scissor_rect(self, x: int, y: int, width: int, height: int) -> None:
        """GPURenderPassEncoder.setScissorRect -- see the WebGPU specification."""
        return self._call('set_scissor_rect', x, y, width, height)

    def set_blend_constant(self, color: tuple[float, float, float, float] | structs.ColorStruct) -> None:
        """GPURenderPassEncoder.setBlendConstant -- see the WebGPU specification."""
        return self._call('set_blend_constant', color)

    def set_stencil_reference(self, reference: int) -> None:
        """GPURenderPassEncoder.setStencilReference -- see the WebGPU specification."""
        return self._call('set_stencil_reference', reference)

    def begin_occlusion_query(self, query_index: int) -> None:
        """GPURenderPassEncoder.beginOcclusionQuery -- see the WebGPU specification."""
        return self._call('begin_occlusion_query', query_index)

    def end_occlusion_query(self) -> None:
        """GPURenderPassEncoder.endOcclusionQuery -- see the WebGPU specification."""
        return self._call('end_occlusion_query')

    def execute_bundles(self, bundles: Sequence[GPURenderBundle]) -> None:
        """GPURenderPassEncoder.executeBundles -- see the WebGPU specification."""
        return self._call('execute_bundles', bundles)

    def end(self) -> None:
        """GPURenderPassEncoder.end -- see the WebGPU specification."""
        return self._call('end')



class GPURenderPipeline(GPUPipelineBase, GPUObjectBase):
    """GPURenderPipeline -- see the WebGPU specification."""
    _spec_name = 'render_pipeline'

    pass



class GPUSampler(GPUObjectBase):
    """GPUSampler -- see the WebGPU specification."""
    _spec_name = 'sampler'

    pass



class GPUShaderModule(GPUObjectBase):
    """GPUShaderModule -- see the WebGPU specification."""
    _spec_name = 'shader_module'

    def get_compilation_info_async(self) -> GPUCompilationInfo:
        """GPUShaderModule.getCompilationInfo -- see the WebGPU specification."""
        return self._promise(self._call('get_compilation_info'))

    def get_compilation_info_sync(self) -> GPUCompilationInfo:
        """GPUShaderModule.getCompilationInfo -- see the WebGPU specification."""
        return self._await(self._call('get_compilation_info'))

    get_compilation_info = _ov.deprecated_sync_or_async('get_compilation_info')



class GPUTexture(GPUObjectBase):
    """GPUTexture -- see the WebGPU specification."""
    _spec_name = 'texture'

    def create_view(self, *, label: str = "", format: enums.TextureFormatEnum | None = None, dimension: enums.TextureViewDimensionEnum | None = None, usage: flags.TextureUsageFlags = 0, aspect: enums.TextureAspectEnum = "all", base_mip_level: int = 0, mip_level_count: int | None = None, base_array_layer: int = 0, array_layer_count: int | None = None, swizzle: str = "rgba") -> GPUTextureView:
        """GPUTexture.createView -- see the WebGPU specification."""
        return self._call_desc('create_view', {'label': label, 'format': format, 'dimension': dimension, 'usage': usage, 'aspect': aspect, 'base_mip_level': base_mip_level, 'mip_level_count': mip_level_count, 'base_array_layer': base_array_layer, 'array_layer_count': array_layer_count, 'swizzle': swizzle})

    def destroy(self) -> None:
        """GPUTexture.destroy -- see the WebGPU specification."""
        return self._call('destroy')

    @property
    def width(self) -> int:
        """GPUTexture.width"""
        return self._get('get_width')

    @property
    def height(self) -> int:
        """GPUTexture.height"""
        return self._get('get_height')

    @property
    def depth_or_array_layers(self) -> int:
        """GPUTexture.depthOrArrayLayers"""
        return self._get('get_depth_or_array_layers')

    @property
    def mip_level_count(self) -> int:
        """GPUTexture.mipLevelCount"""
        return self._get('get_mip_level_count')

    @property
    def sample_count(self) -> int:
        """GPUTexture.sampleCount"""
        return self._get('get_sample_count')

    @property
    def dimension(self) -> enums.TextureDimensionEnum:
        """GPUTexture.dimension"""
        return self._get('get_dimension')

    @property
    def format(self) -> enums.TextureFormatEnum:
        """GPUTexture.format"""
        return self._get('get_format')

    @property
    def usage(self) -> int:
        """GPUTexture.usage"""
        return self._get('get_usage')

    texture_binding_view_dimension = _ov.texture_texture_binding_view_dimension



class GPUTextureView(GPUObjectBase):
    """GPUTextureView -- see the WebGPU specification."""
    _spec_name = 'texture_view'

    pass
