# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Public API surface, generated from bindgen/resources/webgpu.idl (the W3C
# WebGPU Web IDL) and cross-referenced against the wgpu-native C spec. Re-run
# the generator after updating either spec.

"""WebGPU enums. Values are strings, so ``wgpu.TextureFormat.rgba8unorm``
and ``"rgba8unorm"`` are interchangeable."""

from typing import Literal

from wgpu._api.enumbase import EnumType as _EnumType
from wgpu._api.maps import EnumMap as _EnumMap


class Enum(metaclass=_EnumType):
    """Base class for wgpu enums."""

    def __init__(self):
        raise RuntimeError("Cannot instantiate an enum.")


__all__ = [
    'AddressMode',
    'AutoLayoutMode',
    'BlendFactor',
    'BlendOperation',
    'BufferBindingType',
    'BufferMapState',
    'CanvasAlphaMode',
    'CanvasToneMappingMode',
    'CompareFunction',
    'CompilationMessageType',
    'CullMode',
    'DeviceLostReason',
    'ErrorFilter',
    'FeatureName',
    'FilterMode',
    'FrontFace',
    'IndexFormat',
    'LoadOp',
    'MipmapFilterMode',
    'PipelineErrorReason',
    'PowerPreference',
    'PrimitiveTopology',
    'QueryType',
    'SamplerBindingType',
    'StencilOperation',
    'StorageTextureAccess',
    'StoreOp',
    'TextureAspect',
    'TextureDimension',
    'TextureFormat',
    'TextureSampleType',
    'TextureViewDimension',
    'VertexFormat',
    'VertexStepMode',
    'AddressModeEnum',
    'AutoLayoutModeEnum',
    'BlendFactorEnum',
    'BlendOperationEnum',
    'BufferBindingTypeEnum',
    'BufferMapStateEnum',
    'CanvasAlphaModeEnum',
    'CanvasToneMappingModeEnum',
    'CompareFunctionEnum',
    'CompilationMessageTypeEnum',
    'CullModeEnum',
    'DeviceLostReasonEnum',
    'ErrorFilterEnum',
    'FeatureNameEnum',
    'FilterModeEnum',
    'FrontFaceEnum',
    'IndexFormatEnum',
    'LoadOpEnum',
    'MipmapFilterModeEnum',
    'PipelineErrorReasonEnum',
    'PowerPreferenceEnum',
    'PrimitiveTopologyEnum',
    'QueryTypeEnum',
    'SamplerBindingTypeEnum',
    'StencilOperationEnum',
    'StorageTextureAccessEnum',
    'StoreOpEnum',
    'TextureAspectEnum',
    'TextureDimensionEnum',
    'TextureFormatEnum',
    'TextureSampleTypeEnum',
    'TextureViewDimensionEnum',
    'VertexFormatEnum',
    'VertexStepModeEnum',
]


class AddressMode(Enum):
    clamp_to_edge = 'clamp-to-edge'
    repeat = 'repeat'
    mirror_repeat = 'mirror-repeat'


class AutoLayoutMode(Enum):
    auto = 'auto'


class BlendFactor(Enum):
    zero = 'zero'
    one = 'one'
    src = 'src'
    one_minus_src = 'one-minus-src'
    src_alpha = 'src-alpha'
    one_minus_src_alpha = 'one-minus-src-alpha'
    dst = 'dst'
    one_minus_dst = 'one-minus-dst'
    dst_alpha = 'dst-alpha'
    one_minus_dst_alpha = 'one-minus-dst-alpha'
    src_alpha_saturated = 'src-alpha-saturated'
    constant = 'constant'
    one_minus_constant = 'one-minus-constant'
    src1 = 'src1'
    one_minus_src1 = 'one-minus-src1'
    src1_alpha = 'src1-alpha'
    one_minus_src1_alpha = 'one-minus-src1-alpha'


class BlendOperation(Enum):
    add = 'add'
    subtract = 'subtract'
    reverse_subtract = 'reverse-subtract'
    min = 'min'
    max = 'max'


class BufferBindingType(Enum):
    uniform = 'uniform'
    storage = 'storage'
    read_only_storage = 'read-only-storage'


class BufferMapState(Enum):
    unmapped = 'unmapped'
    pending = 'pending'
    mapped = 'mapped'


class CanvasAlphaMode(Enum):
    opaque = 'opaque'
    premultiplied = 'premultiplied'


class CanvasToneMappingMode(Enum):
    standard = 'standard'
    extended = 'extended'


class CompareFunction(Enum):
    never = 'never'
    less = 'less'
    equal = 'equal'
    less_equal = 'less-equal'
    greater = 'greater'
    not_equal = 'not-equal'
    greater_equal = 'greater-equal'
    always = 'always'


class CompilationMessageType(Enum):
    error = 'error'
    warning = 'warning'
    info = 'info'


class CullMode(Enum):
    none = 'none'
    front = 'front'
    back = 'back'


class DeviceLostReason(Enum):
    unknown = 'unknown'
    destroyed = 'destroyed'


class ErrorFilter(Enum):
    validation = 'validation'
    out_of_memory = 'out-of-memory'
    internal = 'internal'


class FeatureName(Enum):
    core_features_and_limits = 'core-features-and-limits'
    depth_clip_control = 'depth-clip-control'
    depth32float_stencil8 = 'depth32float-stencil8'
    texture_compression_bc = 'texture-compression-bc'
    texture_compression_bc_sliced_d3 = 'texture-compression-bc-sliced-3d'
    texture_compression_etc2 = 'texture-compression-etc2'
    texture_compression_astc = 'texture-compression-astc'
    texture_compression_astc_sliced_d3 = 'texture-compression-astc-sliced-3d'
    timestamp_query = 'timestamp-query'
    indirect_first_instance = 'indirect-first-instance'
    shader_f16 = 'shader-f16'
    rg11b10ufloat_renderable = 'rg11b10ufloat-renderable'
    bgra8unorm_storage = 'bgra8unorm-storage'
    float32_filterable = 'float32-filterable'
    float32_blendable = 'float32-blendable'
    clip_distances = 'clip-distances'
    dual_source_blending = 'dual-source-blending'
    subgroups = 'subgroups'
    texture_formats_tier1 = 'texture-formats-tier1'
    texture_formats_tier2 = 'texture-formats-tier2'
    primitive_index = 'primitive-index'
    texture_component_swizzle = 'texture-component-swizzle'


class FilterMode(Enum):
    nearest = 'nearest'
    linear = 'linear'


class FrontFace(Enum):
    ccw = 'ccw'
    cw = 'cw'


class IndexFormat(Enum):
    uint16 = 'uint16'
    uint32 = 'uint32'


class LoadOp(Enum):
    load = 'load'
    clear = 'clear'


class MipmapFilterMode(Enum):
    nearest = 'nearest'
    linear = 'linear'


class PipelineErrorReason(Enum):
    validation = 'validation'
    internal = 'internal'


class PowerPreference(Enum):
    low_power = 'low-power'
    high_performance = 'high-performance'


class PrimitiveTopology(Enum):
    point_list = 'point-list'
    line_list = 'line-list'
    line_strip = 'line-strip'
    triangle_list = 'triangle-list'
    triangle_strip = 'triangle-strip'


class QueryType(Enum):
    occlusion = 'occlusion'
    timestamp = 'timestamp'


class SamplerBindingType(Enum):
    filtering = 'filtering'
    non_filtering = 'non-filtering'
    comparison = 'comparison'


class StencilOperation(Enum):
    keep = 'keep'
    zero = 'zero'
    replace = 'replace'
    invert = 'invert'
    increment_clamp = 'increment-clamp'
    decrement_clamp = 'decrement-clamp'
    increment_wrap = 'increment-wrap'
    decrement_wrap = 'decrement-wrap'


class StorageTextureAccess(Enum):
    write_only = 'write-only'
    read_only = 'read-only'
    read_write = 'read-write'


class StoreOp(Enum):
    store = 'store'
    discard = 'discard'


class TextureAspect(Enum):
    all = 'all'
    stencil_only = 'stencil-only'
    depth_only = 'depth-only'


class TextureDimension(Enum):
    d1 = '1d'
    d2 = '2d'
    d3 = '3d'


class TextureFormat(Enum):
    r8unorm = 'r8unorm'
    r8snorm = 'r8snorm'
    r8uint = 'r8uint'
    r8sint = 'r8sint'
    r16unorm = 'r16unorm'
    r16snorm = 'r16snorm'
    r16uint = 'r16uint'
    r16sint = 'r16sint'
    r16float = 'r16float'
    rg8unorm = 'rg8unorm'
    rg8snorm = 'rg8snorm'
    rg8uint = 'rg8uint'
    rg8sint = 'rg8sint'
    r32uint = 'r32uint'
    r32sint = 'r32sint'
    r32float = 'r32float'
    rg16unorm = 'rg16unorm'
    rg16snorm = 'rg16snorm'
    rg16uint = 'rg16uint'
    rg16sint = 'rg16sint'
    rg16float = 'rg16float'
    rgba8unorm = 'rgba8unorm'
    rgba8unorm_srgb = 'rgba8unorm-srgb'
    rgba8snorm = 'rgba8snorm'
    rgba8uint = 'rgba8uint'
    rgba8sint = 'rgba8sint'
    bgra8unorm = 'bgra8unorm'
    bgra8unorm_srgb = 'bgra8unorm-srgb'
    rgb9e5ufloat = 'rgb9e5ufloat'
    rgb10a2uint = 'rgb10a2uint'
    rgb10a2unorm = 'rgb10a2unorm'
    rg11b10ufloat = 'rg11b10ufloat'
    rg32uint = 'rg32uint'
    rg32sint = 'rg32sint'
    rg32float = 'rg32float'
    rgba16unorm = 'rgba16unorm'
    rgba16snorm = 'rgba16snorm'
    rgba16uint = 'rgba16uint'
    rgba16sint = 'rgba16sint'
    rgba16float = 'rgba16float'
    rgba32uint = 'rgba32uint'
    rgba32sint = 'rgba32sint'
    rgba32float = 'rgba32float'
    stencil8 = 'stencil8'
    depth16unorm = 'depth16unorm'
    depth24plus = 'depth24plus'
    depth24plus_stencil8 = 'depth24plus-stencil8'
    depth32float = 'depth32float'
    depth32float_stencil8 = 'depth32float-stencil8'
    bc1_rgba_unorm = 'bc1-rgba-unorm'
    bc1_rgba_unorm_srgb = 'bc1-rgba-unorm-srgb'
    bc2_rgba_unorm = 'bc2-rgba-unorm'
    bc2_rgba_unorm_srgb = 'bc2-rgba-unorm-srgb'
    bc3_rgba_unorm = 'bc3-rgba-unorm'
    bc3_rgba_unorm_srgb = 'bc3-rgba-unorm-srgb'
    bc4_r_unorm = 'bc4-r-unorm'
    bc4_r_snorm = 'bc4-r-snorm'
    bc5_rg_unorm = 'bc5-rg-unorm'
    bc5_rg_snorm = 'bc5-rg-snorm'
    bc6h_rgb_ufloat = 'bc6h-rgb-ufloat'
    bc6h_rgb_float = 'bc6h-rgb-float'
    bc7_rgba_unorm = 'bc7-rgba-unorm'
    bc7_rgba_unorm_srgb = 'bc7-rgba-unorm-srgb'
    etc2_rgb8unorm = 'etc2-rgb8unorm'
    etc2_rgb8unorm_srgb = 'etc2-rgb8unorm-srgb'
    etc2_rgb8a1unorm = 'etc2-rgb8a1unorm'
    etc2_rgb8a1unorm_srgb = 'etc2-rgb8a1unorm-srgb'
    etc2_rgba8unorm = 'etc2-rgba8unorm'
    etc2_rgba8unorm_srgb = 'etc2-rgba8unorm-srgb'
    eac_r11unorm = 'eac-r11unorm'
    eac_r11snorm = 'eac-r11snorm'
    eac_rg11unorm = 'eac-rg11unorm'
    eac_rg11snorm = 'eac-rg11snorm'
    astc_4x4_unorm = 'astc-4x4-unorm'
    astc_4x4_unorm_srgb = 'astc-4x4-unorm-srgb'
    astc_5x4_unorm = 'astc-5x4-unorm'
    astc_5x4_unorm_srgb = 'astc-5x4-unorm-srgb'
    astc_5x5_unorm = 'astc-5x5-unorm'
    astc_5x5_unorm_srgb = 'astc-5x5-unorm-srgb'
    astc_6x5_unorm = 'astc-6x5-unorm'
    astc_6x5_unorm_srgb = 'astc-6x5-unorm-srgb'
    astc_6x6_unorm = 'astc-6x6-unorm'
    astc_6x6_unorm_srgb = 'astc-6x6-unorm-srgb'
    astc_8x5_unorm = 'astc-8x5-unorm'
    astc_8x5_unorm_srgb = 'astc-8x5-unorm-srgb'
    astc_8x6_unorm = 'astc-8x6-unorm'
    astc_8x6_unorm_srgb = 'astc-8x6-unorm-srgb'
    astc_8x8_unorm = 'astc-8x8-unorm'
    astc_8x8_unorm_srgb = 'astc-8x8-unorm-srgb'
    astc_10x5_unorm = 'astc-10x5-unorm'
    astc_10x5_unorm_srgb = 'astc-10x5-unorm-srgb'
    astc_10x6_unorm = 'astc-10x6-unorm'
    astc_10x6_unorm_srgb = 'astc-10x6-unorm-srgb'
    astc_10x8_unorm = 'astc-10x8-unorm'
    astc_10x8_unorm_srgb = 'astc-10x8-unorm-srgb'
    astc_10x10_unorm = 'astc-10x10-unorm'
    astc_10x10_unorm_srgb = 'astc-10x10-unorm-srgb'
    astc_12x10_unorm = 'astc-12x10-unorm'
    astc_12x10_unorm_srgb = 'astc-12x10-unorm-srgb'
    astc_12x12_unorm = 'astc-12x12-unorm'
    astc_12x12_unorm_srgb = 'astc-12x12-unorm-srgb'


class TextureSampleType(Enum):
    float = 'float'
    unfilterable_float = 'unfilterable-float'
    depth = 'depth'
    sint = 'sint'
    uint = 'uint'


class TextureViewDimension(Enum):
    d1 = '1d'
    d2 = '2d'
    d2_array = '2d-array'
    cube = 'cube'
    cube_array = 'cube-array'
    d3 = '3d'


class VertexFormat(Enum):
    uint8 = 'uint8'
    uint8x2 = 'uint8x2'
    uint8x4 = 'uint8x4'
    sint8 = 'sint8'
    sint8x2 = 'sint8x2'
    sint8x4 = 'sint8x4'
    unorm8 = 'unorm8'
    unorm8x2 = 'unorm8x2'
    unorm8x4 = 'unorm8x4'
    snorm8 = 'snorm8'
    snorm8x2 = 'snorm8x2'
    snorm8x4 = 'snorm8x4'
    uint16 = 'uint16'
    uint16x2 = 'uint16x2'
    uint16x4 = 'uint16x4'
    sint16 = 'sint16'
    sint16x2 = 'sint16x2'
    sint16x4 = 'sint16x4'
    unorm16 = 'unorm16'
    unorm16x2 = 'unorm16x2'
    unorm16x4 = 'unorm16x4'
    snorm16 = 'snorm16'
    snorm16x2 = 'snorm16x2'
    snorm16x4 = 'snorm16x4'
    float16 = 'float16'
    float16x2 = 'float16x2'
    float16x4 = 'float16x4'
    float32 = 'float32'
    float32x2 = 'float32x2'
    float32x3 = 'float32x3'
    float32x4 = 'float32x4'
    uint32 = 'uint32'
    uint32x2 = 'uint32x2'
    uint32x3 = 'uint32x3'
    uint32x4 = 'uint32x4'
    sint32 = 'sint32'
    sint32x2 = 'sint32x2'
    sint32x3 = 'sint32x3'
    sint32x4 = 'sint32x4'
    unorm10_10_10_2 = 'unorm10-10-10-2'
    unorm8x4_bgra = 'unorm8x4-bgra'


class VertexStepMode(Enum):
    vertex = 'vertex'
    instance = 'instance'


AddressModeEnum = Literal['clamp-to-edge', 'repeat', 'mirror-repeat'] | str
AutoLayoutModeEnum = Literal['auto'] | str
BlendFactorEnum = Literal['zero', 'one', 'src', 'one-minus-src', 'src-alpha', 'one-minus-src-alpha', 'dst', 'one-minus-dst', 'dst-alpha', 'one-minus-dst-alpha', 'src-alpha-saturated', 'constant', 'one-minus-constant', 'src1', 'one-minus-src1', 'src1-alpha', 'one-minus-src1-alpha'] | str
BlendOperationEnum = Literal['add', 'subtract', 'reverse-subtract', 'min', 'max'] | str
BufferBindingTypeEnum = Literal['uniform', 'storage', 'read-only-storage'] | str
BufferMapStateEnum = Literal['unmapped', 'pending', 'mapped'] | str
CanvasAlphaModeEnum = Literal['opaque', 'premultiplied'] | str
CanvasToneMappingModeEnum = Literal['standard', 'extended'] | str
CompareFunctionEnum = Literal['never', 'less', 'equal', 'less-equal', 'greater', 'not-equal', 'greater-equal', 'always'] | str
CompilationMessageTypeEnum = Literal['error', 'warning', 'info'] | str
CullModeEnum = Literal['none', 'front', 'back'] | str
DeviceLostReasonEnum = Literal['unknown', 'destroyed'] | str
ErrorFilterEnum = Literal['validation', 'out-of-memory', 'internal'] | str
FeatureNameEnum = Literal['core-features-and-limits', 'depth-clip-control', 'depth32float-stencil8', 'texture-compression-bc', 'texture-compression-bc-sliced-3d', 'texture-compression-etc2', 'texture-compression-astc', 'texture-compression-astc-sliced-3d', 'timestamp-query', 'indirect-first-instance', 'shader-f16', 'rg11b10ufloat-renderable', 'bgra8unorm-storage', 'float32-filterable', 'float32-blendable', 'clip-distances', 'dual-source-blending', 'subgroups', 'texture-formats-tier1', 'texture-formats-tier2', 'primitive-index', 'texture-component-swizzle'] | str
FilterModeEnum = Literal['nearest', 'linear'] | str
FrontFaceEnum = Literal['ccw', 'cw'] | str
IndexFormatEnum = Literal['uint16', 'uint32'] | str
LoadOpEnum = Literal['load', 'clear'] | str
MipmapFilterModeEnum = Literal['nearest', 'linear'] | str
PipelineErrorReasonEnum = Literal['validation', 'internal'] | str
PowerPreferenceEnum = Literal['low-power', 'high-performance'] | str
PrimitiveTopologyEnum = Literal['point-list', 'line-list', 'line-strip', 'triangle-list', 'triangle-strip'] | str
QueryTypeEnum = Literal['occlusion', 'timestamp'] | str
SamplerBindingTypeEnum = Literal['filtering', 'non-filtering', 'comparison'] | str
StencilOperationEnum = Literal['keep', 'zero', 'replace', 'invert', 'increment-clamp', 'decrement-clamp', 'increment-wrap', 'decrement-wrap'] | str
StorageTextureAccessEnum = Literal['write-only', 'read-only', 'read-write'] | str
StoreOpEnum = Literal['store', 'discard'] | str
TextureAspectEnum = Literal['all', 'stencil-only', 'depth-only'] | str
TextureDimensionEnum = Literal['1d', '2d', '3d'] | str
TextureFormatEnum = Literal['r8unorm', 'r8snorm', 'r8uint', 'r8sint', 'r16unorm', 'r16snorm', 'r16uint', 'r16sint', 'r16float', 'rg8unorm', 'rg8snorm', 'rg8uint', 'rg8sint', 'r32uint', 'r32sint', 'r32float', 'rg16unorm', 'rg16snorm', 'rg16uint', 'rg16sint', 'rg16float', 'rgba8unorm', 'rgba8unorm-srgb', 'rgba8snorm', 'rgba8uint', 'rgba8sint', 'bgra8unorm', 'bgra8unorm-srgb', 'rgb9e5ufloat', 'rgb10a2uint', 'rgb10a2unorm', 'rg11b10ufloat', 'rg32uint', 'rg32sint', 'rg32float', 'rgba16unorm', 'rgba16snorm', 'rgba16uint', 'rgba16sint', 'rgba16float', 'rgba32uint', 'rgba32sint', 'rgba32float', 'stencil8', 'depth16unorm', 'depth24plus', 'depth24plus-stencil8', 'depth32float', 'depth32float-stencil8', 'bc1-rgba-unorm', 'bc1-rgba-unorm-srgb', 'bc2-rgba-unorm', 'bc2-rgba-unorm-srgb', 'bc3-rgba-unorm', 'bc3-rgba-unorm-srgb', 'bc4-r-unorm', 'bc4-r-snorm', 'bc5-rg-unorm', 'bc5-rg-snorm', 'bc6h-rgb-ufloat', 'bc6h-rgb-float', 'bc7-rgba-unorm', 'bc7-rgba-unorm-srgb', 'etc2-rgb8unorm', 'etc2-rgb8unorm-srgb', 'etc2-rgb8a1unorm', 'etc2-rgb8a1unorm-srgb', 'etc2-rgba8unorm', 'etc2-rgba8unorm-srgb', 'eac-r11unorm', 'eac-r11snorm', 'eac-rg11unorm', 'eac-rg11snorm', 'astc-4x4-unorm', 'astc-4x4-unorm-srgb', 'astc-5x4-unorm', 'astc-5x4-unorm-srgb', 'astc-5x5-unorm', 'astc-5x5-unorm-srgb', 'astc-6x5-unorm', 'astc-6x5-unorm-srgb', 'astc-6x6-unorm', 'astc-6x6-unorm-srgb', 'astc-8x5-unorm', 'astc-8x5-unorm-srgb', 'astc-8x6-unorm', 'astc-8x6-unorm-srgb', 'astc-8x8-unorm', 'astc-8x8-unorm-srgb', 'astc-10x5-unorm', 'astc-10x5-unorm-srgb', 'astc-10x6-unorm', 'astc-10x6-unorm-srgb', 'astc-10x8-unorm', 'astc-10x8-unorm-srgb', 'astc-10x10-unorm', 'astc-10x10-unorm-srgb', 'astc-12x10-unorm', 'astc-12x10-unorm-srgb', 'astc-12x12-unorm', 'astc-12x12-unorm-srgb'] | str
TextureSampleTypeEnum = Literal['float', 'unfilterable-float', 'depth', 'sint', 'uint'] | str
TextureViewDimensionEnum = Literal['1d', '2d', '2d-array', 'cube', 'cube-array', '3d'] | str
VertexFormatEnum = Literal['uint8', 'uint8x2', 'uint8x4', 'sint8', 'sint8x2', 'sint8x4', 'unorm8', 'unorm8x2', 'unorm8x4', 'snorm8', 'snorm8x2', 'snorm8x4', 'uint16', 'uint16x2', 'uint16x4', 'sint16', 'sint16x2', 'sint16x4', 'unorm16', 'unorm16x2', 'unorm16x4', 'snorm16', 'snorm16x2', 'snorm16x4', 'float16', 'float16x2', 'float16x4', 'float32', 'float32x2', 'float32x3', 'float32x4', 'uint32', 'uint32x2', 'uint32x3', 'uint32x4', 'sint32', 'sint32x2', 'sint32x3', 'sint32x4', 'unorm10-10-10-2', 'unorm8x4-bgra'] | str
VertexStepModeEnum = Literal['vertex', 'instance'] | str


#: C-spec enum name -> mapping of accepted value to C integer.
TO_INT: dict[str, _EnumMap] = {}

TO_INT['address_mode'] = _EnumMap('AddressMode', {
    'clamp-to-edge': 1,
    'repeat': 2,
    'mirror-repeat': 3,
})

TO_INT['blend_factor'] = _EnumMap('BlendFactor', {
    'zero': 1,
    'one': 2,
    'src': 3,
    'one-minus-src': 4,
    'src-alpha': 5,
    'one-minus-src-alpha': 6,
    'dst': 7,
    'one-minus-dst': 8,
    'dst-alpha': 9,
    'one-minus-dst-alpha': 10,
    'src-alpha-saturated': 11,
    'constant': 12,
    'one-minus-constant': 13,
    'src1': 14,
    'one-minus-src1': 15,
    'src1-alpha': 16,
    'one-minus-src1-alpha': 17,
})

TO_INT['blend_operation'] = _EnumMap('BlendOperation', {
    'add': 1,
    'subtract': 2,
    'reverse-subtract': 3,
    'min': 4,
    'max': 5,
})

TO_INT['buffer_binding_type'] = _EnumMap('BufferBindingType', {
    'uniform': 2,
    'storage': 3,
    'read-only-storage': 4,
})

TO_INT['buffer_map_state'] = _EnumMap('BufferMapState', {
    'unmapped': 1,
    'pending': 2,
    'mapped': 3,
})

TO_INT['compare_function'] = _EnumMap('CompareFunction', {
    'never': 1,
    'less': 2,
    'equal': 3,
    'less-equal': 4,
    'greater': 5,
    'not-equal': 6,
    'greater-equal': 7,
    'always': 8,
})

TO_INT['compilation_message_type'] = _EnumMap('CompilationMessageType', {
    'error': 1,
    'warning': 2,
    'info': 3,
})

TO_INT['cull_mode'] = _EnumMap('CullMode', {
    'none': 1,
    'front': 2,
    'back': 3,
})

TO_INT['device_lost_reason'] = _EnumMap('DeviceLostReason', {
    'unknown': 1,
    'destroyed': 2,
})

TO_INT['error_filter'] = _EnumMap('ErrorFilter', {
    'validation': 1,
    'out-of-memory': 2,
    'internal': 3,
})

TO_INT['feature_name'] = _EnumMap('FeatureName', {
    'core-features-and-limits': 1,
    'depth-clip-control': 2,
    'depth32float-stencil8': 3,
    'texture-compression-bc': 4,
    'texture-compression-bc-sliced-3d': 5,
    'texture-compression-etc2': 6,
    'texture-compression-astc': 7,
    'texture-compression-astc-sliced-3d': 8,
    'timestamp-query': 9,
    'indirect-first-instance': 10,
    'shader-f16': 11,
    'rg11b10ufloat-renderable': 12,
    'bgra8unorm-storage': 13,
    'float32-filterable': 14,
    'float32-blendable': 15,
    'clip-distances': 16,
    'dual-source-blending': 17,
    'subgroups': 18,
    'texture-formats-tier1': 19,
    'texture-formats-tier2': 20,
    'primitive-index': 21,
    'texture-component-swizzle': 22,
})

TO_INT['filter_mode'] = _EnumMap('FilterMode', {
    'nearest': 1,
    'linear': 2,
})

TO_INT['front_face'] = _EnumMap('FrontFace', {
    'ccw': 1,
    'cw': 2,
})

TO_INT['index_format'] = _EnumMap('IndexFormat', {
    'uint16': 1,
    'uint32': 2,
})

TO_INT['load_op'] = _EnumMap('LoadOp', {
    'load': 1,
    'clear': 2,
})

TO_INT['mipmap_filter_mode'] = _EnumMap('MipmapFilterMode', {
    'nearest': 1,
    'linear': 2,
})

TO_INT['power_preference'] = _EnumMap('PowerPreference', {
    'low-power': 1,
    'high-performance': 2,
})

TO_INT['primitive_topology'] = _EnumMap('PrimitiveTopology', {
    'point-list': 1,
    'line-list': 2,
    'line-strip': 3,
    'triangle-list': 4,
    'triangle-strip': 5,
})

TO_INT['query_type'] = _EnumMap('QueryType', {
    'occlusion': 1,
    'timestamp': 2,
})

TO_INT['sampler_binding_type'] = _EnumMap('SamplerBindingType', {
    'filtering': 2,
    'non-filtering': 3,
    'comparison': 4,
})

TO_INT['stencil_operation'] = _EnumMap('StencilOperation', {
    'keep': 1,
    'zero': 2,
    'replace': 3,
    'invert': 4,
    'increment-clamp': 5,
    'decrement-clamp': 6,
    'increment-wrap': 7,
    'decrement-wrap': 8,
})

TO_INT['storage_texture_access'] = _EnumMap('StorageTextureAccess', {
    'write-only': 2,
    'read-only': 3,
    'read-write': 4,
})

TO_INT['store_op'] = _EnumMap('StoreOp', {
    'store': 1,
    'discard': 2,
})

TO_INT['texture_aspect'] = _EnumMap('TextureAspect', {
    'all': 1,
    'stencil-only': 2,
    'depth-only': 3,
})

TO_INT['texture_dimension'] = _EnumMap('TextureDimension', {
    '1d': 1,
    '2d': 2,
    '3d': 3,
})

TO_INT['texture_format'] = _EnumMap('TextureFormat', {
    'r8unorm': 1,
    'r8snorm': 2,
    'r8uint': 3,
    'r8sint': 4,
    'r16unorm': 5,
    'r16snorm': 6,
    'r16uint': 7,
    'r16sint': 8,
    'r16float': 9,
    'rg8unorm': 10,
    'rg8snorm': 11,
    'rg8uint': 12,
    'rg8sint': 13,
    'r32uint': 15,
    'r32sint': 16,
    'r32float': 14,
    'rg16unorm': 17,
    'rg16snorm': 18,
    'rg16uint': 19,
    'rg16sint': 20,
    'rg16float': 21,
    'rgba8unorm': 22,
    'rgba8unorm-srgb': 23,
    'rgba8snorm': 24,
    'rgba8uint': 25,
    'rgba8sint': 26,
    'bgra8unorm': 27,
    'bgra8unorm-srgb': 28,
    'rgb9e5ufloat': 32,
    'rgb10a2uint': 29,
    'rgb10a2unorm': 30,
    'rg11b10ufloat': 31,
    'rg32uint': 34,
    'rg32sint': 35,
    'rg32float': 33,
    'rgba16unorm': 36,
    'rgba16snorm': 37,
    'rgba16uint': 38,
    'rgba16sint': 39,
    'rgba16float': 40,
    'rgba32uint': 42,
    'rgba32sint': 43,
    'rgba32float': 41,
    'stencil8': 44,
    'depth16unorm': 45,
    'depth24plus': 46,
    'depth24plus-stencil8': 47,
    'depth32float': 48,
    'depth32float-stencil8': 49,
    'bc1-rgba-unorm': 50,
    'bc1-rgba-unorm-srgb': 51,
    'bc2-rgba-unorm': 52,
    'bc2-rgba-unorm-srgb': 53,
    'bc3-rgba-unorm': 54,
    'bc3-rgba-unorm-srgb': 55,
    'bc4-r-unorm': 56,
    'bc4-r-snorm': 57,
    'bc5-rg-unorm': 58,
    'bc5-rg-snorm': 59,
    'bc6h-rgb-ufloat': 60,
    'bc6h-rgb-float': 61,
    'bc7-rgba-unorm': 62,
    'bc7-rgba-unorm-srgb': 63,
    'etc2-rgb8unorm': 64,
    'etc2-rgb8unorm-srgb': 65,
    'etc2-rgb8a1unorm': 66,
    'etc2-rgb8a1unorm-srgb': 67,
    'etc2-rgba8unorm': 68,
    'etc2-rgba8unorm-srgb': 69,
    'eac-r11unorm': 70,
    'eac-r11snorm': 71,
    'eac-rg11unorm': 72,
    'eac-rg11snorm': 73,
    'astc-4x4-unorm': 74,
    'astc-4x4-unorm-srgb': 75,
    'astc-5x4-unorm': 76,
    'astc-5x4-unorm-srgb': 77,
    'astc-5x5-unorm': 78,
    'astc-5x5-unorm-srgb': 79,
    'astc-6x5-unorm': 80,
    'astc-6x5-unorm-srgb': 81,
    'astc-6x6-unorm': 82,
    'astc-6x6-unorm-srgb': 83,
    'astc-8x5-unorm': 84,
    'astc-8x5-unorm-srgb': 85,
    'astc-8x6-unorm': 86,
    'astc-8x6-unorm-srgb': 87,
    'astc-8x8-unorm': 88,
    'astc-8x8-unorm-srgb': 89,
    'astc-10x5-unorm': 90,
    'astc-10x5-unorm-srgb': 91,
    'astc-10x6-unorm': 92,
    'astc-10x6-unorm-srgb': 93,
    'astc-10x8-unorm': 94,
    'astc-10x8-unorm-srgb': 95,
    'astc-10x10-unorm': 96,
    'astc-10x10-unorm-srgb': 97,
    'astc-12x10-unorm': 98,
    'astc-12x10-unorm-srgb': 99,
    'astc-12x12-unorm': 100,
    'astc-12x12-unorm-srgb': 101,
})

TO_INT['texture_sample_type'] = _EnumMap('TextureSampleType', {
    'float': 2,
    'unfilterable-float': 3,
    'depth': 4,
    'sint': 5,
    'uint': 6,
})

TO_INT['texture_view_dimension'] = _EnumMap('TextureViewDimension', {
    '1d': 1,
    '2d': 2,
    '2d-array': 3,
    'cube': 4,
    'cube-array': 5,
    '3d': 6,
})

TO_INT['vertex_format'] = _EnumMap('VertexFormat', {
    'uint8': 1,
    'uint8x2': 2,
    'uint8x4': 3,
    'sint8': 4,
    'sint8x2': 5,
    'sint8x4': 6,
    'unorm8': 7,
    'unorm8x2': 8,
    'unorm8x4': 9,
    'snorm8': 10,
    'snorm8x2': 11,
    'snorm8x4': 12,
    'uint16': 13,
    'uint16x2': 14,
    'uint16x4': 15,
    'sint16': 16,
    'sint16x2': 17,
    'sint16x4': 18,
    'unorm16': 19,
    'unorm16x2': 20,
    'unorm16x4': 21,
    'snorm16': 22,
    'snorm16x2': 23,
    'snorm16x4': 24,
    'float16': 25,
    'float16x2': 26,
    'float16x4': 27,
    'float32': 28,
    'float32x2': 29,
    'float32x3': 30,
    'float32x4': 31,
    'uint32': 32,
    'uint32x2': 33,
    'uint32x3': 34,
    'uint32x4': 35,
    'sint32': 36,
    'sint32x2': 37,
    'sint32x3': 38,
    'sint32x4': 39,
    'unorm10-10-10-2': 40,
    'unorm8x4-bgra': 41,
})

TO_INT['vertex_step_mode'] = _EnumMap('VertexStepMode', {
    'vertex': 1,
    'instance': 2,
})


# wgpu-native's own features, from wgpu.h. Not WebGPU, but
# they extend the same enum and are requested the same way.
TO_INT['feature_name'].update({
    'acceleration-structure-binding-array': 196670,
    'address-mode-clamp-to-border': 196626,
    'address-mode-clamp-to-zero': 196625,
    'buffer-binding-array': 196623,
    'clear-texture': 196630,
    'conservative-rasterization': 196629,
    'cooperative-matrix': 196667,
    'immediates': 196609,
    'mappable-primary-buffers': 196622,
    'memory-decoration-coherent': 196671,
    'memory-decoration-volatile': 196672,
    'multi-draw-indirect-count': 196612,
    'multisample-array': 196666,
    'multiview': 196632,
    'partially-bound-binding-array': 196618,
    'pipeline-cache': 196651,
    'pipeline-statistics-query': 196616,
    'polygon-mode-line': 196627,
    'polygon-mode-point': 196628,
    'ray-query': 196636,
    'sampled-texture-and-storage-buffer-array-non-uniform-indexing': 196615,
    'selective-multiview': 196664,
    'shader-barycentrics': 196663,
    'shader-draw-index': 196669,
    'shader-early-depth-test': 196640,
    'shader-f64': 196637,
    'shader-float32-atomic': 196647,
    'shader-i16': 196638,
    'shader-int64': 196646,
    'shader-int64-atomic-all-ops': 196653,
    'shader-int64-atomic-min-max': 196652,
    'shader-per-vertex': 196668,
    'storage-resource-binding-array': 196617,
    'storage-texture-array-non-uniform-indexing': 196624,
    'subgroup': 196641,
    'subgroup-barrier': 196643,
    'subgroup-vertex': 196642,
    'texture-adapter-specific-format-features': 196610,
    'texture-atomic': 196648,
    'texture-binding-array': 196614,
    'texture-compression-astc-hdr': 196620,
    'texture-format16bit-norm': 196619,
    'texture-format-nv12': 196634,
    'texture-format-p010': 196649,
    'texture-int64-atomic': 196656,
    'timestamp-query-inside-encoders': 196644,
    'timestamp-query-inside-passes': 196645,
    'vertex-attribute64bit': 196633,
    'vertex-writable-storage': 196613,
})


# C-only enums: no Web IDL counterpart, but their values are
# reported by getters such as adapter.info.
TO_INT['adapter_type'] = _EnumMap('adapter_type', {
    'discrete-gpu': 1,
    'integrated-gpu': 2,
    'cpu': 3,
    'unknown': 4,
})

TO_INT['backend_type'] = _EnumMap('backend_type', {
    'undefined': 0,
    'null': 1,
    'webgpu': 2,
    'd3d11': 3,
    'd3d12': 4,
    'metal': 5,
    'vulkan': 6,
    'opengl': 7,
    'opengles': 8,
})

TO_INT['callback_mode'] = _EnumMap('callback_mode', {
    'wait-any-only': 1,
    'allow-process-events': 2,
    'allow-spontaneous': 3,
})

TO_INT['compilation_info_request_status'] = _EnumMap('compilation_info_request_status', {
    'success': 1,
    'callback-cancelled': 2,
})

TO_INT['component_swizzle'] = _EnumMap('component_swizzle', {
    'undefined': 0,
    'zero': 1,
    'one': 2,
    'r': 3,
    'g': 4,
    'b': 5,
    'a': 6,
})

TO_INT['composite_alpha_mode'] = _EnumMap('composite_alpha_mode', {
    'auto': 0,
    'opaque': 1,
    'premultiplied': 2,
    'unpremultiplied': 3,
    'inherit': 4,
})

TO_INT['create_pipeline_async_status'] = _EnumMap('create_pipeline_async_status', {
    'success': 1,
    'callback-cancelled': 2,
    'validation-error': 3,
    'internal-error': 4,
})

TO_INT['error_type'] = _EnumMap('error_type', {
    'no-error': 1,
    'validation': 2,
    'out-of-memory': 3,
    'internal': 4,
    'unknown': 5,
})

TO_INT['feature_level'] = _EnumMap('feature_level', {
    'undefined': 0,
    'compatibility': 1,
    'core': 2,
})

TO_INT['instance_feature_name'] = _EnumMap('instance_feature_name', {
    'timed-wait-any': 1,
    'shader-source-spirv': 2,
    'multiple-devices-per-adapter': 3,
})

TO_INT['map_async_status'] = _EnumMap('map_async_status', {
    'success': 1,
    'callback-cancelled': 2,
    'error': 3,
    'aborted': 4,
})

TO_INT['optional_bool'] = _EnumMap('optional_bool', {
    'false': 0,
    'true': 1,
    'undefined': 2,
})

TO_INT['pop_error_scope_status'] = _EnumMap('pop_error_scope_status', {
    'success': 1,
    'callback-cancelled': 2,
    'error': 3,
})

TO_INT['predefined_color_space'] = _EnumMap('predefined_color_space', {
    'srgb': 1,
    'display-p3': 2,
})

TO_INT['present_mode'] = _EnumMap('present_mode', {
    'undefined': 0,
    'fifo': 1,
    'fifo-relaxed': 2,
    'immediate': 3,
    'mailbox': 4,
})

TO_INT['queue_work_done_status'] = _EnumMap('queue_work_done_status', {
    'success': 1,
    'callback-cancelled': 2,
    'error': 3,
})

TO_INT['request_adapter_status'] = _EnumMap('request_adapter_status', {
    'success': 1,
    'callback-cancelled': 2,
    'unavailable': 3,
    'error': 4,
})

TO_INT['request_device_status'] = _EnumMap('request_device_status', {
    'success': 1,
    'callback-cancelled': 2,
    'error': 3,
})

TO_INT['s_type'] = _EnumMap('s_type', {
    'shader-source-spirv': 1,
    'shader-source-wgsl': 2,
    'render-pass-max-draw-count': 3,
    'surface-source-metal-layer': 4,
    'surface-source-windows-hwnd': 5,
    'surface-source-xlib-window': 6,
    'surface-source-wayland-surface': 7,
    'surface-source-android-native-window': 8,
    'surface-source-xcb-window': 9,
    'surface-color-management': 10,
    'request-adapter-webxr-options': 11,
    'texture-component-swizzle-descriptor': 12,
    'external-texture-binding-layout': 13,
    'external-texture-binding-entry': 14,
    'compatibility-mode-limits': 15,
    'texture-binding-view-dimension': 16,
})

TO_INT['status'] = _EnumMap('status', {
    'success': 1,
    'error': 2,
})

TO_INT['surface_get_current_texture_status'] = _EnumMap('surface_get_current_texture_status', {
    'success-optimal': 1,
    'success-suboptimal': 2,
    'timeout': 3,
    'outdated': 4,
    'lost': 5,
    'error': 6,
})

TO_INT['tone_mapping_mode'] = _EnumMap('tone_mapping_mode', {
    'standard': 1,
    'extended': 2,
})

TO_INT['wait_status'] = _EnumMap('wait_status', {
    'success': 1,
    'timed-out': 2,
    'error': 3,
})

TO_INT['WGSL_language_feature_name'] = _EnumMap('WGSL_language_feature_name', {
    'readonly-and-readwrite-storage-textures': 1,
    'packed4x8-integer-dot-product': 2,
    'unrestricted-pointer-parameters': 3,
    'pointer-composite-access': 4,
    'uniform-buffer-standard-layout': 5,
    'subgroup-id': 6,
    'texture-and-sampler-let': 7,
    'subgroup-uniformity': 8,
    'texture-formats-tier1': 9,
    'linear-indexing': 10,
})


#: C-spec enum name -> mapping of C integer back to its string.
FROM_INT: dict[str, dict[int, str]] = {
    name: {i: v for v, i in table.items() if isinstance(v, str)}
    for name, table in TO_INT.items()
}
