# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Public API surface, generated from bindgen/resources/webgpu.idl (the W3C
# WebGPU Web IDL) and cross-referenced against the wgpu-native C spec. Re-run
# the generator after updating either spec.

"""WebGPU flags: integer bitmasks. ``BufferUsage.MAP_READ | BufferUsage.COPY_DST``
can also be written as ``"MAP_READ|COPY_DST"``."""

from wgpu._runtime.enumbase import EnumType as _EnumType
from wgpu._runtime.maps import FlagMap as _FlagMap


class Flags(metaclass=_EnumType):
    """Base class for wgpu flags."""

    def __init__(self):
        raise RuntimeError("Cannot instantiate a flags class.")


__all__ = [
    'BufferUsage',
    'BufferUsageFlags',
    'ColorWrite',
    'ColorWriteFlags',
    'MapMode',
    'MapModeFlags',
    'ShaderStage',
    'ShaderStageFlags',
    'TextureUsage',
    'TextureUsageFlags',
]


class BufferUsage(Flags):
    MAP_READ = 1
    MAP_WRITE = 2
    COPY_SRC = 4
    COPY_DST = 8
    INDEX = 16
    VERTEX = 32
    UNIFORM = 64
    STORAGE = 128
    INDIRECT = 256
    QUERY_RESOLVE = 512


class ColorWrite(Flags):
    RED = 1
    GREEN = 2
    BLUE = 4
    ALPHA = 8
    ALL = 15


class MapMode(Flags):
    READ = 1
    WRITE = 2


class ShaderStage(Flags):
    VERTEX = 1
    FRAGMENT = 2
    COMPUTE = 4


class TextureUsage(Flags):
    COPY_SRC = 1
    COPY_DST = 2
    TEXTURE_BINDING = 4
    STORAGE_BINDING = 8
    RENDER_ATTACHMENT = 16
    TRANSIENT_ATTACHMENT = 32


BufferUsageFlags = int | str
ColorWriteFlags = int | str
MapModeFlags = int | str
ShaderStageFlags = int | str
TextureUsageFlags = int | str

#: C-spec bitflag name -> mapping that accepts ints and 'A|B' strings.
TO_INT: dict[str, _FlagMap] = {}

TO_INT['buffer_usage'] = _FlagMap('BufferUsage', {
    'MAP_READ': 1,
    'MAP_WRITE': 2,
    'COPY_SRC': 4,
    'COPY_DST': 8,
    'INDEX': 16,
    'VERTEX': 32,
    'UNIFORM': 64,
    'STORAGE': 128,
    'INDIRECT': 256,
    'QUERY_RESOLVE': 512,
})

TO_INT['color_write_mask'] = _FlagMap('ColorWrite', {
    'RED': 1,
    'GREEN': 2,
    'BLUE': 4,
    'ALPHA': 8,
    'ALL': 15,
})

TO_INT['map_mode'] = _FlagMap('MapMode', {
    'READ': 1,
    'WRITE': 2,
})

TO_INT['shader_stage'] = _FlagMap('ShaderStage', {
    'VERTEX': 1,
    'FRAGMENT': 2,
    'COMPUTE': 4,
})

TO_INT['texture_usage'] = _FlagMap('TextureUsage', {
    'COPY_SRC': 1,
    'COPY_DST': 2,
    'TEXTURE_BINDING': 4,
    'STORAGE_BINDING': 8,
    'RENDER_ATTACHMENT': 16,
    'TRANSIENT_ATTACHMENT': 32,
})
