# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Public API surface, generated from bindgen/resources/webgpu.idl (the W3C
# WebGPU Web IDL) and cross-referenced against the wgpu-native C spec. Re-run
# the generator after updating either spec.

"""WebGPU structs, as dataclasses.

Instantiating these gives readable, type-checkable code, but every API that
accepts a struct also accepts a plain dict with the same fields.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass

from wgpu._api.types import ArrayLike, CanvasLike
from wgpu._generated import apienums as enums
from wgpu._generated import apiflags as flags
from wgpu._api.struct import Struct

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from wgpu._generated import apistructs as structs
    from wgpu._generated.apiclasses import (
        GPUBindGroupLayout,
        GPUBuffer,
        GPUDevice,
        GPUError,
        GPUPipelineLayout,
        GPUQuerySet,
        GPUSampler,
        GPUShaderModule,
        GPUTexture,
        GPUTextureView,
    )


__all__ = [
    'BindGroupDescriptor',
    'BindGroupDescriptorStruct',
    'BindGroupEntry',
    'BindGroupEntryStruct',
    'BindGroupLayoutDescriptor',
    'BindGroupLayoutDescriptorStruct',
    'BindGroupLayoutEntry',
    'BindGroupLayoutEntryStruct',
    'BlendComponent',
    'BlendComponentStruct',
    'BlendState',
    'BlendStateStruct',
    'BufferBinding',
    'BufferBindingLayout',
    'BufferBindingLayoutStruct',
    'BufferBindingStruct',
    'BufferDescriptor',
    'BufferDescriptorStruct',
    'CanvasConfiguration',
    'CanvasConfigurationStruct',
    'CanvasToneMapping',
    'CanvasToneMappingStruct',
    'Color',
    'ColorStruct',
    'ColorTargetState',
    'ColorTargetStateStruct',
    'CommandBufferDescriptor',
    'CommandBufferDescriptorStruct',
    'CommandEncoderDescriptor',
    'CommandEncoderDescriptorStruct',
    'ComputePassDescriptor',
    'ComputePassDescriptorStruct',
    'ComputePassTimestampWrites',
    'ComputePassTimestampWritesStruct',
    'ComputePipelineDescriptor',
    'ComputePipelineDescriptorStruct',
    'CopyExternalImageDestInfo',
    'CopyExternalImageDestInfoStruct',
    'CopyExternalImageSourceInfo',
    'CopyExternalImageSourceInfoStruct',
    'DepthStencilState',
    'DepthStencilStateStruct',
    'DeviceDescriptor',
    'DeviceDescriptorStruct',
    'Extent3D',
    'Extent3DStruct',
    'ExternalTextureBindingLayout',
    'ExternalTextureBindingLayoutStruct',
    'ExternalTextureDescriptor',
    'ExternalTextureDescriptorStruct',
    'FragmentState',
    'FragmentStateStruct',
    'MultisampleState',
    'MultisampleStateStruct',
    'Origin2D',
    'Origin2DStruct',
    'Origin3D',
    'Origin3DStruct',
    'PipelineErrorInit',
    'PipelineErrorInitStruct',
    'PipelineLayoutDescriptor',
    'PipelineLayoutDescriptorStruct',
    'PrimitiveState',
    'PrimitiveStateStruct',
    'ProgrammableStage',
    'ProgrammableStageStruct',
    'QuerySetDescriptor',
    'QuerySetDescriptorStruct',
    'QueueDescriptor',
    'QueueDescriptorStruct',
    'RenderBundleDescriptor',
    'RenderBundleDescriptorStruct',
    'RenderBundleEncoderDescriptor',
    'RenderBundleEncoderDescriptorStruct',
    'RenderPassColorAttachment',
    'RenderPassColorAttachmentStruct',
    'RenderPassDepthStencilAttachment',
    'RenderPassDepthStencilAttachmentStruct',
    'RenderPassDescriptor',
    'RenderPassDescriptorStruct',
    'RenderPassLayout',
    'RenderPassLayoutStruct',
    'RenderPassTimestampWrites',
    'RenderPassTimestampWritesStruct',
    'RenderPipelineDescriptor',
    'RenderPipelineDescriptorStruct',
    'RequestAdapterOptions',
    'RequestAdapterOptionsStruct',
    'SamplerBindingLayout',
    'SamplerBindingLayoutStruct',
    'SamplerDescriptor',
    'SamplerDescriptorStruct',
    'ShaderModuleCompilationHint',
    'ShaderModuleCompilationHintStruct',
    'ShaderModuleDescriptor',
    'ShaderModuleDescriptorStruct',
    'StencilFaceState',
    'StencilFaceStateStruct',
    'StorageTextureBindingLayout',
    'StorageTextureBindingLayoutStruct',
    'TexelCopyBufferInfo',
    'TexelCopyBufferInfoStruct',
    'TexelCopyBufferLayout',
    'TexelCopyBufferLayoutStruct',
    'TexelCopyTextureInfo',
    'TexelCopyTextureInfoStruct',
    'TextureBindingLayout',
    'TextureBindingLayoutStruct',
    'TextureDescriptor',
    'TextureDescriptorStruct',
    'TextureViewDescriptor',
    'TextureViewDescriptorStruct',
    'UncapturedErrorEventInit',
    'UncapturedErrorEventInitStruct',
    'VertexAttribute',
    'VertexAttributeStruct',
    'VertexBufferLayout',
    'VertexBufferLayoutStruct',
    'VertexState',
    'VertexStateStruct',
]


@dataclass(kw_only=True, repr=False)
class BindGroupDescriptor(Struct):
    label: str = ""
    layout: GPUBindGroupLayout
    entries: Sequence[structs.BindGroupEntryStruct]


BindGroupDescriptorStruct = BindGroupDescriptor | dict


@dataclass(kw_only=True, repr=False)
class BindGroupEntry(Struct):
    binding: int
    resource: GPUBuffer | GPUSampler | GPUTexture | GPUTextureView | object | structs.BufferBindingStruct


BindGroupEntryStruct = BindGroupEntry | dict


@dataclass(kw_only=True, repr=False)
class BindGroupLayoutDescriptor(Struct):
    label: str = ""
    entries: Sequence[structs.BindGroupLayoutEntryStruct]


BindGroupLayoutDescriptorStruct = BindGroupLayoutDescriptor | dict


@dataclass(kw_only=True, repr=False)
class BindGroupLayoutEntry(Struct):
    binding: int
    visibility: flags.ShaderStageFlags
    buffer: structs.BufferBindingLayoutStruct = None
    sampler: structs.SamplerBindingLayoutStruct = None
    texture: structs.TextureBindingLayoutStruct = None
    storage_texture: structs.StorageTextureBindingLayoutStruct = None
    external_texture: structs.ExternalTextureBindingLayoutStruct = None


BindGroupLayoutEntryStruct = BindGroupLayoutEntry | dict


@dataclass(kw_only=True, repr=False)
class BlendComponent(Struct):
    operation: enums.BlendOperationEnum = "add"
    src_factor: enums.BlendFactorEnum = "one"
    dst_factor: enums.BlendFactorEnum = "zero"


BlendComponentStruct = BlendComponent | dict


@dataclass(kw_only=True, repr=False)
class BlendState(Struct):
    color: structs.BlendComponentStruct
    alpha: structs.BlendComponentStruct


BlendStateStruct = BlendState | dict


@dataclass(kw_only=True, repr=False)
class BufferBinding(Struct):
    buffer: GPUBuffer
    offset: int = 0
    size: int = None


BufferBindingStruct = BufferBinding | dict


@dataclass(kw_only=True, repr=False)
class BufferBindingLayout(Struct):
    type: enums.BufferBindingTypeEnum = "uniform"
    has_dynamic_offset: bool = False
    min_binding_size: int = 0


BufferBindingLayoutStruct = BufferBindingLayout | dict


@dataclass(kw_only=True, repr=False)
class BufferDescriptor(Struct):
    label: str = ""
    size: int
    usage: flags.BufferUsageFlags
    mapped_at_creation: bool = False


BufferDescriptorStruct = BufferDescriptor | dict


@dataclass(kw_only=True, repr=False)
class CanvasConfiguration(Struct):
    device: GPUDevice
    format: enums.TextureFormatEnum
    usage: flags.TextureUsageFlags = '0x10'
    view_formats: Sequence[enums.TextureFormatEnum] = ()
    color_space: str = "srgb"
    tone_mapping: structs.CanvasToneMappingStruct = None
    alpha_mode: enums.CanvasAlphaModeEnum = "opaque"


CanvasConfigurationStruct = CanvasConfiguration | dict


@dataclass(kw_only=True, repr=False)
class CanvasToneMapping(Struct):
    mode: enums.CanvasToneMappingModeEnum = "standard"


CanvasToneMappingStruct = CanvasToneMapping | dict


@dataclass(kw_only=True, repr=False)
class Color(Struct):
    r: float
    g: float
    b: float
    a: float


ColorStruct = Color | dict


@dataclass(kw_only=True, repr=False)
class ColorTargetState(Struct):
    format: enums.TextureFormatEnum
    blend: structs.BlendStateStruct = None
    write_mask: flags.ColorWriteFlags = '0xF'


ColorTargetStateStruct = ColorTargetState | dict


@dataclass(kw_only=True, repr=False)
class CommandBufferDescriptor(Struct):
    label: str = ""


CommandBufferDescriptorStruct = CommandBufferDescriptor | dict


@dataclass(kw_only=True, repr=False)
class CommandEncoderDescriptor(Struct):
    label: str = ""


CommandEncoderDescriptorStruct = CommandEncoderDescriptor | dict


@dataclass(kw_only=True, repr=False)
class ComputePassDescriptor(Struct):
    label: str = ""
    timestamp_writes: structs.ComputePassTimestampWritesStruct = None


ComputePassDescriptorStruct = ComputePassDescriptor | dict


@dataclass(kw_only=True, repr=False)
class ComputePassTimestampWrites(Struct):
    query_set: GPUQuerySet
    beginning_of_pass_write_index: int = None
    end_of_pass_write_index: int = None


ComputePassTimestampWritesStruct = ComputePassTimestampWrites | dict


@dataclass(kw_only=True, repr=False)
class ComputePipelineDescriptor(Struct):
    label: str = ""
    layout: GPUPipelineLayout | enums.AutoLayoutModeEnum
    compute: structs.ProgrammableStageStruct


ComputePipelineDescriptorStruct = ComputePipelineDescriptor | dict


@dataclass(kw_only=True, repr=False)
class CopyExternalImageDestInfo(Struct):
    texture: GPUTexture
    mip_level: int = 0
    origin: tuple[int, int, int] | structs.Origin3DStruct = None
    aspect: enums.TextureAspectEnum = "all"
    color_space: str = "srgb"
    premultiplied_alpha: bool = False


CopyExternalImageDestInfoStruct = CopyExternalImageDestInfo | dict


@dataclass(kw_only=True, repr=False)
class CopyExternalImageSourceInfo(Struct):
    source: ArrayLike | CanvasLike | object
    origin: tuple[int, int] | structs.Origin2DStruct = None
    flip_y: bool = False


CopyExternalImageSourceInfoStruct = CopyExternalImageSourceInfo | dict


@dataclass(kw_only=True, repr=False)
class DepthStencilState(Struct):
    format: enums.TextureFormatEnum
    depth_write_enabled: bool = None
    depth_compare: enums.CompareFunctionEnum = None
    stencil_front: structs.StencilFaceStateStruct = None
    stencil_back: structs.StencilFaceStateStruct = None
    stencil_read_mask: int = '0xFFFFFFFF'
    stencil_write_mask: int = '0xFFFFFFFF'
    depth_bias: int = 0
    depth_bias_slope_scale: float = 0
    depth_bias_clamp: float = 0


DepthStencilStateStruct = DepthStencilState | dict


@dataclass(kw_only=True, repr=False)
class DeviceDescriptor(Struct):
    label: str = ""
    required_features: Sequence[enums.FeatureNameEnum] = ()
    required_limits: dict[str, int | None] = None
    default_queue: structs.QueueDescriptorStruct = None


DeviceDescriptorStruct = DeviceDescriptor | dict


@dataclass(kw_only=True, repr=False)
class Extent3D(Struct):
    width: int
    height: int = 1
    depth_or_array_layers: int = 1


Extent3DStruct = Extent3D | dict


@dataclass(kw_only=True, repr=False)
class ExternalTextureBindingLayout(Struct):
    pass


ExternalTextureBindingLayoutStruct = ExternalTextureBindingLayout | dict


@dataclass(kw_only=True, repr=False)
class ExternalTextureDescriptor(Struct):
    label: str = ""
    source: ArrayLike | object
    color_space: str = "srgb"


ExternalTextureDescriptorStruct = ExternalTextureDescriptor | dict


@dataclass(kw_only=True, repr=False)
class FragmentState(Struct):
    module: GPUShaderModule
    entry_point: str = None
    constants: dict[str, float] = None
    targets: Sequence[structs.ColorTargetStateStruct]


FragmentStateStruct = FragmentState | dict


@dataclass(kw_only=True, repr=False)
class MultisampleState(Struct):
    count: int = 1
    mask: int = '0xFFFFFFFF'
    alpha_to_coverage_enabled: bool = False


MultisampleStateStruct = MultisampleState | dict


@dataclass(kw_only=True, repr=False)
class Origin2D(Struct):
    x: int = 0
    y: int = 0


Origin2DStruct = Origin2D | dict


@dataclass(kw_only=True, repr=False)
class Origin3D(Struct):
    x: int = 0
    y: int = 0
    z: int = 0


Origin3DStruct = Origin3D | dict


@dataclass(kw_only=True, repr=False)
class PipelineErrorInit(Struct):
    reason: enums.PipelineErrorReasonEnum


PipelineErrorInitStruct = PipelineErrorInit | dict


@dataclass(kw_only=True, repr=False)
class PipelineLayoutDescriptor(Struct):
    label: str = ""
    bind_group_layouts: Sequence[GPUBindGroupLayout]
    immediate_size: int = 0


PipelineLayoutDescriptorStruct = PipelineLayoutDescriptor | dict


@dataclass(kw_only=True, repr=False)
class PrimitiveState(Struct):
    topology: enums.PrimitiveTopologyEnum = "triangle-list"
    strip_index_format: enums.IndexFormatEnum = None
    front_face: enums.FrontFaceEnum = "ccw"
    cull_mode: enums.CullModeEnum = "none"
    unclipped_depth: bool = False


PrimitiveStateStruct = PrimitiveState | dict


@dataclass(kw_only=True, repr=False)
class ProgrammableStage(Struct):
    module: GPUShaderModule
    entry_point: str = None
    constants: dict[str, float] = None


ProgrammableStageStruct = ProgrammableStage | dict


@dataclass(kw_only=True, repr=False)
class QuerySetDescriptor(Struct):
    label: str = ""
    type: enums.QueryTypeEnum
    count: int


QuerySetDescriptorStruct = QuerySetDescriptor | dict


@dataclass(kw_only=True, repr=False)
class QueueDescriptor(Struct):
    label: str = ""


QueueDescriptorStruct = QueueDescriptor | dict


@dataclass(kw_only=True, repr=False)
class RenderBundleDescriptor(Struct):
    label: str = ""


RenderBundleDescriptorStruct = RenderBundleDescriptor | dict


@dataclass(kw_only=True, repr=False)
class RenderBundleEncoderDescriptor(Struct):
    label: str = ""
    color_formats: Sequence[enums.TextureFormatEnum]
    depth_stencil_format: enums.TextureFormatEnum = None
    sample_count: int = 1
    depth_read_only: bool = False
    stencil_read_only: bool = False


RenderBundleEncoderDescriptorStruct = RenderBundleEncoderDescriptor | dict


@dataclass(kw_only=True, repr=False)
class RenderPassColorAttachment(Struct):
    view: GPUTexture | GPUTextureView
    depth_slice: int = None
    resolve_target: GPUTexture | GPUTextureView = None
    clear_value: tuple[float, float, float, float] | structs.ColorStruct = None
    load_op: enums.LoadOpEnum
    store_op: enums.StoreOpEnum


RenderPassColorAttachmentStruct = RenderPassColorAttachment | dict


@dataclass(kw_only=True, repr=False)
class RenderPassDepthStencilAttachment(Struct):
    view: GPUTexture | GPUTextureView
    depth_clear_value: float = None
    depth_load_op: enums.LoadOpEnum = None
    depth_store_op: enums.StoreOpEnum = None
    depth_read_only: bool = False
    stencil_clear_value: int = 0
    stencil_load_op: enums.LoadOpEnum = None
    stencil_store_op: enums.StoreOpEnum = None
    stencil_read_only: bool = False


RenderPassDepthStencilAttachmentStruct = RenderPassDepthStencilAttachment | dict


@dataclass(kw_only=True, repr=False)
class RenderPassDescriptor(Struct):
    label: str = ""
    color_attachments: Sequence[structs.RenderPassColorAttachmentStruct]
    depth_stencil_attachment: structs.RenderPassDepthStencilAttachmentStruct = None
    occlusion_query_set: GPUQuerySet = None
    timestamp_writes: structs.RenderPassTimestampWritesStruct = None
    max_draw_count: int = 50000000


RenderPassDescriptorStruct = RenderPassDescriptor | dict


@dataclass(kw_only=True, repr=False)
class RenderPassLayout(Struct):
    label: str = ""
    color_formats: Sequence[enums.TextureFormatEnum]
    depth_stencil_format: enums.TextureFormatEnum = None
    sample_count: int = 1


RenderPassLayoutStruct = RenderPassLayout | dict


@dataclass(kw_only=True, repr=False)
class RenderPassTimestampWrites(Struct):
    query_set: GPUQuerySet
    beginning_of_pass_write_index: int = None
    end_of_pass_write_index: int = None


RenderPassTimestampWritesStruct = RenderPassTimestampWrites | dict


@dataclass(kw_only=True, repr=False)
class RenderPipelineDescriptor(Struct):
    label: str = ""
    layout: GPUPipelineLayout | enums.AutoLayoutModeEnum
    vertex: structs.VertexStateStruct
    primitive: structs.PrimitiveStateStruct = None
    depth_stencil: structs.DepthStencilStateStruct = None
    multisample: structs.MultisampleStateStruct = None
    fragment: structs.FragmentStateStruct = None


RenderPipelineDescriptorStruct = RenderPipelineDescriptor | dict


@dataclass(kw_only=True, repr=False)
class RequestAdapterOptions(Struct):
    feature_level: str = "core"
    power_preference: enums.PowerPreferenceEnum = None
    force_fallback_adapter: bool = False
    xr_compatible: bool = False


RequestAdapterOptionsStruct = RequestAdapterOptions | dict


@dataclass(kw_only=True, repr=False)
class SamplerBindingLayout(Struct):
    type: enums.SamplerBindingTypeEnum = "filtering"


SamplerBindingLayoutStruct = SamplerBindingLayout | dict


@dataclass(kw_only=True, repr=False)
class SamplerDescriptor(Struct):
    label: str = ""
    address_mode_u: enums.AddressModeEnum = "clamp-to-edge"
    address_mode_v: enums.AddressModeEnum = "clamp-to-edge"
    address_mode_w: enums.AddressModeEnum = "clamp-to-edge"
    mag_filter: enums.FilterModeEnum = "nearest"
    min_filter: enums.FilterModeEnum = "nearest"
    mipmap_filter: enums.MipmapFilterModeEnum = "nearest"
    lod_min_clamp: float = 0
    lod_max_clamp: float = 32
    compare: enums.CompareFunctionEnum = None
    max_anisotropy: int = 1


SamplerDescriptorStruct = SamplerDescriptor | dict


@dataclass(kw_only=True, repr=False)
class ShaderModuleCompilationHint(Struct):
    entry_point: str
    layout: GPUPipelineLayout | enums.AutoLayoutModeEnum = None


ShaderModuleCompilationHintStruct = ShaderModuleCompilationHint | dict


@dataclass(kw_only=True, repr=False)
class ShaderModuleDescriptor(Struct):
    label: str = ""
    code: str
    compilation_hints: Sequence[structs.ShaderModuleCompilationHintStruct] = ()


ShaderModuleDescriptorStruct = ShaderModuleDescriptor | dict


@dataclass(kw_only=True, repr=False)
class StencilFaceState(Struct):
    compare: enums.CompareFunctionEnum = "always"
    fail_op: enums.StencilOperationEnum = "keep"
    depth_fail_op: enums.StencilOperationEnum = "keep"
    pass_op: enums.StencilOperationEnum = "keep"


StencilFaceStateStruct = StencilFaceState | dict


@dataclass(kw_only=True, repr=False)
class StorageTextureBindingLayout(Struct):
    access: enums.StorageTextureAccessEnum = "write-only"
    format: enums.TextureFormatEnum
    view_dimension: enums.TextureViewDimensionEnum = "2d"


StorageTextureBindingLayoutStruct = StorageTextureBindingLayout | dict


@dataclass(kw_only=True, repr=False)
class TexelCopyBufferInfo(Struct):
    offset: int = 0
    bytes_per_row: int = None
    rows_per_image: int = None
    buffer: GPUBuffer


TexelCopyBufferInfoStruct = TexelCopyBufferInfo | dict


@dataclass(kw_only=True, repr=False)
class TexelCopyBufferLayout(Struct):
    offset: int = 0
    bytes_per_row: int = None
    rows_per_image: int = None


TexelCopyBufferLayoutStruct = TexelCopyBufferLayout | dict


@dataclass(kw_only=True, repr=False)
class TexelCopyTextureInfo(Struct):
    texture: GPUTexture
    mip_level: int = 0
    origin: tuple[int, int, int] | structs.Origin3DStruct = None
    aspect: enums.TextureAspectEnum = "all"


TexelCopyTextureInfoStruct = TexelCopyTextureInfo | dict


@dataclass(kw_only=True, repr=False)
class TextureBindingLayout(Struct):
    sample_type: enums.TextureSampleTypeEnum = "float"
    view_dimension: enums.TextureViewDimensionEnum = "2d"
    multisampled: bool = False


TextureBindingLayoutStruct = TextureBindingLayout | dict


@dataclass(kw_only=True, repr=False)
class TextureDescriptor(Struct):
    label: str = ""
    size: tuple[int, int, int] | structs.Extent3DStruct
    mip_level_count: int = 1
    sample_count: int = 1
    dimension: enums.TextureDimensionEnum = "2d"
    format: enums.TextureFormatEnum
    usage: flags.TextureUsageFlags
    view_formats: Sequence[enums.TextureFormatEnum] = ()
    texture_binding_view_dimension: enums.TextureViewDimensionEnum = None


TextureDescriptorStruct = TextureDescriptor | dict


@dataclass(kw_only=True, repr=False)
class TextureViewDescriptor(Struct):
    label: str = ""
    format: enums.TextureFormatEnum = None
    dimension: enums.TextureViewDimensionEnum = None
    usage: flags.TextureUsageFlags = 0
    aspect: enums.TextureAspectEnum = "all"
    base_mip_level: int = 0
    mip_level_count: int = None
    base_array_layer: int = 0
    array_layer_count: int = None
    swizzle: str = "rgba"


TextureViewDescriptorStruct = TextureViewDescriptor | dict


@dataclass(kw_only=True, repr=False)
class UncapturedErrorEventInit(Struct):
    error: GPUError


UncapturedErrorEventInitStruct = UncapturedErrorEventInit | dict


@dataclass(kw_only=True, repr=False)
class VertexAttribute(Struct):
    format: enums.VertexFormatEnum
    offset: int
    shader_location: int


VertexAttributeStruct = VertexAttribute | dict


@dataclass(kw_only=True, repr=False)
class VertexBufferLayout(Struct):
    array_stride: int
    step_mode: enums.VertexStepModeEnum = "vertex"
    attributes: Sequence[structs.VertexAttributeStruct]


VertexBufferLayoutStruct = VertexBufferLayout | dict


@dataclass(kw_only=True, repr=False)
class VertexState(Struct):
    module: GPUShaderModule
    entry_point: str = None
    constants: dict[str, float] = None
    buffers: Sequence[structs.VertexBufferLayoutStruct] = ()


VertexStateStruct = VertexState | dict
