# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Source of truth: wgpu-native/ffi/webgpu-headers/webgpu.json (the machine-
# readable WebGPU spec) plus the compiled extension for enum values. Re-run the
# generator after bumping the wgpu-native submodule.

"""Generated ``GPU*`` wrapper classes for wgpu-native objects."""

from wgpu._runtime.base import GPUObjectBase

class GPUAdapter(GPUObjectBase):
    _spec_name = 'adapter'

    def get_limits(self, limits):
        return self._invoke('get_limits', limits)

    def has_feature(self, feature):
        return self._invoke('has_feature', feature)

    def get_features(self, features):
        """Get the list of @ref WGPUFeatureName values supported by the adapter."""
        return self._invoke('get_features', features)

    def get_info(self, info):
        return self._invoke('get_info', info)

    def request_device(self, descriptor=None):
        return self._invoke('request_device', descriptor)


class GPUBindGroup(GPUObjectBase):
    _spec_name = 'bind_group'

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPUBindGroupLayout(GPUObjectBase):
    _spec_name = 'bind_group_layout'

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPUBuffer(GPUObjectBase):
    _spec_name = 'buffer'

    def map_async(self, mode, offset, size):
        return self._invoke('map_async', mode, offset, size)

    def get_mapped_range(self, offset, size):
        """
        Returns a mutable pointer to beginning of the mapped range.
        See @ref MappedRangeBehavior for error conditions and guarantees.
        This function is safe to call inside spontaneous callbacks (see @ref CallbackReentrancy).

        In Wasm, if `memcpy`ing into this range, prefer using @ref wgpuBufferWriteMappedRange
        instead for better performance.
        """
        return self._invoke('get_mapped_range', offset, size)

    def get_const_mapped_range(self, offset, size):
        """
        Returns a const pointer to beginning of the mapped range.
        It must not be written; writing to this range causes undefined behavior.
        See @ref MappedRangeBehavior for error conditions and guarantees.
        This function is safe to call inside spontaneous callbacks (see @ref CallbackReentrancy).

        In Wasm, if `memcpy`ing from this range, prefer using @ref wgpuBufferReadMappedRange
        instead for better performance.
        """
        return self._invoke('get_const_mapped_range', offset, size)

    def read_mapped_range(self, offset, data, size):
        """
        Copies a range of data from the buffer mapping into the provided destination pointer.
        See @ref MappedRangeBehavior for error conditions and guarantees.
        This function is safe to call inside spontaneous callbacks (see @ref CallbackReentrancy).

        In Wasm, this is more efficient than copying from a mapped range into a `malloc`'d range.
        """
        return self._invoke('read_mapped_range', offset, data, size)

    def write_mapped_range(self, offset, data, size):
        """
        Copies a range of data from the provided source pointer into the buffer mapping.
        See @ref MappedRangeBehavior for error conditions and guarantees.
        This function is safe to call inside spontaneous callbacks (see @ref CallbackReentrancy).

        In Wasm, this is more efficient than copying from a `malloc`'d range into a mapped range.
        """
        return self._invoke('write_mapped_range', offset, data, size)

    def set_label(self, label):
        return self._invoke('set_label', label)

    def get_usage(self):
        return self._invoke('get_usage')

    def get_size(self):
        return self._invoke('get_size')

    def get_map_state(self):
        return self._invoke('get_map_state')

    def unmap(self):
        return self._invoke('unmap')

    def destroy(self):
        return self._invoke('destroy')


class GPUCommandBuffer(GPUObjectBase):
    _spec_name = 'command_buffer'

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPUCommandEncoder(GPUObjectBase):
    _spec_name = 'command_encoder'

    def finish(self, descriptor=None):
        return self._invoke('finish', descriptor)

    def begin_compute_pass(self, descriptor=None):
        return self._invoke('begin_compute_pass', descriptor)

    def begin_render_pass(self, descriptor):
        return self._invoke('begin_render_pass', descriptor)

    def copy_buffer_to_buffer(self, source, source_offset, destination, destination_offset, size):
        return self._invoke('copy_buffer_to_buffer', source, source_offset, destination, destination_offset, size)

    def copy_buffer_to_texture(self, source, destination, copy_size):
        return self._invoke('copy_buffer_to_texture', source, destination, copy_size)

    def copy_texture_to_buffer(self, source, destination, copy_size):
        return self._invoke('copy_texture_to_buffer', source, destination, copy_size)

    def copy_texture_to_texture(self, source, destination, copy_size):
        return self._invoke('copy_texture_to_texture', source, destination, copy_size)

    def clear_buffer(self, buffer, offset, size):
        return self._invoke('clear_buffer', buffer, offset, size)

    def insert_debug_marker(self, marker_label):
        return self._invoke('insert_debug_marker', marker_label)

    def pop_debug_group(self):
        return self._invoke('pop_debug_group')

    def push_debug_group(self, group_label):
        return self._invoke('push_debug_group', group_label)

    def resolve_query_set(self, query_set, first_query, query_count, destination, destination_offset):
        return self._invoke('resolve_query_set', query_set, first_query, query_count, destination, destination_offset)

    def write_timestamp(self, query_set, query_index):
        return self._invoke('write_timestamp', query_set, query_index)

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPUComputePassEncoder(GPUObjectBase):
    _spec_name = 'compute_pass_encoder'

    def insert_debug_marker(self, marker_label):
        return self._invoke('insert_debug_marker', marker_label)

    def pop_debug_group(self):
        return self._invoke('pop_debug_group')

    def push_debug_group(self, group_label):
        return self._invoke('push_debug_group', group_label)

    def set_pipeline(self, pipeline):
        return self._invoke('set_pipeline', pipeline)

    def set_bind_group(self, group_index, group, dynamic_offsets):
        return self._invoke('set_bind_group', group_index, group, dynamic_offsets)

    def set_immediates(self, offset, data, size):
        return self._invoke('set_immediates', offset, data, size)

    def dispatch_workgroups(self, workgroupCountX, workgroupCountY, workgroupCountZ):
        return self._invoke('dispatch_workgroups', workgroupCountX, workgroupCountY, workgroupCountZ)

    def dispatch_workgroups_indirect(self, indirect_buffer, indirect_offset):
        return self._invoke('dispatch_workgroups_indirect', indirect_buffer, indirect_offset)

    def end(self):
        return self._invoke('end')

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPUComputePipeline(GPUObjectBase):
    _spec_name = 'compute_pipeline'

    def get_bind_group_layout(self, group_index):
        return self._invoke('get_bind_group_layout', group_index)

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPUDevice(GPUObjectBase):
    _spec_name = 'device'

    def create_bind_group(self, descriptor):
        return self._invoke('create_bind_group', descriptor)

    def create_bind_group_layout(self, descriptor):
        return self._invoke('create_bind_group_layout', descriptor)

    def create_buffer(self, descriptor):
        """
        TODO

        If @ref WGPUBufferDescriptor::mappedAtCreation is `true` and the mapping allocation fails,
        returns `NULL`.
        """
        return self._invoke('create_buffer', descriptor)

    def create_command_encoder(self, descriptor=None):
        return self._invoke('create_command_encoder', descriptor)

    def create_compute_pipeline(self, descriptor):
        return self._invoke('create_compute_pipeline', descriptor)

    def create_compute_pipeline_async(self, descriptor):
        return self._invoke('create_compute_pipeline_async', descriptor)

    def create_pipeline_layout(self, descriptor):
        return self._invoke('create_pipeline_layout', descriptor)

    def create_query_set(self, descriptor):
        return self._invoke('create_query_set', descriptor)

    def create_render_pipeline_async(self, descriptor):
        return self._invoke('create_render_pipeline_async', descriptor)

    def create_render_bundle_encoder(self, descriptor):
        return self._invoke('create_render_bundle_encoder', descriptor)

    def create_render_pipeline(self, descriptor):
        return self._invoke('create_render_pipeline', descriptor)

    def create_sampler(self, descriptor=None):
        return self._invoke('create_sampler', descriptor)

    def create_shader_module(self, descriptor):
        return self._invoke('create_shader_module', descriptor)

    def create_texture(self, descriptor):
        return self._invoke('create_texture', descriptor)

    def destroy(self):
        return self._invoke('destroy')

    def get_lost_future(self):
        return self._invoke('get_lost_future')

    def get_limits(self, limits):
        return self._invoke('get_limits', limits)

    def has_feature(self, feature):
        return self._invoke('has_feature', feature)

    def get_features(self, features):
        """Get the list of @ref WGPUFeatureName values supported by the device."""
        return self._invoke('get_features', features)

    def get_adapter_info(self, adapter_info):
        return self._invoke('get_adapter_info', adapter_info)

    def get_queue(self):
        return self._invoke('get_queue')

    def push_error_scope(self, filter):
        """
        Pushes an error scope to the current thread's error scope stack.
        See @ref ErrorScopes.
        """
        return self._invoke('push_error_scope', filter)

    def pop_error_scope(self):
        """
        Pops an error scope to the current thread's error scope stack,
        asynchronously returning the result. See @ref ErrorScopes.
        """
        return self._invoke('pop_error_scope')

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPUExternalTexture(GPUObjectBase):
    _spec_name = 'external_texture'

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPUInstance(GPUObjectBase):
    _spec_name = 'instance'

    def create_surface(self, descriptor):
        """Creates a @ref WGPUSurface, see @ref Surface-Creation for more details."""
        return self._invoke('create_surface', descriptor)

    def get_WGSL_language_features(self, features):
        """Get the list of @ref WGPUWGSLLanguageFeatureName values supported by the instance."""
        return self._invoke('get_WGSL_language_features', features)

    def has_WGSL_language_feature(self, feature):
        return self._invoke('has_WGSL_language_feature', feature)

    def process_events(self):
        """
        Processes asynchronous events on this `WGPUInstance`, calling any callbacks for asynchronous operations created with @ref WGPUCallbackMode_AllowProcessEvents.

        See @ref Process-Events for more information.
        """
        return self._invoke('process_events')

    def request_adapter(self, options=None):
        return self._invoke('request_adapter', options)

    def wait_any(self, future_count, futures, timeout_NS):
        """
        Wait for at least one WGPUFuture in `futures` to complete, and call callbacks of the respective completed asynchronous operations.

        See @ref Wait-Any for more information.
        """
        return self._invoke('wait_any', future_count, futures, timeout_NS)


class GPUPipelineLayout(GPUObjectBase):
    _spec_name = 'pipeline_layout'

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPUQuerySet(GPUObjectBase):
    _spec_name = 'query_set'

    def set_label(self, label):
        return self._invoke('set_label', label)

    def get_type(self):
        return self._invoke('get_type')

    def get_count(self):
        return self._invoke('get_count')

    def destroy(self):
        return self._invoke('destroy')


class GPUQueue(GPUObjectBase):
    _spec_name = 'queue'

    def submit(self, commands):
        return self._invoke('submit', commands)

    def on_submitted_work_done(self):
        return self._invoke('on_submitted_work_done')

    def write_buffer(self, buffer, buffer_offset, data, size):
        """
        Produces a @ref DeviceError both content-timeline (`size` alignment) and device-timeline
        errors defined by the WebGPU specification.
        """
        return self._invoke('write_buffer', buffer, buffer_offset, data, size)

    def write_texture(self, destination, data, data_size, data_layout, write_size):
        return self._invoke('write_texture', destination, data, data_size, data_layout, write_size)

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPURenderBundle(GPUObjectBase):
    _spec_name = 'render_bundle'

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPURenderBundleEncoder(GPUObjectBase):
    _spec_name = 'render_bundle_encoder'

    def set_pipeline(self, pipeline):
        return self._invoke('set_pipeline', pipeline)

    def set_bind_group(self, group_index, group, dynamic_offsets):
        return self._invoke('set_bind_group', group_index, group, dynamic_offsets)

    def set_immediates(self, offset, data, size):
        return self._invoke('set_immediates', offset, data, size)

    def draw(self, vertex_count, instance_count, first_vertex, first_instance):
        return self._invoke('draw', vertex_count, instance_count, first_vertex, first_instance)

    def draw_indexed(self, index_count, instance_count, first_index, base_vertex, first_instance):
        return self._invoke('draw_indexed', index_count, instance_count, first_index, base_vertex, first_instance)

    def draw_indirect(self, indirect_buffer, indirect_offset):
        return self._invoke('draw_indirect', indirect_buffer, indirect_offset)

    def draw_indexed_indirect(self, indirect_buffer, indirect_offset):
        return self._invoke('draw_indexed_indirect', indirect_buffer, indirect_offset)

    def insert_debug_marker(self, marker_label):
        return self._invoke('insert_debug_marker', marker_label)

    def pop_debug_group(self):
        return self._invoke('pop_debug_group')

    def push_debug_group(self, group_label):
        return self._invoke('push_debug_group', group_label)

    def set_vertex_buffer(self, slot, buffer, offset, size):
        return self._invoke('set_vertex_buffer', slot, buffer, offset, size)

    def set_index_buffer(self, buffer, format, offset, size):
        return self._invoke('set_index_buffer', buffer, format, offset, size)

    def finish(self, descriptor=None):
        return self._invoke('finish', descriptor)

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPURenderPassEncoder(GPUObjectBase):
    _spec_name = 'render_pass_encoder'

    def set_pipeline(self, pipeline):
        return self._invoke('set_pipeline', pipeline)

    def set_bind_group(self, group_index, group, dynamic_offsets):
        return self._invoke('set_bind_group', group_index, group, dynamic_offsets)

    def set_immediates(self, offset, data, size):
        return self._invoke('set_immediates', offset, data, size)

    def draw(self, vertex_count, instance_count, first_vertex, first_instance):
        return self._invoke('draw', vertex_count, instance_count, first_vertex, first_instance)

    def draw_indexed(self, index_count, instance_count, first_index, base_vertex, first_instance):
        return self._invoke('draw_indexed', index_count, instance_count, first_index, base_vertex, first_instance)

    def draw_indirect(self, indirect_buffer, indirect_offset):
        return self._invoke('draw_indirect', indirect_buffer, indirect_offset)

    def draw_indexed_indirect(self, indirect_buffer, indirect_offset):
        return self._invoke('draw_indexed_indirect', indirect_buffer, indirect_offset)

    def execute_bundles(self, bundles):
        return self._invoke('execute_bundles', bundles)

    def insert_debug_marker(self, marker_label):
        return self._invoke('insert_debug_marker', marker_label)

    def pop_debug_group(self):
        return self._invoke('pop_debug_group')

    def push_debug_group(self, group_label):
        return self._invoke('push_debug_group', group_label)

    def set_stencil_reference(self, reference):
        return self._invoke('set_stencil_reference', reference)

    def set_blend_constant(self, color):
        return self._invoke('set_blend_constant', color)

    def set_viewport(self, x, y, width, height, min_depth, max_depth):
        """
        TODO

        If any argument is non-finite, produces a @ref NonFiniteFloatValueError.
        """
        return self._invoke('set_viewport', x, y, width, height, min_depth, max_depth)

    def set_scissor_rect(self, x, y, width, height):
        return self._invoke('set_scissor_rect', x, y, width, height)

    def set_vertex_buffer(self, slot, buffer, offset, size):
        return self._invoke('set_vertex_buffer', slot, buffer, offset, size)

    def set_index_buffer(self, buffer, format, offset, size):
        return self._invoke('set_index_buffer', buffer, format, offset, size)

    def begin_occlusion_query(self, query_index):
        return self._invoke('begin_occlusion_query', query_index)

    def end_occlusion_query(self):
        return self._invoke('end_occlusion_query')

    def end(self):
        return self._invoke('end')

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPURenderPipeline(GPUObjectBase):
    _spec_name = 'render_pipeline'

    def get_bind_group_layout(self, group_index):
        return self._invoke('get_bind_group_layout', group_index)

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPUSampler(GPUObjectBase):
    _spec_name = 'sampler'

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPUShaderModule(GPUObjectBase):
    _spec_name = 'shader_module'

    def get_compilation_info(self):
        return self._invoke('get_compilation_info')

    def set_label(self, label):
        return self._invoke('set_label', label)


class GPUSurface(GPUObjectBase):
    _spec_name = 'surface'

    def configure(self, config):
        """
        Configures parameters for rendering to `surface`.
        Produces a @ref DeviceError for all content-timeline errors defined by the WebGPU specification.

        See @ref Surface-Configuration for more details.
        """
        return self._invoke('configure', config)

    def get_capabilities(self, adapter, capabilities):
        """
        Provides information on how `adapter` is able to use `surface`.
        See @ref Surface-Capabilities for more details.
        """
        return self._invoke('get_capabilities', adapter, capabilities)

    def get_current_texture(self, surface_texture):
        """
        Returns the @ref WGPUTexture to render to `surface` this frame along with metadata on the frame.
        Returns `NULL` and @ref WGPUSurfaceGetCurrentTextureStatus_Error if the surface is not configured.

        See @ref Surface-Presenting for more details.
        """
        return self._invoke('get_current_texture', surface_texture)

    def present(self):
        """
        Shows `surface`'s current texture to the user.
        See @ref Surface-Presenting for more details.
        """
        return self._invoke('present')

    def unconfigure(self):
        """
        Removes the configuration for `surface`.
        See @ref Surface-Configuration for more details.
        """
        return self._invoke('unconfigure')

    def set_label(self, label):
        """Modifies the label used to refer to `surface`."""
        return self._invoke('set_label', label)


class GPUTexture(GPUObjectBase):
    _spec_name = 'texture'

    def create_view(self, descriptor=None):
        return self._invoke('create_view', descriptor)

    def set_label(self, label):
        return self._invoke('set_label', label)

    def get_width(self):
        return self._invoke('get_width')

    def get_height(self):
        return self._invoke('get_height')

    def get_depth_or_array_layers(self):
        return self._invoke('get_depth_or_array_layers')

    def get_mip_level_count(self):
        return self._invoke('get_mip_level_count')

    def get_sample_count(self):
        return self._invoke('get_sample_count')

    def get_dimension(self):
        return self._invoke('get_dimension')

    def get_texture_binding_view_dimension(self):
        return self._invoke('get_texture_binding_view_dimension')

    def get_format(self):
        return self._invoke('get_format')

    def get_usage(self):
        return self._invoke('get_usage')

    def destroy(self):
        return self._invoke('destroy')


class GPUTextureView(GPUObjectBase):
    _spec_name = 'texture_view'

    def set_label(self, label):
        return self._invoke('set_label', label)

