# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Source of truth: wgpu-native/ffi/webgpu-headers/webgpu.json (the machine-
# readable WebGPU spec) plus the compiled extension for enum values. Re-run the
# generator after bumping the wgpu-native submodule.

"""``GPU*`` classes for wgpu-native objects with no Web IDL counterpart."""

from wgpu._api.base import GPUObjectBase

class GPUExternalTexture(GPUObjectBase):
    _spec_name = 'external_texture'

    def set_label(self, label):
        return self._call('set_label', label)


class GPUInstance(GPUObjectBase):
    _spec_name = 'instance'

    def create_surface(self, descriptor):
        """Creates a @ref WGPUSurface, see @ref Surface-Creation for more details."""
        return self._call('create_surface', descriptor)

    def get_WGSL_language_features(self, features):
        """Get the list of @ref WGPUWGSLLanguageFeatureName values supported by the instance."""
        return self._call('get_WGSL_language_features', features)

    def has_WGSL_language_feature(self, feature):
        return self._call('has_WGSL_language_feature', feature)

    def process_events(self):
        """
        Processes asynchronous events on this `WGPUInstance`, calling any callbacks for asynchronous operations created with @ref WGPUCallbackMode_AllowProcessEvents.

        See @ref Process-Events for more information.
        """
        return self._call('process_events')

    def request_adapter(self, options=None):
        return self._call('request_adapter', options)

    def wait_any(self, future_count, futures, timeout_NS):
        """
        Wait for at least one WGPUFuture in `futures` to complete, and call callbacks of the respective completed asynchronous operations.

        See @ref Wait-Any for more information.
        """
        return self._call('wait_any', future_count, futures, timeout_NS)


class GPUSurface(GPUObjectBase):
    _spec_name = 'surface'

    def configure(self, config):
        """
        Configures parameters for rendering to `surface`.
        Produces a @ref DeviceError for all content-timeline errors defined by the WebGPU specification.

        See @ref Surface-Configuration for more details.
        """
        return self._call('configure', config)

    def get_capabilities(self, adapter, capabilities):
        """
        Provides information on how `adapter` is able to use `surface`.
        See @ref Surface-Capabilities for more details.
        """
        return self._call('get_capabilities', adapter, capabilities)

    def get_current_texture(self, surface_texture):
        """
        Returns the @ref WGPUTexture to render to `surface` this frame along with metadata on the frame.
        Returns `NULL` and @ref WGPUSurfaceGetCurrentTextureStatus_Error if the surface is not configured.

        See @ref Surface-Presenting for more details.
        """
        return self._call('get_current_texture', surface_texture)

    def present(self):
        """
        Shows `surface`'s current texture to the user.
        See @ref Surface-Presenting for more details.
        """
        return self._call('present')

    def unconfigure(self):
        """
        Removes the configuration for `surface`.
        See @ref Surface-Configuration for more details.
        """
        return self._call('unconfigure')

    def set_label(self, label):
        """Modifies the label used to refer to `surface`."""
        return self._call('set_label', label)

