# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Source of truth: wgpu-native/ffi/webgpu-headers/webgpu.json (the machine-
# readable WebGPU spec) plus the compiled extension for enum values. Re-run the
# generator after bumping the wgpu-native submodule.

"""WebGPU sentinel constants (e.g. WHOLE_SIZE), from webgpu.json."""

from wgpu._native import ffi as _ffi

_SIZE_T_MAX = (1 << (8 * _ffi.sizeof('size_t'))) - 1

array_layer_count_undefined = 0xFFFFFFFF
copy_stride_undefined = 0xFFFFFFFF
depth_clear_value_undefined = float("nan")
depth_slice_undefined = 0xFFFFFFFF
limit_u32_undefined = 0xFFFFFFFF
limit_u64_undefined = 0xFFFFFFFFFFFFFFFF
mip_level_count_undefined = 0xFFFFFFFF
query_set_index_undefined = 0xFFFFFFFF
strlen = _SIZE_T_MAX
whole_map_size = _SIZE_T_MAX
whole_size = 0xFFFFFFFFFFFFFFFF

#: The wgpu-native release this package was generated against.
WGPU_NATIVE_VERSION = '29.0.1.1'

#: The exact wgpu-native commit compiled into this package.
#: Statically linked, so there is no library file to ask later.
WGPU_NATIVE_COMMIT_SHA = '6aed50955d934ac36049ba8d002034841633ae02'
