# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Source of truth: wgpu-native/ffi/webgpu-headers/webgpu.json (the machine-
# readable WebGPU spec) plus the compiled extension for enum values. Re-run the
# generator after bumping the wgpu-native submodule.

import enum


class AdapterType(enum.IntEnum):
    discrete_GPU = 1
    integrated_GPU = 2
    CPU = 3
    unknown = 4


class AddressMode(enum.IntEnum):
    undefined = 0
    clamp_to_edge = 1
    repeat = 2
    mirror_repeat = 3


class BackendType(enum.IntEnum):
    undefined = 0
    null = 1
    WebGPU = 2
    D3D11 = 3
    D3D12 = 4
    metal = 5
    vulkan = 6
    openGL = 7
    openGLES = 8


class BlendFactor(enum.IntEnum):
    undefined = 0
    zero = 1
    one = 2
    src = 3
    one_minus_src = 4
    src_alpha = 5
    one_minus_src_alpha = 6
    dst = 7
    one_minus_dst = 8
    dst_alpha = 9
    one_minus_dst_alpha = 10
    src_alpha_saturated = 11
    constant = 12
    one_minus_constant = 13
    src1 = 14
    one_minus_src1 = 15
    src1_alpha = 16
    one_minus_src1_alpha = 17


class BlendOperation(enum.IntEnum):
    undefined = 0
    add = 1
    subtract = 2
    reverse_subtract = 3
    min = 4
    max = 5


class BufferBindingType(enum.IntEnum):
    binding_not_used = 0
    undefined = 1
    uniform = 2
    storage = 3
    read_only_storage = 4


class BufferMapState(enum.IntEnum):
    unmapped = 1
    pending = 2
    mapped = 3


class CallbackMode(enum.IntEnum):
    """The callback mode controls how a callback for an asynchronous operation may be fired. See @ref Asynchronous-Operations for how these are used."""
    wait_any_only = 1
    allow_process_events = 2
    allow_spontaneous = 3


class CompareFunction(enum.IntEnum):
    undefined = 0
    never = 1
    less = 2
    equal = 3
    less_equal = 4
    greater = 5
    not_equal = 6
    greater_equal = 7
    always = 8


class CompilationInfoRequestStatus(enum.IntEnum):
    success = 1
    callback_cancelled = 2


class CompilationMessageType(enum.IntEnum):
    error = 1
    warning = 2
    info = 3


class ComponentSwizzle(enum.IntEnum):
    undefined = 0
    zero = 1
    one = 2
    r = 3
    g = 4
    b = 5
    a = 6


class CompositeAlphaMode(enum.IntEnum):
    """Describes how frames are composited with other contents on the screen when @ref wgpuSurfacePresent is called."""
    auto = 0
    opaque = 1
    premultiplied = 2
    unpremultiplied = 3
    inherit = 4


class CreatePipelineAsyncStatus(enum.IntEnum):
    success = 1
    callback_cancelled = 2
    validation_error = 3
    internal_error = 4


class CullMode(enum.IntEnum):
    undefined = 0
    none = 1
    front = 2
    back = 3


class DeviceLostReason(enum.IntEnum):
    unknown = 1
    destroyed = 2
    callback_cancelled = 3
    failed_creation = 4


class ErrorFilter(enum.IntEnum):
    validation = 1
    out_of_memory = 2
    internal = 3


class ErrorType(enum.IntEnum):
    no_error = 1
    validation = 2
    out_of_memory = 3
    internal = 4
    unknown = 5


class FeatureLevel(enum.IntEnum):
    """See @ref WGPURequestAdapterOptions::featureLevel."""
    undefined = 0
    compatibility = 1
    core = 2


class FeatureName(enum.IntEnum):
    core_features_and_limits = 1
    depth_clip_control = 2
    depth32_float_stencil8 = 3
    texture_compression_BC = 4
    texture_compression_BC_sliced_3D = 5
    texture_compression_ETC2 = 6
    texture_compression_ASTC = 7
    texture_compression_ASTC_sliced_3D = 8
    timestamp_query = 9
    indirect_first_instance = 10
    shader_f16 = 11
    RG11B10_ufloat_renderable = 12
    BGRA8_unorm_storage = 13
    float32_filterable = 14
    float32_blendable = 15
    clip_distances = 16
    dual_source_blending = 17
    subgroups = 18
    texture_formats_tier_1 = 19
    texture_formats_tier_2 = 20
    primitive_index = 21
    texture_component_swizzle = 22


class FilterMode(enum.IntEnum):
    undefined = 0
    nearest = 1
    linear = 2


class FrontFace(enum.IntEnum):
    undefined = 0
    CCW = 1
    CW = 2


class IndexFormat(enum.IntEnum):
    undefined = 0
    uint16 = 1
    uint32 = 2


class InstanceFeatureName(enum.IntEnum):
    timed_wait_any = 1
    shader_source_SPIRV = 2
    multiple_devices_per_adapter = 3


class LoadOp(enum.IntEnum):
    undefined = 0
    load = 1
    clear = 2


class MapAsyncStatus(enum.IntEnum):
    success = 1
    callback_cancelled = 2
    error = 3
    aborted = 4


class MipmapFilterMode(enum.IntEnum):
    undefined = 0
    nearest = 1
    linear = 2


class OptionalBool(enum.IntEnum):
    false = 0
    true = 1
    undefined = 2


class PopErrorScopeStatus(enum.IntEnum):
    success = 1
    callback_cancelled = 2
    error = 3


class PowerPreference(enum.IntEnum):
    undefined = 0
    low_power = 1
    high_performance = 2


class PredefinedColorSpace(enum.IntEnum):
    SRGB = 1
    display_p3 = 2


class PresentMode(enum.IntEnum):
    """Describes when and in which order frames are presented on the screen when @ref wgpuSurfacePresent is called."""
    undefined = 0
    fifo = 1
    fifo_relaxed = 2
    immediate = 3
    mailbox = 4


class PrimitiveTopology(enum.IntEnum):
    undefined = 0
    point_list = 1
    line_list = 2
    line_strip = 3
    triangle_list = 4
    triangle_strip = 5


class QueryType(enum.IntEnum):
    occlusion = 1
    timestamp = 2


class QueueWorkDoneStatus(enum.IntEnum):
    success = 1
    callback_cancelled = 2
    error = 3


class RequestAdapterStatus(enum.IntEnum):
    success = 1
    callback_cancelled = 2
    unavailable = 3
    error = 4


class RequestDeviceStatus(enum.IntEnum):
    success = 1
    callback_cancelled = 2
    error = 3


class SType(enum.IntEnum):
    shader_source_SPIRV = 1
    shader_source_WGSL = 2
    render_pass_max_draw_count = 3
    surface_source_metal_layer = 4
    surface_source_windows_HWND = 5
    surface_source_xlib_window = 6
    surface_source_wayland_surface = 7
    surface_source_android_native_window = 8
    surface_source_XCB_window = 9
    surface_color_management = 10
    request_adapter_WebXR_options = 11
    texture_component_swizzle_descriptor = 12
    external_texture_binding_layout = 13
    external_texture_binding_entry = 14
    compatibility_mode_limits = 15
    texture_binding_view_dimension = 16


class SamplerBindingType(enum.IntEnum):
    binding_not_used = 0
    undefined = 1
    filtering = 2
    non_filtering = 3
    comparison = 4


class Status(enum.IntEnum):
    """
    Status code returned (synchronously) from many operations. Generally
    indicates an invalid input like an unknown enum value or @ref OutStructChainError.
    Read the function's documentation for specific error conditions.
    """
    success = 1
    error = 2


class StencilOperation(enum.IntEnum):
    undefined = 0
    keep = 1
    zero = 2
    replace = 3
    invert = 4
    increment_clamp = 5
    decrement_clamp = 6
    increment_wrap = 7
    decrement_wrap = 8


class StorageTextureAccess(enum.IntEnum):
    binding_not_used = 0
    undefined = 1
    write_only = 2
    read_only = 3
    read_write = 4


class StoreOp(enum.IntEnum):
    undefined = 0
    store = 1
    discard = 2


class SurfaceGetCurrentTextureStatus(enum.IntEnum):
    """The status enum for @ref wgpuSurfaceGetCurrentTexture."""
    success_optimal = 1
    success_suboptimal = 2
    timeout = 3
    outdated = 4
    lost = 5
    error = 6


class TextureAspect(enum.IntEnum):
    undefined = 0
    all = 1
    stencil_only = 2
    depth_only = 3


class TextureDimension(enum.IntEnum):
    undefined = 0
    _1D = 1
    _2D = 2
    _3D = 3


class TextureFormat(enum.IntEnum):
    undefined = 0
    R8_unorm = 1
    R8_snorm = 2
    R8_uint = 3
    R8_sint = 4
    R16_unorm = 5
    R16_snorm = 6
    R16_uint = 7
    R16_sint = 8
    R16_float = 9
    RG8_unorm = 10
    RG8_snorm = 11
    RG8_uint = 12
    RG8_sint = 13
    R32_float = 14
    R32_uint = 15
    R32_sint = 16
    RG16_unorm = 17
    RG16_snorm = 18
    RG16_uint = 19
    RG16_sint = 20
    RG16_float = 21
    RGBA8_unorm = 22
    RGBA8_unorm_srgb = 23
    RGBA8_snorm = 24
    RGBA8_uint = 25
    RGBA8_sint = 26
    BGRA8_unorm = 27
    BGRA8_unorm_srgb = 28
    RGB10_A2_uint = 29
    RGB10_A2_unorm = 30
    RG11_B10_ufloat = 31
    RGB9_E5_ufloat = 32
    RG32_float = 33
    RG32_uint = 34
    RG32_sint = 35
    RGBA16_unorm = 36
    RGBA16_snorm = 37
    RGBA16_uint = 38
    RGBA16_sint = 39
    RGBA16_float = 40
    RGBA32_float = 41
    RGBA32_uint = 42
    RGBA32_sint = 43
    stencil8 = 44
    depth16_unorm = 45
    depth24_plus = 46
    depth24_plus_stencil8 = 47
    depth32_float = 48
    depth32_float_stencil8 = 49
    BC1_RGBA_unorm = 50
    BC1_RGBA_unorm_srgb = 51
    BC2_RGBA_unorm = 52
    BC2_RGBA_unorm_srgb = 53
    BC3_RGBA_unorm = 54
    BC3_RGBA_unorm_srgb = 55
    BC4_R_unorm = 56
    BC4_R_snorm = 57
    BC5_RG_unorm = 58
    BC5_RG_snorm = 59
    BC6H_RGB_ufloat = 60
    BC6H_RGB_float = 61
    BC7_RGBA_unorm = 62
    BC7_RGBA_unorm_srgb = 63
    ETC2_RGB8_unorm = 64
    ETC2_RGB8_unorm_srgb = 65
    ETC2_RGB8A1_unorm = 66
    ETC2_RGB8A1_unorm_srgb = 67
    ETC2_RGBA8_unorm = 68
    ETC2_RGBA8_unorm_srgb = 69
    EAC_R11_unorm = 70
    EAC_R11_snorm = 71
    EAC_RG11_unorm = 72
    EAC_RG11_snorm = 73
    ASTC_4x4_unorm = 74
    ASTC_4x4_unorm_srgb = 75
    ASTC_5x4_unorm = 76
    ASTC_5x4_unorm_srgb = 77
    ASTC_5x5_unorm = 78
    ASTC_5x5_unorm_srgb = 79
    ASTC_6x5_unorm = 80
    ASTC_6x5_unorm_srgb = 81
    ASTC_6x6_unorm = 82
    ASTC_6x6_unorm_srgb = 83
    ASTC_8x5_unorm = 84
    ASTC_8x5_unorm_srgb = 85
    ASTC_8x6_unorm = 86
    ASTC_8x6_unorm_srgb = 87
    ASTC_8x8_unorm = 88
    ASTC_8x8_unorm_srgb = 89
    ASTC_10x5_unorm = 90
    ASTC_10x5_unorm_srgb = 91
    ASTC_10x6_unorm = 92
    ASTC_10x6_unorm_srgb = 93
    ASTC_10x8_unorm = 94
    ASTC_10x8_unorm_srgb = 95
    ASTC_10x10_unorm = 96
    ASTC_10x10_unorm_srgb = 97
    ASTC_12x10_unorm = 98
    ASTC_12x10_unorm_srgb = 99
    ASTC_12x12_unorm = 100
    ASTC_12x12_unorm_srgb = 101


class TextureSampleType(enum.IntEnum):
    binding_not_used = 0
    undefined = 1
    float = 2
    unfilterable_float = 3
    depth = 4
    sint = 5
    uint = 6


class TextureViewDimension(enum.IntEnum):
    undefined = 0
    _1D = 1
    _2D = 2
    _2D_array = 3
    cube = 4
    cube_array = 5
    _3D = 6


class ToneMappingMode(enum.IntEnum):
    standard = 1
    extended = 2


class VertexFormat(enum.IntEnum):
    uint8 = 1
    uint8x2 = 2
    uint8x4 = 3
    sint8 = 4
    sint8x2 = 5
    sint8x4 = 6
    unorm8 = 7
    unorm8x2 = 8
    unorm8x4 = 9
    snorm8 = 10
    snorm8x2 = 11
    snorm8x4 = 12
    uint16 = 13
    uint16x2 = 14
    uint16x4 = 15
    sint16 = 16
    sint16x2 = 17
    sint16x4 = 18
    unorm16 = 19
    unorm16x2 = 20
    unorm16x4 = 21
    snorm16 = 22
    snorm16x2 = 23
    snorm16x4 = 24
    float16 = 25
    float16x2 = 26
    float16x4 = 27
    float32 = 28
    float32x2 = 29
    float32x3 = 30
    float32x4 = 31
    uint32 = 32
    uint32x2 = 33
    uint32x3 = 34
    uint32x4 = 35
    sint32 = 36
    sint32x2 = 37
    sint32x3 = 38
    sint32x4 = 39
    unorm10__10__10__2 = 40
    unorm8x4_B_G_R_A = 41


class VertexStepMode(enum.IntEnum):
    undefined = 0
    vertex = 1
    instance = 2


class WaitStatus(enum.IntEnum):
    """Status returned from a call to ::wgpuInstanceWaitAny."""
    success = 1
    timed_out = 2
    error = 3


class WGSLLanguageFeatureName(enum.IntEnum):
    readonly_and_readwrite_storage_textures = 1
    packed4x8_integer_dot_product = 2
    unrestricted_pointer_parameters = 3
    pointer_composite_access = 4
    uniform_buffer_standard_layout = 5
    subgroup_id = 6
    texture_and_sampler_let = 7
    subgroup_uniformity = 8
    texture_formats_tier1 = 9
    linear_indexing = 10

BY_SPEC_NAME = {
    'adapter_type': AdapterType,
    'address_mode': AddressMode,
    'backend_type': BackendType,
    'blend_factor': BlendFactor,
    'blend_operation': BlendOperation,
    'buffer_binding_type': BufferBindingType,
    'buffer_map_state': BufferMapState,
    'callback_mode': CallbackMode,
    'compare_function': CompareFunction,
    'compilation_info_request_status': CompilationInfoRequestStatus,
    'compilation_message_type': CompilationMessageType,
    'component_swizzle': ComponentSwizzle,
    'composite_alpha_mode': CompositeAlphaMode,
    'create_pipeline_async_status': CreatePipelineAsyncStatus,
    'cull_mode': CullMode,
    'device_lost_reason': DeviceLostReason,
    'error_filter': ErrorFilter,
    'error_type': ErrorType,
    'feature_level': FeatureLevel,
    'feature_name': FeatureName,
    'filter_mode': FilterMode,
    'front_face': FrontFace,
    'index_format': IndexFormat,
    'instance_feature_name': InstanceFeatureName,
    'load_op': LoadOp,
    'map_async_status': MapAsyncStatus,
    'mipmap_filter_mode': MipmapFilterMode,
    'optional_bool': OptionalBool,
    'pop_error_scope_status': PopErrorScopeStatus,
    'power_preference': PowerPreference,
    'predefined_color_space': PredefinedColorSpace,
    'present_mode': PresentMode,
    'primitive_topology': PrimitiveTopology,
    'query_type': QueryType,
    'queue_work_done_status': QueueWorkDoneStatus,
    'request_adapter_status': RequestAdapterStatus,
    'request_device_status': RequestDeviceStatus,
    's_type': SType,
    'sampler_binding_type': SamplerBindingType,
    'status': Status,
    'stencil_operation': StencilOperation,
    'storage_texture_access': StorageTextureAccess,
    'store_op': StoreOp,
    'surface_get_current_texture_status': SurfaceGetCurrentTextureStatus,
    'texture_aspect': TextureAspect,
    'texture_dimension': TextureDimension,
    'texture_format': TextureFormat,
    'texture_sample_type': TextureSampleType,
    'texture_view_dimension': TextureViewDimension,
    'tone_mapping_mode': ToneMappingMode,
    'vertex_format': VertexFormat,
    'vertex_step_mode': VertexStepMode,
    'wait_status': WaitStatus,
    'WGSL_language_feature_name': WGSLLanguageFeatureName,
}
