# AUTO-GENERATED by `python -m bindgen.generate`. DO NOT EDIT.
#
# Source of truth: wgpu-native/ffi/webgpu-headers/webgpu.json (the machine-
# readable WebGPU spec) plus the compiled extension for enum values. Re-run the
# generator after bumping the wgpu-native submodule.

import enum


class BufferUsage(enum.IntFlag):
    none = 0
    map_read = 1
    map_write = 2
    copy_src = 4
    copy_dst = 8
    index = 16
    vertex = 32
    uniform = 64
    storage = 128
    indirect = 256
    query_resolve = 512


class ColorWriteMask(enum.IntFlag):
    none = 0
    red = 1
    green = 2
    blue = 4
    alpha = 8
    all = 15


class MapMode(enum.IntFlag):
    none = 0
    read = 1
    write = 2


class ShaderStage(enum.IntFlag):
    none = 0
    vertex = 1
    fragment = 2
    compute = 4


class TextureUsage(enum.IntFlag):
    none = 0
    copy_src = 1
    copy_dst = 2
    texture_binding = 4
    storage_binding = 8
    render_attachment = 16
    transient_attachment = 32

